// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	bob "github.com/stephenafamo/bob"
	mock "github.com/stretchr/testify/mock"
)

// MockTrxService is an autogenerated mock type for the TrxService type
type MockTrxService struct {
	mock.Mock
}

type MockTrxService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrxService) EXPECT() *MockTrxService_Expecter {
	return &MockTrxService_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *MockTrxService) WithTx(ctx context.Context, fn func(tx bob.Executor) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(bob.Executor) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTrxService_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockTrxService_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(tx bob.Executor) error
func (_e *MockTrxService_Expecter) WithTx(ctx interface{}, fn interface{}) *MockTrxService_WithTx_Call {
	return &MockTrxService_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *MockTrxService_WithTx_Call) Run(run func(ctx context.Context, fn func(bob.Executor) error)) *MockTrxService_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(bob.Executor) error))
	})
	return _c
}

func (_c *MockTrxService_WithTx_Call) Return(_a0 error) *MockTrxService_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrxService_WithTx_Call) RunAndReturn(run func(context.Context, func(bob.Executor) error) error) *MockTrxService_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTrxService creates a new instance of MockTrxService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrxService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrxService {
	mock := &MockTrxService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
