with-expecter: true
resolve-type-alias: False
disable-version-string: True
issue-845-fix: True
packages:
  github.com/letenk/golang-authentication/internal/applications/user/repository/db:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      UserRepository:
  github.com/letenk/golang-authentication/internal/applications/refresh_token/repository/db:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      RefreshTokenRepository:
  github.com/letenk/golang-authentication/internal/applications/auth/service:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      AuthService:
