// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/google/wire"
	"github.com/letenk/golang-authentication/configs/credential"
	"github.com/letenk/golang-authentication/configs/database"
	"github.com/letenk/golang-authentication/configs/jwt_config"
	"github.com/letenk/golang-authentication/internal/applications/auth/service"
	emailSvc "github.com/letenk/golang-authentication/internal/applications/email/service"
	otpRepo "github.com/letenk/golang-authentication/internal/applications/otp/repository/db"
	tokenRepo "github.com/letenk/golang-authentication/internal/applications/refresh_token/repository/db"
	"github.com/letenk/golang-authentication/internal/applications/transaction"
	userRepo "github.com/letenk/golang-authentication/internal/applications/user/repository/db"
)

// Injectors from auth_injector.go:

// InitializeAuthService initializes all dependencies for AuthController
func InitializeAuthService(
	db *database.BobDB,
	jwtConfig *jwt_config.JWTConfig,
	emailService emailSvc.EmailService,
	otpConfig *credential.OTPConfig,
) *service.AuthServiceImpl {
	userRepositoryImpl := userRepo.NewUserRepository(db)
	refreshTokenRepositoryImpl := tokenRepo.NewRefreshTokenRepository(db)
	otpRepositoryImpl := otpRepo.NewOTPRepository(db)
	trxService := transaction.NewTrxService(db)
	authServiceImpl := service.NewAuthService(trxService, userRepositoryImpl, refreshTokenRepositoryImpl, otpRepositoryImpl, emailService, jwtConfig, otpConfig)
	return authServiceImpl
}

// auth_injector.go:

var providerSetAuth = wire.NewSet(
	userRepo.NewUserRepository,
	wire.Bind(new(userRepo.UserRepository), new(*userRepo.UserRepositoryImpl)),
	tokenRepo.NewRefreshTokenRepository,
	wire.Bind(new(tokenRepo.RefreshTokenRepository), new(*tokenRepo.RefreshTokenRepositoryImpl)),
	otpRepo.NewOTPRepository,
	wire.Bind(new(otpRepo.OTPRepository), new(*otpRepo.OTPRepositoryImpl)),
	transaction.NewTrxService,
	service.NewAuthService,
	wire.Bind(new(service.AuthService), new(*service.AuthServiceImpl)),
)
