// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/letenk/golang-authentication/bob/models"
	mock "github.com/stretchr/testify/mock"
)

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// CountActiveByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenRepository) CountActiveByUserID(ctx context.Context, userID int64) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveByUserID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_CountActiveByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActiveByUserID'
type MockRefreshTokenRepository_CountActiveByUserID_Call struct {
	*mock.Call
}

// CountActiveByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockRefreshTokenRepository_Expecter) CountActiveByUserID(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_CountActiveByUserID_Call {
	return &MockRefreshTokenRepository_CountActiveByUserID_Call{Call: _e.mock.On("CountActiveByUserID", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_CountActiveByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockRefreshTokenRepository_CountActiveByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_CountActiveByUserID_Call) Return(_a0 int, _a1 error) *MockRefreshTokenRepository_CountActiveByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_CountActiveByUserID_Call) RunAndReturn(run func(context.Context, int64) (int, error)) *MockRefreshTokenRepository_CountActiveByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, token
func (_m *MockRefreshTokenRepository) Create(ctx context.Context, token *models.RefreshTokenSetter) (*models.RefreshToken, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RefreshTokenSetter) (*models.RefreshToken, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.RefreshTokenSetter) *models.RefreshToken); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.RefreshTokenSetter) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *models.RefreshTokenSetter
func (_e *MockRefreshTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *MockRefreshTokenRepository_Create_Call {
	return &MockRefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockRefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, token *models.RefreshTokenSetter)) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.RefreshTokenSetter))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) Return(_a0 *models.RefreshToken, _a1 error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) RunAndReturn(run func(context.Context, *models.RefreshTokenSetter) (*models.RefreshToken, error)) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenRepository) FindActiveByUserID(ctx context.Context, userID int64) ([]*models.RefreshToken, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByUserID")
	}

	var r0 []*models.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*models.RefreshToken, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*models.RefreshToken); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_FindActiveByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByUserID'
type MockRefreshTokenRepository_FindActiveByUserID_Call struct {
	*mock.Call
}

// FindActiveByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockRefreshTokenRepository_Expecter) FindActiveByUserID(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_FindActiveByUserID_Call {
	return &MockRefreshTokenRepository_FindActiveByUserID_Call{Call: _e.mock.On("FindActiveByUserID", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_FindActiveByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockRefreshTokenRepository_FindActiveByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_FindActiveByUserID_Call) Return(_a0 []*models.RefreshToken, _a1 error) *MockRefreshTokenRepository_FindActiveByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_FindActiveByUserID_Call) RunAndReturn(run func(context.Context, int64) ([]*models.RefreshToken, error)) *MockRefreshTokenRepository_FindActiveByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByToken provides a mock function with given fields: ctx, token
func (_m *MockRefreshTokenRepository) FindByToken(ctx context.Context, token string) (*models.RefreshToken, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *models.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.RefreshToken, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.RefreshToken); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type MockRefreshTokenRepository_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockRefreshTokenRepository_Expecter) FindByToken(ctx interface{}, token interface{}) *MockRefreshTokenRepository_FindByToken_Call {
	return &MockRefreshTokenRepository_FindByToken_Call{Call: _e.mock.On("FindByToken", ctx, token)}
}

func (_c *MockRefreshTokenRepository_FindByToken_Call) Run(run func(ctx context.Context, token string)) *MockRefreshTokenRepository_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_FindByToken_Call) Return(_a0 *models.RefreshToken, _a1 error) *MockRefreshTokenRepository_FindByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_FindByToken_Call) RunAndReturn(run func(context.Context, string) (*models.RefreshToken, error)) *MockRefreshTokenRepository_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceToken provides a mock function with given fields: ctx, oldToken, newToken
func (_m *MockRefreshTokenRepository) ReplaceToken(ctx context.Context, oldToken string, newToken string) error {
	ret := _m.Called(ctx, oldToken, newToken)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, oldToken, newToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_ReplaceToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceToken'
type MockRefreshTokenRepository_ReplaceToken_Call struct {
	*mock.Call
}

// ReplaceToken is a helper method to define mock.On call
//   - ctx context.Context
//   - oldToken string
//   - newToken string
func (_e *MockRefreshTokenRepository_Expecter) ReplaceToken(ctx interface{}, oldToken interface{}, newToken interface{}) *MockRefreshTokenRepository_ReplaceToken_Call {
	return &MockRefreshTokenRepository_ReplaceToken_Call{Call: _e.mock.On("ReplaceToken", ctx, oldToken, newToken)}
}

func (_c *MockRefreshTokenRepository_ReplaceToken_Call) Run(run func(ctx context.Context, oldToken string, newToken string)) *MockRefreshTokenRepository_ReplaceToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_ReplaceToken_Call) Return(_a0 error) *MockRefreshTokenRepository_ReplaceToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_ReplaceToken_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRefreshTokenRepository_ReplaceToken_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, token
func (_m *MockRefreshTokenRepository) Revoke(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockRefreshTokenRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockRefreshTokenRepository_Expecter) Revoke(ctx interface{}, token interface{}) *MockRefreshTokenRepository_Revoke_Call {
	return &MockRefreshTokenRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, token)}
}

func (_c *MockRefreshTokenRepository_Revoke_Call) Run(run func(ctx context.Context, token string)) *MockRefreshTokenRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Revoke_Call) Return(_a0 error) *MockRefreshTokenRepository_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_Revoke_Call) RunAndReturn(run func(context.Context, string) error) *MockRefreshTokenRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenRepository) RevokeAllByUserID(ctx context.Context, userID int64) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllByUserID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_RevokeAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllByUserID'
type MockRefreshTokenRepository_RevokeAllByUserID_Call struct {
	*mock.Call
}

// RevokeAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockRefreshTokenRepository_Expecter) RevokeAllByUserID(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_RevokeAllByUserID_Call {
	return &MockRefreshTokenRepository_RevokeAllByUserID_Call{Call: _e.mock.On("RevokeAllByUserID", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_RevokeAllByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockRefreshTokenRepository_RevokeAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeAllByUserID_Call) Return(_a0 int, _a1 error) *MockRefreshTokenRepository_RevokeAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeAllByUserID_Call) RunAndReturn(run func(context.Context, int64) (int, error)) *MockRefreshTokenRepository_RevokeAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByIDForUser provides a mock function with given fields: ctx, sessionID, userID
func (_m *MockRefreshTokenRepository) RevokeByIDForUser(ctx context.Context, sessionID int64, userID int64) error {
	ret := _m.Called(ctx, sessionID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByIDForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, sessionID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeByIDForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByIDForUser'
type MockRefreshTokenRepository_RevokeByIDForUser_Call struct {
	*mock.Call
}

// RevokeByIDForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID int64
//   - userID int64
func (_e *MockRefreshTokenRepository_Expecter) RevokeByIDForUser(ctx interface{}, sessionID interface{}, userID interface{}) *MockRefreshTokenRepository_RevokeByIDForUser_Call {
	return &MockRefreshTokenRepository_RevokeByIDForUser_Call{Call: _e.mock.On("RevokeByIDForUser", ctx, sessionID, userID)}
}

func (_c *MockRefreshTokenRepository_RevokeByIDForUser_Call) Run(run func(ctx context.Context, sessionID int64, userID int64)) *MockRefreshTokenRepository_RevokeByIDForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeByIDForUser_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeByIDForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeByIDForUser_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockRefreshTokenRepository_RevokeByIDForUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
