// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	bob "github.com/stephenafamo/bob"
	mock "github.com/stretchr/testify/mock"

	models "github.com/letenk/golang-authentication/bob/models"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, entity
func (_m *MockUserRepository) Create(ctx context.Context, entity *models.UserSetter) (*models.User, error) {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserSetter) (*models.User, error)); ok {
		return rf(ctx, entity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserSetter) *models.User); ok {
		r0 = rf(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UserSetter) error); ok {
		r1 = rf(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *models.UserSetter
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, entity interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, entity *models.UserSetter)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UserSetter))
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(context.Context, *models.UserSetter) (*models.User, error)) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserRepository) FindByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUserRepository_FindByEmail_Call {
	return &MockUserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) FindByID(ctx context.Context, id int64) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUserRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockUserRepository_FindByID_Call {
	return &MockUserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockUserRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockUserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUserRepository_FindByID_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*models.User, error)) *MockUserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPhone provides a mock function with given fields: ctx, phone
func (_m *MockUserRepository) FindByPhone(ctx context.Context, phone string) (*models.User, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for FindByPhone")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPhone'
type MockUserRepository_FindByPhone_Call struct {
	*mock.Call
}

// FindByPhone is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockUserRepository_Expecter) FindByPhone(ctx interface{}, phone interface{}) *MockUserRepository_FindByPhone_Call {
	return &MockUserRepository_FindByPhone_Call{Call: _e.mock.On("FindByPhone", ctx, phone)}
}

func (_c *MockUserRepository_FindByPhone_Call) Run(run func(ctx context.Context, phone string)) *MockUserRepository_FindByPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindByPhone_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_FindByPhone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByPhone_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockUserRepository_FindByPhone_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteByID provides a mock function with given fields: ctx, id, deletedBy
func (_m *MockUserRepository) SoftDeleteByID(ctx context.Context, id int64, deletedBy int64) error {
	ret := _m.Called(ctx, id, deletedBy)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, id, deletedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_SoftDeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteByID'
type MockUserRepository_SoftDeleteByID_Call struct {
	*mock.Call
}

// SoftDeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - deletedBy int64
func (_e *MockUserRepository_Expecter) SoftDeleteByID(ctx interface{}, id interface{}, deletedBy interface{}) *MockUserRepository_SoftDeleteByID_Call {
	return &MockUserRepository_SoftDeleteByID_Call{Call: _e.mock.On("SoftDeleteByID", ctx, id, deletedBy)}
}

func (_c *MockUserRepository_SoftDeleteByID_Call) Run(run func(ctx context.Context, id int64, deletedBy int64)) *MockUserRepository_SoftDeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockUserRepository_SoftDeleteByID_Call) Return(_a0 error) *MockUserRepository_SoftDeleteByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_SoftDeleteByID_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockUserRepository_SoftDeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function with given fields: ctx, id, setter
func (_m *MockUserRepository) UpdateByID(ctx context.Context, id int64, setter *models.UserSetter) (*models.User, error) {
	ret := _m.Called(ctx, id, setter)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *models.UserSetter) (*models.User, error)); ok {
		return rf(ctx, id, setter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *models.UserSetter) *models.User); ok {
		r0 = rf(ctx, id, setter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *models.UserSetter) error); ok {
		r1 = rf(ctx, id, setter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockUserRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - setter *models.UserSetter
func (_e *MockUserRepository_Expecter) UpdateByID(ctx interface{}, id interface{}, setter interface{}) *MockUserRepository_UpdateByID_Call {
	return &MockUserRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, setter)}
}

func (_c *MockUserRepository_UpdateByID_Call) Run(run func(ctx context.Context, id int64, setter *models.UserSetter)) *MockUserRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*models.UserSetter))
	})
	return _c
}

func (_c *MockUserRepository_UpdateByID_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_UpdateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_UpdateByID_Call) RunAndReturn(run func(context.Context, int64, *models.UserSetter) (*models.User, error)) *MockUserRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePasswordWithExec provides a mock function with given fields: ctx, exec, userID, hashedPassword
func (_m *MockUserRepository) UpdatePasswordWithExec(ctx context.Context, exec bob.Executor, userID int64, hashedPassword string) error {
	ret := _m.Called(ctx, exec, userID, hashedPassword)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePasswordWithExec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bob.Executor, int64, string) error); ok {
		r0 = rf(ctx, exec, userID, hashedPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdatePasswordWithExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePasswordWithExec'
type MockUserRepository_UpdatePasswordWithExec_Call struct {
	*mock.Call
}

// UpdatePasswordWithExec is a helper method to define mock.On call
//   - ctx context.Context
//   - exec bob.Executor
//   - userID int64
//   - hashedPassword string
func (_e *MockUserRepository_Expecter) UpdatePasswordWithExec(ctx, exec, userID, hashedPassword interface{}) *MockUserRepository_UpdatePasswordWithExec_Call {
	return &MockUserRepository_UpdatePasswordWithExec_Call{Call: _e.mock.On("UpdatePasswordWithExec", ctx, exec, userID, hashedPassword)}
}

func (_c *MockUserRepository_UpdatePasswordWithExec_Call) Run(run func(ctx context.Context, exec bob.Executor, userID int64, hashedPassword string)) *MockUserRepository_UpdatePasswordWithExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bob.Executor), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *MockUserRepository_UpdatePasswordWithExec_Call) Return(_a0 error) *MockUserRepository_UpdatePasswordWithExec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdatePasswordWithExec_Call) RunAndReturn(run func(context.Context, bob.Executor, int64, string) error) *MockUserRepository_UpdatePasswordWithExec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
