// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	models "github.com/letenk/golang-authentication/bob/models"
)

type Factory struct {
	baseEmailVerificationOtpMods EmailVerificationOtpModSlice
	baseGooseDBVersionMods       GooseDBVersionModSlice
	basePasswordResetOtpMods     PasswordResetOtpModSlice
	baseRefreshTokenMods         RefreshTokenModSlice
	baseUserMods                 UserModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewEmailVerificationOtp(mods ...EmailVerificationOtpMod) *EmailVerificationOtpTemplate {
	return f.NewEmailVerificationOtpWithContext(context.Background(), mods...)
}

func (f *Factory) NewEmailVerificationOtpWithContext(ctx context.Context, mods ...EmailVerificationOtpMod) *EmailVerificationOtpTemplate {
	o := &EmailVerificationOtpTemplate{f: f}

	if f != nil {
		f.baseEmailVerificationOtpMods.Apply(ctx, o)
	}

	EmailVerificationOtpModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingEmailVerificationOtp(m *models.EmailVerificationOtp) *EmailVerificationOtpTemplate {
	o := &EmailVerificationOtpTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.UserID = func() int64 { return m.UserID }
	o.Code = func() string { return m.Code }
	o.ExpiresAt = func() time.Time { return m.ExpiresAt }
	o.UsedAt = func() null.Val[time.Time] { return m.UsedAt }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }

	ctx := context.Background()
	if m.R.User != nil {
		EmailVerificationOtpMods.WithExistingUser(m.R.User).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewGooseDBVersion(mods ...GooseDBVersionMod) *GooseDBVersionTemplate {
	return f.NewGooseDBVersionWithContext(context.Background(), mods...)
}

func (f *Factory) NewGooseDBVersionWithContext(ctx context.Context, mods ...GooseDBVersionMod) *GooseDBVersionTemplate {
	o := &GooseDBVersionTemplate{f: f}

	if f != nil {
		f.baseGooseDBVersionMods.Apply(ctx, o)
	}

	GooseDBVersionModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingGooseDBVersion(m *models.GooseDBVersion) *GooseDBVersionTemplate {
	o := &GooseDBVersionTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.VersionID = func() int64 { return m.VersionID }
	o.IsApplied = func() bool { return m.IsApplied }
	o.Tstamp = func() time.Time { return m.Tstamp }

	return o
}

func (f *Factory) NewPasswordResetOtp(mods ...PasswordResetOtpMod) *PasswordResetOtpTemplate {
	return f.NewPasswordResetOtpWithContext(context.Background(), mods...)
}

func (f *Factory) NewPasswordResetOtpWithContext(ctx context.Context, mods ...PasswordResetOtpMod) *PasswordResetOtpTemplate {
	o := &PasswordResetOtpTemplate{f: f}

	if f != nil {
		f.basePasswordResetOtpMods.Apply(ctx, o)
	}

	PasswordResetOtpModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingPasswordResetOtp(m *models.PasswordResetOtp) *PasswordResetOtpTemplate {
	o := &PasswordResetOtpTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.UserID = func() int64 { return m.UserID }
	o.Code = func() string { return m.Code }
	o.ExpiresAt = func() time.Time { return m.ExpiresAt }
	o.UsedAt = func() null.Val[time.Time] { return m.UsedAt }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }

	ctx := context.Background()
	if m.R.User != nil {
		PasswordResetOtpMods.WithExistingUser(m.R.User).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewRefreshToken(mods ...RefreshTokenMod) *RefreshTokenTemplate {
	return f.NewRefreshTokenWithContext(context.Background(), mods...)
}

func (f *Factory) NewRefreshTokenWithContext(ctx context.Context, mods ...RefreshTokenMod) *RefreshTokenTemplate {
	o := &RefreshTokenTemplate{f: f}

	if f != nil {
		f.baseRefreshTokenMods.Apply(ctx, o)
	}

	RefreshTokenModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingRefreshToken(m *models.RefreshToken) *RefreshTokenTemplate {
	o := &RefreshTokenTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.UserID = func() int64 { return m.UserID }
	o.Token = func() string { return m.Token }
	o.DeviceName = func() null.Val[string] { return m.DeviceName }
	o.DeviceID = func() null.Val[string] { return m.DeviceID }
	o.IPAddress = func() null.Val[string] { return m.IPAddress }
	o.UserAgent = func() null.Val[string] { return m.UserAgent }
	o.ExpiresAt = func() time.Time { return m.ExpiresAt }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }
	o.RevokedAt = func() null.Val[time.Time] { return m.RevokedAt }
	o.ReplacedByToken = func() null.Val[string] { return m.ReplacedByToken }

	ctx := context.Background()
	if m.R.User != nil {
		RefreshTokenMods.WithExistingUser(m.R.User).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewUser(mods ...UserMod) *UserTemplate {
	return f.NewUserWithContext(context.Background(), mods...)
}

func (f *Factory) NewUserWithContext(ctx context.Context, mods ...UserMod) *UserTemplate {
	o := &UserTemplate{f: f}

	if f != nil {
		f.baseUserMods.Apply(ctx, o)
	}

	UserModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingUser(m *models.User) *UserTemplate {
	o := &UserTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Version = func() int64 { return m.Version }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }
	o.CreatedBy = func() int64 { return m.CreatedBy }
	o.UpdatedAt = func() null.Val[time.Time] { return m.UpdatedAt }
	o.UpdatedBy = func() int64 { return m.UpdatedBy }
	o.DeletedAt = func() null.Val[time.Time] { return m.DeletedAt }
	o.DeletedBy = func() null.Val[int64] { return m.DeletedBy }
	o.Name = func() null.Val[string] { return m.Name }
	o.Email = func() null.Val[string] { return m.Email }
	o.Phone = func() null.Val[string] { return m.Phone }
	o.Password = func() string { return m.Password }
	o.LoginType = func() string { return m.LoginType }
	o.IsVerified = func() null.Val[bool] { return m.IsVerified }
	o.VerifiedAt = func() null.Val[time.Time] { return m.VerifiedAt }

	ctx := context.Background()
	if len(m.R.EmailVerificationOtps) > 0 {
		UserMods.AddExistingEmailVerificationOtps(m.R.EmailVerificationOtps...).Apply(ctx, o)
	}
	if len(m.R.PasswordResetOtps) > 0 {
		UserMods.AddExistingPasswordResetOtps(m.R.PasswordResetOtps...).Apply(ctx, o)
	}
	if len(m.R.RefreshTokens) > 0 {
		UserMods.AddExistingRefreshTokens(m.R.RefreshTokens...).Apply(ctx, o)
	}
	if m.R.CreatedBy != nil {
		UserMods.WithExistingCreatedBy(m.R.CreatedBy).Apply(ctx, o)
	}
	if len(m.R.ReverseCreatedBies) > 0 {
		UserMods.AddExistingReverseCreatedBies(m.R.ReverseCreatedBies...).Apply(ctx, o)
	}
	if m.R.DeletedBy != nil {
		UserMods.WithExistingDeletedBy(m.R.DeletedBy).Apply(ctx, o)
	}
	if len(m.R.ReverseDeletedBies) > 0 {
		UserMods.AddExistingReverseDeletedBies(m.R.ReverseDeletedBies...).Apply(ctx, o)
	}
	if m.R.UpdatedBy != nil {
		UserMods.WithExistingUpdatedBy(m.R.UpdatedBy).Apply(ctx, o)
	}
	if len(m.R.ReverseUpdatedBies) > 0 {
		UserMods.AddExistingReverseUpdatedBies(m.R.ReverseUpdatedBies...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) ClearBaseEmailVerificationOtpMods() {
	f.baseEmailVerificationOtpMods = nil
}

func (f *Factory) AddBaseEmailVerificationOtpMod(mods ...EmailVerificationOtpMod) {
	f.baseEmailVerificationOtpMods = append(f.baseEmailVerificationOtpMods, mods...)
}

func (f *Factory) ClearBaseGooseDBVersionMods() {
	f.baseGooseDBVersionMods = nil
}

func (f *Factory) AddBaseGooseDBVersionMod(mods ...GooseDBVersionMod) {
	f.baseGooseDBVersionMods = append(f.baseGooseDBVersionMods, mods...)
}

func (f *Factory) ClearBasePasswordResetOtpMods() {
	f.basePasswordResetOtpMods = nil
}

func (f *Factory) AddBasePasswordResetOtpMod(mods ...PasswordResetOtpMod) {
	f.basePasswordResetOtpMods = append(f.basePasswordResetOtpMods, mods...)
}

func (f *Factory) ClearBaseRefreshTokenMods() {
	f.baseRefreshTokenMods = nil
}

func (f *Factory) AddBaseRefreshTokenMod(mods ...RefreshTokenMod) {
	f.baseRefreshTokenMods = append(f.baseRefreshTokenMods, mods...)
}

func (f *Factory) ClearBaseUserMods() {
	f.baseUserMods = nil
}

func (f *Factory) AddBaseUserMod(mods ...UserMod) {
	f.baseUserMods = append(f.baseUserMods, mods...)
}
