// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	models "github.com/letenk/golang-authentication/bob/models"
)

type Factory struct {
	baseGooseDBVersionMods GooseDBVersionModSlice
	baseUserMods           UserModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewGooseDBVersion(mods ...GooseDBVersionMod) *GooseDBVersionTemplate {
	return f.NewGooseDBVersionWithContext(context.Background(), mods...)
}

func (f *Factory) NewGooseDBVersionWithContext(ctx context.Context, mods ...GooseDBVersionMod) *GooseDBVersionTemplate {
	o := &GooseDBVersionTemplate{f: f}

	if f != nil {
		f.baseGooseDBVersionMods.Apply(ctx, o)
	}

	GooseDBVersionModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingGooseDBVersion(m *models.GooseDBVersion) *GooseDBVersionTemplate {
	o := &GooseDBVersionTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.VersionID = func() int64 { return m.VersionID }
	o.IsApplied = func() bool { return m.IsApplied }
	o.Tstamp = func() time.Time { return m.Tstamp }

	return o
}

func (f *Factory) NewUser(mods ...UserMod) *UserTemplate {
	return f.NewUserWithContext(context.Background(), mods...)
}

func (f *Factory) NewUserWithContext(ctx context.Context, mods ...UserMod) *UserTemplate {
	o := &UserTemplate{f: f}

	if f != nil {
		f.baseUserMods.Apply(ctx, o)
	}

	UserModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingUser(m *models.User) *UserTemplate {
	o := &UserTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Version = func() int64 { return m.Version }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }
	o.CreatedBy = func() int64 { return m.CreatedBy }
	o.UpdatedAt = func() null.Val[time.Time] { return m.UpdatedAt }
	o.UpdatedBy = func() int64 { return m.UpdatedBy }
	o.DeletedAt = func() null.Val[time.Time] { return m.DeletedAt }
	o.DeletedBy = func() null.Val[int64] { return m.DeletedBy }
	o.Name = func() null.Val[string] { return m.Name }
	o.Email = func() null.Val[string] { return m.Email }
	o.Phone = func() null.Val[string] { return m.Phone }
	o.Password = func() string { return m.Password }
	o.LoginType = func() string { return m.LoginType }
	o.IsVerified = func() null.Val[bool] { return m.IsVerified }
	o.VerifiedAt = func() null.Val[time.Time] { return m.VerifiedAt }

	ctx := context.Background()
	if m.R.CreatedBy != nil {
		UserMods.WithExistingCreatedBy(m.R.CreatedBy).Apply(ctx, o)
	}
	if len(m.R.ReverseCreatedBies) > 0 {
		UserMods.AddExistingReverseCreatedBies(m.R.ReverseCreatedBies...).Apply(ctx, o)
	}
	if m.R.DeletedBy != nil {
		UserMods.WithExistingDeletedBy(m.R.DeletedBy).Apply(ctx, o)
	}
	if len(m.R.ReverseDeletedBies) > 0 {
		UserMods.AddExistingReverseDeletedBies(m.R.ReverseDeletedBies...).Apply(ctx, o)
	}
	if m.R.UpdatedBy != nil {
		UserMods.WithExistingUpdatedBy(m.R.UpdatedBy).Apply(ctx, o)
	}
	if len(m.R.ReverseUpdatedBies) > 0 {
		UserMods.AddExistingReverseUpdatedBies(m.R.ReverseUpdatedBies...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) ClearBaseGooseDBVersionMods() {
	f.baseGooseDBVersionMods = nil
}

func (f *Factory) AddBaseGooseDBVersionMod(mods ...GooseDBVersionMod) {
	f.baseGooseDBVersionMods = append(f.baseGooseDBVersionMods, mods...)
}

func (f *Factory) ClearBaseUserMods() {
	f.baseUserMods = nil
}

func (f *Factory) AddBaseUserMod(mods ...UserMod) {
	f.baseUserMods = append(f.baseUserMods, mods...)
}
