// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type contextKey string

var (
	// Relationship Contexts for goose_db_version
	gooseDBVersionWithParentsCascadingCtx = newContextual[bool]("gooseDBVersionWithParentsCascading")

	// Relationship Contexts for password_reset_otps
	passwordResetOtpWithParentsCascadingCtx = newContextual[bool]("passwordResetOtpWithParentsCascading")
	passwordResetOtpRelUserCtx              = newContextual[bool]("password_reset_otps.users.password_reset_otps.password_reset_otps_user_id_fkey")

	// Relationship Contexts for refresh_tokens
	refreshTokenWithParentsCascadingCtx = newContextual[bool]("refreshTokenWithParentsCascading")
	refreshTokenRelUserCtx              = newContextual[bool]("refresh_tokens.users.refresh_tokens.refresh_tokens_user_id_fkey")

	// Relationship Contexts for users
	userWithParentsCascadingCtx  = newContextual[bool]("userWithParentsCascading")
	userRelPasswordResetOtpsCtx  = newContextual[bool]("password_reset_otps.users.password_reset_otps.password_reset_otps_user_id_fkey")
	userRelRefreshTokensCtx      = newContextual[bool]("refresh_tokens.users.refresh_tokens.refresh_tokens_user_id_fkey")
	userRelCreatedByCtx          = newContextual[bool]("users.users.users.fk_users_created_by")
	userRelReverseCreatedBiesCtx = newContextual[bool]("users.users.users.fk_users_created_by")
	userRelDeletedByCtx          = newContextual[bool]("users.users.users.fk_users_deleted_by")
	userRelReverseDeletedBiesCtx = newContextual[bool]("users.users.users.fk_users_deleted_by")
	userRelUpdatedByCtx          = newContextual[bool]("users.users.users.fk_users_updated_by")
	userRelReverseUpdatedBiesCtx = newContextual[bool]("users.users.users.fk_users_updated_by")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
