// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/letenk/golang-authentication/bob/models"
	"github.com/stephenafamo/bob"
)

type EmailVerificationOtpMod interface {
	Apply(context.Context, *EmailVerificationOtpTemplate)
}

type EmailVerificationOtpModFunc func(context.Context, *EmailVerificationOtpTemplate)

func (f EmailVerificationOtpModFunc) Apply(ctx context.Context, n *EmailVerificationOtpTemplate) {
	f(ctx, n)
}

type EmailVerificationOtpModSlice []EmailVerificationOtpMod

func (mods EmailVerificationOtpModSlice) Apply(ctx context.Context, n *EmailVerificationOtpTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// EmailVerificationOtpTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type EmailVerificationOtpTemplate struct {
	ID        func() int64
	UserID    func() int64
	Code      func() string
	ExpiresAt func() time.Time
	UsedAt    func() null.Val[time.Time]
	CreatedAt func() null.Val[time.Time]

	r emailVerificationOtpR
	f *Factory

	alreadyPersisted bool
}

type emailVerificationOtpR struct {
	User *emailVerificationOtpRUserR
}

type emailVerificationOtpRUserR struct {
	o *UserTemplate
}

// Apply mods to the EmailVerificationOtpTemplate
func (o *EmailVerificationOtpTemplate) Apply(ctx context.Context, mods ...EmailVerificationOtpMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.EmailVerificationOtp
// according to the relationships in the template. Nothing is inserted into the db
func (t EmailVerificationOtpTemplate) setModelRels(o *models.EmailVerificationOtp) {
	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.EmailVerificationOtps = append(rel.R.EmailVerificationOtps, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.EmailVerificationOtpSetter
// this does nothing with the relationship templates
func (o EmailVerificationOtpTemplate) BuildSetter() *models.EmailVerificationOtpSetter {
	m := &models.EmailVerificationOtpSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.Code != nil {
		val := o.Code()
		m.Code = omit.From(val)
	}
	if o.ExpiresAt != nil {
		val := o.ExpiresAt()
		m.ExpiresAt = omit.From(val)
	}
	if o.UsedAt != nil {
		val := o.UsedAt()
		m.UsedAt = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.EmailVerificationOtpSetter
// this does nothing with the relationship templates
func (o EmailVerificationOtpTemplate) BuildManySetter(number int) []*models.EmailVerificationOtpSetter {
	m := make([]*models.EmailVerificationOtpSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.EmailVerificationOtp
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use EmailVerificationOtpTemplate.Create
func (o EmailVerificationOtpTemplate) Build() *models.EmailVerificationOtp {
	m := &models.EmailVerificationOtp{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.Code != nil {
		m.Code = o.Code()
	}
	if o.ExpiresAt != nil {
		m.ExpiresAt = o.ExpiresAt()
	}
	if o.UsedAt != nil {
		m.UsedAt = o.UsedAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.EmailVerificationOtpSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use EmailVerificationOtpTemplate.CreateMany
func (o EmailVerificationOtpTemplate) BuildMany(number int) models.EmailVerificationOtpSlice {
	m := make(models.EmailVerificationOtpSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableEmailVerificationOtp(m *models.EmailVerificationOtpSetter) {
	if !(m.UserID.IsValue()) {
		val := random_int64(nil)
		m.UserID = omit.From(val)
	}
	if !(m.Code.IsValue()) {
		val := random_string(nil, "10")
		m.Code = omit.From(val)
	}
	if !(m.ExpiresAt.IsValue()) {
		val := random_time_Time(nil)
		m.ExpiresAt = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.EmailVerificationOtp
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *EmailVerificationOtpTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.EmailVerificationOtp) error {
	var err error

	return err
}

// Create builds a emailVerificationOtp and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *EmailVerificationOtpTemplate) Create(ctx context.Context, exec bob.Executor) (*models.EmailVerificationOtp, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableEmailVerificationOtp(opt)

	if o.r.User == nil {
		EmailVerificationOtpMods.WithNewUser().Apply(ctx, o)
	}

	var rel0 *models.User

	if o.r.User.o.alreadyPersisted {
		rel0 = o.r.User.o.Build()
	} else {
		rel0, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel0.ID)

	m, err := models.EmailVerificationOtps.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a emailVerificationOtp and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *EmailVerificationOtpTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.EmailVerificationOtp {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a emailVerificationOtp and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *EmailVerificationOtpTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.EmailVerificationOtp {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple emailVerificationOtps and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o EmailVerificationOtpTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.EmailVerificationOtpSlice, error) {
	var err error
	m := make(models.EmailVerificationOtpSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple emailVerificationOtps and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o EmailVerificationOtpTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.EmailVerificationOtpSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple emailVerificationOtps and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o EmailVerificationOtpTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.EmailVerificationOtpSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// EmailVerificationOtp has methods that act as mods for the EmailVerificationOtpTemplate
var EmailVerificationOtpMods emailVerificationOtpMods

type emailVerificationOtpMods struct{}

func (m emailVerificationOtpMods) RandomizeAllColumns(f *faker.Faker) EmailVerificationOtpMod {
	return EmailVerificationOtpModSlice{
		EmailVerificationOtpMods.RandomID(f),
		EmailVerificationOtpMods.RandomUserID(f),
		EmailVerificationOtpMods.RandomCode(f),
		EmailVerificationOtpMods.RandomExpiresAt(f),
		EmailVerificationOtpMods.RandomUsedAt(f),
		EmailVerificationOtpMods.RandomCreatedAt(f),
	}
}

// Set the model columns to this value
func (m emailVerificationOtpMods) ID(val int64) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m emailVerificationOtpMods) IDFunc(f func() int64) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m emailVerificationOtpMods) UnsetID() EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m emailVerificationOtpMods) RandomID(f *faker.Faker) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m emailVerificationOtpMods) UserID(val int64) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.UserID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m emailVerificationOtpMods) UserIDFunc(f func() int64) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m emailVerificationOtpMods) UnsetUserID() EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m emailVerificationOtpMods) RandomUserID(f *faker.Faker) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.UserID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m emailVerificationOtpMods) Code(val string) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.Code = func() string { return val }
	})
}

// Set the Column from the function
func (m emailVerificationOtpMods) CodeFunc(f func() string) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.Code = f
	})
}

// Clear any values for the column
func (m emailVerificationOtpMods) UnsetCode() EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.Code = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m emailVerificationOtpMods) RandomCode(f *faker.Faker) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.Code = func() string {
			return random_string(f, "10")
		}
	})
}

// Set the model columns to this value
func (m emailVerificationOtpMods) ExpiresAt(val time.Time) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.ExpiresAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m emailVerificationOtpMods) ExpiresAtFunc(f func() time.Time) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.ExpiresAt = f
	})
}

// Clear any values for the column
func (m emailVerificationOtpMods) UnsetExpiresAt() EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.ExpiresAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m emailVerificationOtpMods) RandomExpiresAt(f *faker.Faker) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.ExpiresAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m emailVerificationOtpMods) UsedAt(val null.Val[time.Time]) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.UsedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m emailVerificationOtpMods) UsedAtFunc(f func() null.Val[time.Time]) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.UsedAt = f
	})
}

// Clear any values for the column
func (m emailVerificationOtpMods) UnsetUsedAt() EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.UsedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m emailVerificationOtpMods) RandomUsedAt(f *faker.Faker) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.UsedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m emailVerificationOtpMods) RandomUsedAtNotNull(f *faker.Faker) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.UsedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m emailVerificationOtpMods) CreatedAt(val null.Val[time.Time]) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.CreatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m emailVerificationOtpMods) CreatedAtFunc(f func() null.Val[time.Time]) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m emailVerificationOtpMods) UnsetCreatedAt() EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m emailVerificationOtpMods) RandomCreatedAt(f *faker.Faker) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m emailVerificationOtpMods) RandomCreatedAtNotNull(f *faker.Faker) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(_ context.Context, o *EmailVerificationOtpTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m emailVerificationOtpMods) WithParentsCascading() EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(ctx context.Context, o *EmailVerificationOtpTemplate) {
		if isDone, _ := emailVerificationOtpWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = emailVerificationOtpWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m emailVerificationOtpMods) WithUser(rel *UserTemplate) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(ctx context.Context, o *EmailVerificationOtpTemplate) {
		o.r.User = &emailVerificationOtpRUserR{
			o: rel,
		}
	})
}

func (m emailVerificationOtpMods) WithNewUser(mods ...UserMod) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(ctx context.Context, o *EmailVerificationOtpTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m emailVerificationOtpMods) WithExistingUser(em *models.User) EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(ctx context.Context, o *EmailVerificationOtpTemplate) {
		o.r.User = &emailVerificationOtpRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m emailVerificationOtpMods) WithoutUser() EmailVerificationOtpMod {
	return EmailVerificationOtpModFunc(func(ctx context.Context, o *EmailVerificationOtpTemplate) {
		o.r.User = nil
	})
}
