// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/letenk/golang-authentication/bob/models"
	"github.com/stephenafamo/bob"
)

type OtpMod interface {
	Apply(context.Context, *OtpTemplate)
}

type OtpModFunc func(context.Context, *OtpTemplate)

func (f OtpModFunc) Apply(ctx context.Context, n *OtpTemplate) {
	f(ctx, n)
}

type OtpModSlice []OtpMod

func (mods OtpModSlice) Apply(ctx context.Context, n *OtpTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// OtpTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type OtpTemplate struct {
	ID        func() int64
	UserID    func() int64
	Code      func() string
	Purpose   func() string
	ExpiresAt func() time.Time
	UsedAt    func() null.Val[time.Time]
	CreatedAt func() null.Val[time.Time]

	r otpR
	f *Factory

	alreadyPersisted bool
}

type otpR struct {
	User *otpRUserR
}

type otpRUserR struct {
	o *UserTemplate
}

// Apply mods to the OtpTemplate
func (o *OtpTemplate) Apply(ctx context.Context, mods ...OtpMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Otp
// according to the relationships in the template. Nothing is inserted into the db
func (t OtpTemplate) setModelRels(o *models.Otp) {
	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.Otps = append(rel.R.Otps, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.OtpSetter
// this does nothing with the relationship templates
func (o OtpTemplate) BuildSetter() *models.OtpSetter {
	m := &models.OtpSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.Code != nil {
		val := o.Code()
		m.Code = omit.From(val)
	}
	if o.Purpose != nil {
		val := o.Purpose()
		m.Purpose = omit.From(val)
	}
	if o.ExpiresAt != nil {
		val := o.ExpiresAt()
		m.ExpiresAt = omit.From(val)
	}
	if o.UsedAt != nil {
		val := o.UsedAt()
		m.UsedAt = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.OtpSetter
// this does nothing with the relationship templates
func (o OtpTemplate) BuildManySetter(number int) []*models.OtpSetter {
	m := make([]*models.OtpSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Otp
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OtpTemplate.Create
func (o OtpTemplate) Build() *models.Otp {
	m := &models.Otp{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.Code != nil {
		m.Code = o.Code()
	}
	if o.Purpose != nil {
		m.Purpose = o.Purpose()
	}
	if o.ExpiresAt != nil {
		m.ExpiresAt = o.ExpiresAt()
	}
	if o.UsedAt != nil {
		m.UsedAt = o.UsedAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.OtpSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OtpTemplate.CreateMany
func (o OtpTemplate) BuildMany(number int) models.OtpSlice {
	m := make(models.OtpSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableOtp(m *models.OtpSetter) {
	if !(m.UserID.IsValue()) {
		val := random_int64(nil)
		m.UserID = omit.From(val)
	}
	if !(m.Code.IsValue()) {
		val := random_string(nil, "10")
		m.Code = omit.From(val)
	}
	if !(m.Purpose.IsValue()) {
		val := random_string(nil, "50")
		m.Purpose = omit.From(val)
	}
	if !(m.ExpiresAt.IsValue()) {
		val := random_time_Time(nil)
		m.ExpiresAt = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Otp
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *OtpTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Otp) error {
	var err error

	return err
}

// Create builds a otp and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *OtpTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Otp, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableOtp(opt)

	if o.r.User == nil {
		OtpMods.WithNewUser().Apply(ctx, o)
	}

	var rel0 *models.User

	if o.r.User.o.alreadyPersisted {
		rel0 = o.r.User.o.Build()
	} else {
		rel0, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel0.ID)

	m, err := models.Otps.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a otp and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *OtpTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Otp {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a otp and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *OtpTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Otp {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple otps and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o OtpTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.OtpSlice, error) {
	var err error
	m := make(models.OtpSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple otps and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o OtpTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.OtpSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple otps and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o OtpTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.OtpSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Otp has methods that act as mods for the OtpTemplate
var OtpMods otpMods

type otpMods struct{}

func (m otpMods) RandomizeAllColumns(f *faker.Faker) OtpMod {
	return OtpModSlice{
		OtpMods.RandomID(f),
		OtpMods.RandomUserID(f),
		OtpMods.RandomCode(f),
		OtpMods.RandomPurpose(f),
		OtpMods.RandomExpiresAt(f),
		OtpMods.RandomUsedAt(f),
		OtpMods.RandomCreatedAt(f),
	}
}

// Set the model columns to this value
func (m otpMods) ID(val int64) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m otpMods) IDFunc(f func() int64) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m otpMods) UnsetID() OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m otpMods) RandomID(f *faker.Faker) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m otpMods) UserID(val int64) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.UserID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m otpMods) UserIDFunc(f func() int64) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m otpMods) UnsetUserID() OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m otpMods) RandomUserID(f *faker.Faker) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.UserID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m otpMods) Code(val string) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.Code = func() string { return val }
	})
}

// Set the Column from the function
func (m otpMods) CodeFunc(f func() string) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.Code = f
	})
}

// Clear any values for the column
func (m otpMods) UnsetCode() OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.Code = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m otpMods) RandomCode(f *faker.Faker) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.Code = func() string {
			return random_string(f, "10")
		}
	})
}

// Set the model columns to this value
func (m otpMods) Purpose(val string) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.Purpose = func() string { return val }
	})
}

// Set the Column from the function
func (m otpMods) PurposeFunc(f func() string) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.Purpose = f
	})
}

// Clear any values for the column
func (m otpMods) UnsetPurpose() OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.Purpose = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m otpMods) RandomPurpose(f *faker.Faker) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.Purpose = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m otpMods) ExpiresAt(val time.Time) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.ExpiresAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m otpMods) ExpiresAtFunc(f func() time.Time) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.ExpiresAt = f
	})
}

// Clear any values for the column
func (m otpMods) UnsetExpiresAt() OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.ExpiresAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m otpMods) RandomExpiresAt(f *faker.Faker) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.ExpiresAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m otpMods) UsedAt(val null.Val[time.Time]) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.UsedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m otpMods) UsedAtFunc(f func() null.Val[time.Time]) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.UsedAt = f
	})
}

// Clear any values for the column
func (m otpMods) UnsetUsedAt() OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.UsedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m otpMods) RandomUsedAt(f *faker.Faker) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.UsedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m otpMods) RandomUsedAtNotNull(f *faker.Faker) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.UsedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m otpMods) CreatedAt(val null.Val[time.Time]) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.CreatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m otpMods) CreatedAtFunc(f func() null.Val[time.Time]) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m otpMods) UnsetCreatedAt() OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m otpMods) RandomCreatedAt(f *faker.Faker) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m otpMods) RandomCreatedAtNotNull(f *faker.Faker) OtpMod {
	return OtpModFunc(func(_ context.Context, o *OtpTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m otpMods) WithParentsCascading() OtpMod {
	return OtpModFunc(func(ctx context.Context, o *OtpTemplate) {
		if isDone, _ := otpWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = otpWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m otpMods) WithUser(rel *UserTemplate) OtpMod {
	return OtpModFunc(func(ctx context.Context, o *OtpTemplate) {
		o.r.User = &otpRUserR{
			o: rel,
		}
	})
}

func (m otpMods) WithNewUser(mods ...UserMod) OtpMod {
	return OtpModFunc(func(ctx context.Context, o *OtpTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m otpMods) WithExistingUser(em *models.User) OtpMod {
	return OtpModFunc(func(ctx context.Context, o *OtpTemplate) {
		o.r.User = &otpRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m otpMods) WithoutUser() OtpMod {
	return OtpModFunc(func(ctx context.Context, o *OtpTemplate) {
		o.r.User = nil
	})
}
