// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/letenk/golang-authentication/bob/models"
	"github.com/stephenafamo/bob"
)

type RefreshTokenMod interface {
	Apply(context.Context, *RefreshTokenTemplate)
}

type RefreshTokenModFunc func(context.Context, *RefreshTokenTemplate)

func (f RefreshTokenModFunc) Apply(ctx context.Context, n *RefreshTokenTemplate) {
	f(ctx, n)
}

type RefreshTokenModSlice []RefreshTokenMod

func (mods RefreshTokenModSlice) Apply(ctx context.Context, n *RefreshTokenTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// RefreshTokenTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type RefreshTokenTemplate struct {
	ID              func() int64
	UserID          func() int64
	Token           func() string
	DeviceName      func() null.Val[string]
	DeviceID        func() null.Val[string]
	IPAddress       func() null.Val[string]
	UserAgent       func() null.Val[string]
	ExpiresAt       func() time.Time
	CreatedAt       func() null.Val[time.Time]
	RevokedAt       func() null.Val[time.Time]
	ReplacedByToken func() null.Val[string]

	r refreshTokenR
	f *Factory

	alreadyPersisted bool
}

type refreshTokenR struct {
	User *refreshTokenRUserR
}

type refreshTokenRUserR struct {
	o *UserTemplate
}

// Apply mods to the RefreshTokenTemplate
func (o *RefreshTokenTemplate) Apply(ctx context.Context, mods ...RefreshTokenMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.RefreshToken
// according to the relationships in the template. Nothing is inserted into the db
func (t RefreshTokenTemplate) setModelRels(o *models.RefreshToken) {
	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.RefreshTokens = append(rel.R.RefreshTokens, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.RefreshTokenSetter
// this does nothing with the relationship templates
func (o RefreshTokenTemplate) BuildSetter() *models.RefreshTokenSetter {
	m := &models.RefreshTokenSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.Token != nil {
		val := o.Token()
		m.Token = omit.From(val)
	}
	if o.DeviceName != nil {
		val := o.DeviceName()
		m.DeviceName = omitnull.FromNull(val)
	}
	if o.DeviceID != nil {
		val := o.DeviceID()
		m.DeviceID = omitnull.FromNull(val)
	}
	if o.IPAddress != nil {
		val := o.IPAddress()
		m.IPAddress = omitnull.FromNull(val)
	}
	if o.UserAgent != nil {
		val := o.UserAgent()
		m.UserAgent = omitnull.FromNull(val)
	}
	if o.ExpiresAt != nil {
		val := o.ExpiresAt()
		m.ExpiresAt = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omitnull.FromNull(val)
	}
	if o.RevokedAt != nil {
		val := o.RevokedAt()
		m.RevokedAt = omitnull.FromNull(val)
	}
	if o.ReplacedByToken != nil {
		val := o.ReplacedByToken()
		m.ReplacedByToken = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.RefreshTokenSetter
// this does nothing with the relationship templates
func (o RefreshTokenTemplate) BuildManySetter(number int) []*models.RefreshTokenSetter {
	m := make([]*models.RefreshTokenSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.RefreshToken
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use RefreshTokenTemplate.Create
func (o RefreshTokenTemplate) Build() *models.RefreshToken {
	m := &models.RefreshToken{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.Token != nil {
		m.Token = o.Token()
	}
	if o.DeviceName != nil {
		m.DeviceName = o.DeviceName()
	}
	if o.DeviceID != nil {
		m.DeviceID = o.DeviceID()
	}
	if o.IPAddress != nil {
		m.IPAddress = o.IPAddress()
	}
	if o.UserAgent != nil {
		m.UserAgent = o.UserAgent()
	}
	if o.ExpiresAt != nil {
		m.ExpiresAt = o.ExpiresAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.RevokedAt != nil {
		m.RevokedAt = o.RevokedAt()
	}
	if o.ReplacedByToken != nil {
		m.ReplacedByToken = o.ReplacedByToken()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.RefreshTokenSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use RefreshTokenTemplate.CreateMany
func (o RefreshTokenTemplate) BuildMany(number int) models.RefreshTokenSlice {
	m := make(models.RefreshTokenSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableRefreshToken(m *models.RefreshTokenSetter) {
	if !(m.UserID.IsValue()) {
		val := random_int64(nil)
		m.UserID = omit.From(val)
	}
	if !(m.Token.IsValue()) {
		val := random_string(nil, "500")
		m.Token = omit.From(val)
	}
	if !(m.ExpiresAt.IsValue()) {
		val := random_time_Time(nil)
		m.ExpiresAt = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.RefreshToken
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *RefreshTokenTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.RefreshToken) error {
	var err error

	return err
}

// Create builds a refreshToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *RefreshTokenTemplate) Create(ctx context.Context, exec bob.Executor) (*models.RefreshToken, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableRefreshToken(opt)

	if o.r.User == nil {
		RefreshTokenMods.WithNewUser().Apply(ctx, o)
	}

	var rel0 *models.User

	if o.r.User.o.alreadyPersisted {
		rel0 = o.r.User.o.Build()
	} else {
		rel0, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel0.ID)

	m, err := models.RefreshTokens.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a refreshToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *RefreshTokenTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.RefreshToken {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a refreshToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *RefreshTokenTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.RefreshToken {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple refreshTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o RefreshTokenTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.RefreshTokenSlice, error) {
	var err error
	m := make(models.RefreshTokenSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple refreshTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o RefreshTokenTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.RefreshTokenSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple refreshTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o RefreshTokenTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.RefreshTokenSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// RefreshToken has methods that act as mods for the RefreshTokenTemplate
var RefreshTokenMods refreshTokenMods

type refreshTokenMods struct{}

func (m refreshTokenMods) RandomizeAllColumns(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModSlice{
		RefreshTokenMods.RandomID(f),
		RefreshTokenMods.RandomUserID(f),
		RefreshTokenMods.RandomToken(f),
		RefreshTokenMods.RandomDeviceName(f),
		RefreshTokenMods.RandomDeviceID(f),
		RefreshTokenMods.RandomIPAddress(f),
		RefreshTokenMods.RandomUserAgent(f),
		RefreshTokenMods.RandomExpiresAt(f),
		RefreshTokenMods.RandomCreatedAt(f),
		RefreshTokenMods.RandomRevokedAt(f),
		RefreshTokenMods.RandomReplacedByToken(f),
	}
}

// Set the model columns to this value
func (m refreshTokenMods) ID(val int64) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m refreshTokenMods) IDFunc(f func() int64) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m refreshTokenMods) UnsetID() RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m refreshTokenMods) RandomID(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m refreshTokenMods) UserID(val int64) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.UserID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m refreshTokenMods) UserIDFunc(f func() int64) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m refreshTokenMods) UnsetUserID() RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m refreshTokenMods) RandomUserID(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.UserID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m refreshTokenMods) Token(val string) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.Token = func() string { return val }
	})
}

// Set the Column from the function
func (m refreshTokenMods) TokenFunc(f func() string) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.Token = f
	})
}

// Clear any values for the column
func (m refreshTokenMods) UnsetToken() RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.Token = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m refreshTokenMods) RandomToken(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.Token = func() string {
			return random_string(f, "500")
		}
	})
}

// Set the model columns to this value
func (m refreshTokenMods) DeviceName(val null.Val[string]) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.DeviceName = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m refreshTokenMods) DeviceNameFunc(f func() null.Val[string]) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.DeviceName = f
	})
}

// Clear any values for the column
func (m refreshTokenMods) UnsetDeviceName() RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.DeviceName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m refreshTokenMods) RandomDeviceName(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.DeviceName = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "100")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m refreshTokenMods) RandomDeviceNameNotNull(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.DeviceName = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "100")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m refreshTokenMods) DeviceID(val null.Val[string]) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.DeviceID = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m refreshTokenMods) DeviceIDFunc(f func() null.Val[string]) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.DeviceID = f
	})
}

// Clear any values for the column
func (m refreshTokenMods) UnsetDeviceID() RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.DeviceID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m refreshTokenMods) RandomDeviceID(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.DeviceID = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m refreshTokenMods) RandomDeviceIDNotNull(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.DeviceID = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m refreshTokenMods) IPAddress(val null.Val[string]) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.IPAddress = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m refreshTokenMods) IPAddressFunc(f func() null.Val[string]) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.IPAddress = f
	})
}

// Clear any values for the column
func (m refreshTokenMods) UnsetIPAddress() RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.IPAddress = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m refreshTokenMods) RandomIPAddress(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.IPAddress = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "45")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m refreshTokenMods) RandomIPAddressNotNull(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.IPAddress = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "45")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m refreshTokenMods) UserAgent(val null.Val[string]) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.UserAgent = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m refreshTokenMods) UserAgentFunc(f func() null.Val[string]) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.UserAgent = f
	})
}

// Clear any values for the column
func (m refreshTokenMods) UnsetUserAgent() RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.UserAgent = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m refreshTokenMods) RandomUserAgent(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.UserAgent = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m refreshTokenMods) RandomUserAgentNotNull(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.UserAgent = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m refreshTokenMods) ExpiresAt(val time.Time) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.ExpiresAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m refreshTokenMods) ExpiresAtFunc(f func() time.Time) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.ExpiresAt = f
	})
}

// Clear any values for the column
func (m refreshTokenMods) UnsetExpiresAt() RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.ExpiresAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m refreshTokenMods) RandomExpiresAt(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.ExpiresAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m refreshTokenMods) CreatedAt(val null.Val[time.Time]) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.CreatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m refreshTokenMods) CreatedAtFunc(f func() null.Val[time.Time]) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m refreshTokenMods) UnsetCreatedAt() RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m refreshTokenMods) RandomCreatedAt(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m refreshTokenMods) RandomCreatedAtNotNull(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m refreshTokenMods) RevokedAt(val null.Val[time.Time]) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.RevokedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m refreshTokenMods) RevokedAtFunc(f func() null.Val[time.Time]) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.RevokedAt = f
	})
}

// Clear any values for the column
func (m refreshTokenMods) UnsetRevokedAt() RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.RevokedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m refreshTokenMods) RandomRevokedAt(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.RevokedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m refreshTokenMods) RandomRevokedAtNotNull(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.RevokedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m refreshTokenMods) ReplacedByToken(val null.Val[string]) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.ReplacedByToken = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m refreshTokenMods) ReplacedByTokenFunc(f func() null.Val[string]) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.ReplacedByToken = f
	})
}

// Clear any values for the column
func (m refreshTokenMods) UnsetReplacedByToken() RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.ReplacedByToken = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m refreshTokenMods) RandomReplacedByToken(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.ReplacedByToken = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "500")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m refreshTokenMods) RandomReplacedByTokenNotNull(f *faker.Faker) RefreshTokenMod {
	return RefreshTokenModFunc(func(_ context.Context, o *RefreshTokenTemplate) {
		o.ReplacedByToken = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "500")
			return null.From(val)
		}
	})
}

func (m refreshTokenMods) WithParentsCascading() RefreshTokenMod {
	return RefreshTokenModFunc(func(ctx context.Context, o *RefreshTokenTemplate) {
		if isDone, _ := refreshTokenWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = refreshTokenWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m refreshTokenMods) WithUser(rel *UserTemplate) RefreshTokenMod {
	return RefreshTokenModFunc(func(ctx context.Context, o *RefreshTokenTemplate) {
		o.r.User = &refreshTokenRUserR{
			o: rel,
		}
	})
}

func (m refreshTokenMods) WithNewUser(mods ...UserMod) RefreshTokenMod {
	return RefreshTokenModFunc(func(ctx context.Context, o *RefreshTokenTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m refreshTokenMods) WithExistingUser(em *models.User) RefreshTokenMod {
	return RefreshTokenModFunc(func(ctx context.Context, o *RefreshTokenTemplate) {
		o.r.User = &refreshTokenRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m refreshTokenMods) WithoutUser() RefreshTokenMod {
	return RefreshTokenModFunc(func(ctx context.Context, o *RefreshTokenTemplate) {
		o.r.User = nil
	})
}
