// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/letenk/golang-authentication/bob/models"
	"github.com/stephenafamo/bob"
)

type UserMod interface {
	Apply(context.Context, *UserTemplate)
}

type UserModFunc func(context.Context, *UserTemplate)

func (f UserModFunc) Apply(ctx context.Context, n *UserTemplate) {
	f(ctx, n)
}

type UserModSlice []UserMod

func (mods UserModSlice) Apply(ctx context.Context, n *UserTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// UserTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type UserTemplate struct {
	ID         func() int64
	Version    func() int64
	CreatedAt  func() null.Val[time.Time]
	CreatedBy  func() int64
	UpdatedAt  func() null.Val[time.Time]
	UpdatedBy  func() int64
	DeletedAt  func() null.Val[time.Time]
	DeletedBy  func() null.Val[int64]
	Name       func() null.Val[string]
	Email      func() null.Val[string]
	Phone      func() null.Val[string]
	Password   func() string
	LoginType  func() string
	IsVerified func() null.Val[bool]
	VerifiedAt func() null.Val[time.Time]

	r userR
	f *Factory

	alreadyPersisted bool
}

type userR struct {
	Otps               []*userROtpsR
	RefreshTokens      []*userRRefreshTokensR
	CreatedBy          *userRCreatedByR
	ReverseCreatedBies []*userRReverseCreatedBiesR
	DeletedBy          *userRDeletedByR
	ReverseDeletedBies []*userRReverseDeletedBiesR
	UpdatedBy          *userRUpdatedByR
	ReverseUpdatedBies []*userRReverseUpdatedBiesR
}

type userROtpsR struct {
	number int
	o      *OtpTemplate
}
type userRRefreshTokensR struct {
	number int
	o      *RefreshTokenTemplate
}
type userRCreatedByR struct {
	o *UserTemplate
}
type userRReverseCreatedBiesR struct {
	number int
	o      *UserTemplate
}
type userRDeletedByR struct {
	o *UserTemplate
}
type userRReverseDeletedBiesR struct {
	number int
	o      *UserTemplate
}
type userRUpdatedByR struct {
	o *UserTemplate
}
type userRReverseUpdatedBiesR struct {
	number int
	o      *UserTemplate
}

// Apply mods to the UserTemplate
func (o *UserTemplate) Apply(ctx context.Context, mods ...UserMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.User
// according to the relationships in the template. Nothing is inserted into the db
func (t UserTemplate) setModelRels(o *models.User) {
	if t.r.Otps != nil {
		rel := models.OtpSlice{}
		for _, r := range t.r.Otps {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserID = o.ID // h2
				rel.R.User = o
			}
			rel = append(rel, related...)
		}
		o.R.Otps = rel
	}

	if t.r.RefreshTokens != nil {
		rel := models.RefreshTokenSlice{}
		for _, r := range t.r.RefreshTokens {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserID = o.ID // h2
				rel.R.User = o
			}
			rel = append(rel, related...)
		}
		o.R.RefreshTokens = rel
	}

	if t.r.CreatedBy != nil {
		rel := t.r.CreatedBy.o.Build()
		rel.R.ReverseCreatedBies = append(rel.R.ReverseCreatedBies, o)
		o.CreatedBy = rel.ID // h2
		o.R.CreatedBy = rel
	}

	if t.r.ReverseCreatedBies != nil {
		rel := models.UserSlice{}
		for _, r := range t.r.ReverseCreatedBies {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.CreatedBy = o.ID // h2
				rel.R.CreatedBy = o
			}
			rel = append(rel, related...)
		}
		o.R.ReverseCreatedBies = rel
	}

	if t.r.DeletedBy != nil {
		rel := t.r.DeletedBy.o.Build()
		rel.R.ReverseDeletedBies = append(rel.R.ReverseDeletedBies, o)
		o.DeletedBy = null.From(rel.ID) // h2
		o.R.DeletedBy = rel
	}

	if t.r.ReverseDeletedBies != nil {
		rel := models.UserSlice{}
		for _, r := range t.r.ReverseDeletedBies {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.DeletedBy = null.From(o.ID) // h2
				rel.R.DeletedBy = o
			}
			rel = append(rel, related...)
		}
		o.R.ReverseDeletedBies = rel
	}

	if t.r.UpdatedBy != nil {
		rel := t.r.UpdatedBy.o.Build()
		rel.R.ReverseUpdatedBies = append(rel.R.ReverseUpdatedBies, o)
		o.UpdatedBy = rel.ID // h2
		o.R.UpdatedBy = rel
	}

	if t.r.ReverseUpdatedBies != nil {
		rel := models.UserSlice{}
		for _, r := range t.r.ReverseUpdatedBies {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UpdatedBy = o.ID // h2
				rel.R.UpdatedBy = o
			}
			rel = append(rel, related...)
		}
		o.R.ReverseUpdatedBies = rel
	}
}

// BuildSetter returns an *models.UserSetter
// this does nothing with the relationship templates
func (o UserTemplate) BuildSetter() *models.UserSetter {
	m := &models.UserSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Version != nil {
		val := o.Version()
		m.Version = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omitnull.FromNull(val)
	}
	if o.CreatedBy != nil {
		val := o.CreatedBy()
		m.CreatedBy = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omitnull.FromNull(val)
	}
	if o.UpdatedBy != nil {
		val := o.UpdatedBy()
		m.UpdatedBy = omit.From(val)
	}
	if o.DeletedAt != nil {
		val := o.DeletedAt()
		m.DeletedAt = omitnull.FromNull(val)
	}
	if o.DeletedBy != nil {
		val := o.DeletedBy()
		m.DeletedBy = omitnull.FromNull(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omitnull.FromNull(val)
	}
	if o.Email != nil {
		val := o.Email()
		m.Email = omitnull.FromNull(val)
	}
	if o.Phone != nil {
		val := o.Phone()
		m.Phone = omitnull.FromNull(val)
	}
	if o.Password != nil {
		val := o.Password()
		m.Password = omit.From(val)
	}
	if o.LoginType != nil {
		val := o.LoginType()
		m.LoginType = omit.From(val)
	}
	if o.IsVerified != nil {
		val := o.IsVerified()
		m.IsVerified = omitnull.FromNull(val)
	}
	if o.VerifiedAt != nil {
		val := o.VerifiedAt()
		m.VerifiedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.UserSetter
// this does nothing with the relationship templates
func (o UserTemplate) BuildManySetter(number int) []*models.UserSetter {
	m := make([]*models.UserSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.User
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserTemplate.Create
func (o UserTemplate) Build() *models.User {
	m := &models.User{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Version != nil {
		m.Version = o.Version()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.CreatedBy != nil {
		m.CreatedBy = o.CreatedBy()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}
	if o.UpdatedBy != nil {
		m.UpdatedBy = o.UpdatedBy()
	}
	if o.DeletedAt != nil {
		m.DeletedAt = o.DeletedAt()
	}
	if o.DeletedBy != nil {
		m.DeletedBy = o.DeletedBy()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Email != nil {
		m.Email = o.Email()
	}
	if o.Phone != nil {
		m.Phone = o.Phone()
	}
	if o.Password != nil {
		m.Password = o.Password()
	}
	if o.LoginType != nil {
		m.LoginType = o.LoginType()
	}
	if o.IsVerified != nil {
		m.IsVerified = o.IsVerified()
	}
	if o.VerifiedAt != nil {
		m.VerifiedAt = o.VerifiedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.UserSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserTemplate.CreateMany
func (o UserTemplate) BuildMany(number int) models.UserSlice {
	m := make(models.UserSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableUser(m *models.UserSetter) {
	if !(m.Password.IsValue()) {
		val := random_string(nil, "255")
		m.Password = omit.From(val)
	}
	if !(m.LoginType.IsValue()) {
		val := random_string(nil, "255")
		m.LoginType = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.User
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *UserTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.User) error {
	var err error

	isOtpsDone, _ := userRelOtpsCtx.Value(ctx)
	if !isOtpsDone && o.r.Otps != nil {
		ctx = userRelOtpsCtx.WithValue(ctx, true)
		for _, r := range o.r.Otps {
			if r.o.alreadyPersisted {
				m.R.Otps = append(m.R.Otps, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOtps(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isRefreshTokensDone, _ := userRelRefreshTokensCtx.Value(ctx)
	if !isRefreshTokensDone && o.r.RefreshTokens != nil {
		ctx = userRelRefreshTokensCtx.WithValue(ctx, true)
		for _, r := range o.r.RefreshTokens {
			if r.o.alreadyPersisted {
				m.R.RefreshTokens = append(m.R.RefreshTokens, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachRefreshTokens(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isReverseCreatedBiesDone, _ := userRelReverseCreatedBiesCtx.Value(ctx)
	if !isReverseCreatedBiesDone && o.r.ReverseCreatedBies != nil {
		ctx = userRelReverseCreatedBiesCtx.WithValue(ctx, true)
		for _, r := range o.r.ReverseCreatedBies {
			if r.o.alreadyPersisted {
				m.R.ReverseCreatedBies = append(m.R.ReverseCreatedBies, r.o.Build())
			} else {
				rel3, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachReverseCreatedBies(ctx, exec, rel3...)
				if err != nil {
					return err
				}
			}
		}
	}

	isDeletedByDone, _ := userRelDeletedByCtx.Value(ctx)
	if !isDeletedByDone && o.r.DeletedBy != nil {
		ctx = userRelDeletedByCtx.WithValue(ctx, true)
		if o.r.DeletedBy.o.alreadyPersisted {
			m.R.DeletedBy = o.r.DeletedBy.o.Build()
		} else {
			var rel4 *models.User
			rel4, err = o.r.DeletedBy.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachDeletedBy(ctx, exec, rel4)
			if err != nil {
				return err
			}
		}

	}

	isReverseDeletedBiesDone, _ := userRelReverseDeletedBiesCtx.Value(ctx)
	if !isReverseDeletedBiesDone && o.r.ReverseDeletedBies != nil {
		ctx = userRelReverseDeletedBiesCtx.WithValue(ctx, true)
		for _, r := range o.r.ReverseDeletedBies {
			if r.o.alreadyPersisted {
				m.R.ReverseDeletedBies = append(m.R.ReverseDeletedBies, r.o.Build())
			} else {
				rel5, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachReverseDeletedBies(ctx, exec, rel5...)
				if err != nil {
					return err
				}
			}
		}
	}

	isReverseUpdatedBiesDone, _ := userRelReverseUpdatedBiesCtx.Value(ctx)
	if !isReverseUpdatedBiesDone && o.r.ReverseUpdatedBies != nil {
		ctx = userRelReverseUpdatedBiesCtx.WithValue(ctx, true)
		for _, r := range o.r.ReverseUpdatedBies {
			if r.o.alreadyPersisted {
				m.R.ReverseUpdatedBies = append(m.R.ReverseUpdatedBies, r.o.Build())
			} else {
				rel7, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachReverseUpdatedBies(ctx, exec, rel7...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *UserTemplate) Create(ctx context.Context, exec bob.Executor) (*models.User, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableUser(opt)

	if o.r.CreatedBy == nil {
		UserMods.WithNewCreatedBy().Apply(ctx, o)
	}

	var rel2 *models.User

	if o.r.CreatedBy.o.alreadyPersisted {
		rel2 = o.r.CreatedBy.o.Build()
	} else {
		rel2, err = o.r.CreatedBy.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.CreatedBy = omit.From(rel2.ID)

	if o.r.UpdatedBy == nil {
		UserMods.WithNewUpdatedBy().Apply(ctx, o)
	}

	var rel6 *models.User

	if o.r.UpdatedBy.o.alreadyPersisted {
		rel6 = o.r.UpdatedBy.o.Build()
	} else {
		rel6, err = o.r.UpdatedBy.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UpdatedBy = omit.From(rel6.ID)

	m, err := models.Users.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.CreatedBy = rel2
	m.R.UpdatedBy = rel6

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *UserTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.User {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *UserTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.User {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o UserTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.UserSlice, error) {
	var err error
	m := make(models.UserSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o UserTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.UserSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o UserTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.UserSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// User has methods that act as mods for the UserTemplate
var UserMods userMods

type userMods struct{}

func (m userMods) RandomizeAllColumns(f *faker.Faker) UserMod {
	return UserModSlice{
		UserMods.RandomID(f),
		UserMods.RandomVersion(f),
		UserMods.RandomCreatedAt(f),
		UserMods.RandomCreatedBy(f),
		UserMods.RandomUpdatedAt(f),
		UserMods.RandomUpdatedBy(f),
		UserMods.RandomDeletedAt(f),
		UserMods.RandomDeletedBy(f),
		UserMods.RandomName(f),
		UserMods.RandomEmail(f),
		UserMods.RandomPhone(f),
		UserMods.RandomPassword(f),
		UserMods.RandomLoginType(f),
		UserMods.RandomIsVerified(f),
		UserMods.RandomVerifiedAt(f),
	}
}

// Set the model columns to this value
func (m userMods) ID(val int64) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m userMods) IDFunc(f func() int64) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m userMods) UnsetID() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomID(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Version(val int64) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Version = func() int64 { return val }
	})
}

// Set the Column from the function
func (m userMods) VersionFunc(f func() int64) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Version = f
	})
}

// Clear any values for the column
func (m userMods) UnsetVersion() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Version = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomVersion(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Version = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) CreatedAt(val null.Val[time.Time]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m userMods) CreatedAtFunc(f func() null.Val[time.Time]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m userMods) UnsetCreatedAt() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomCreatedAt(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomCreatedAtNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) CreatedBy(val int64) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedBy = func() int64 { return val }
	})
}

// Set the Column from the function
func (m userMods) CreatedByFunc(f func() int64) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedBy = f
	})
}

// Clear any values for the column
func (m userMods) UnsetCreatedBy() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomCreatedBy(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedBy = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) UpdatedAt(val null.Val[time.Time]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m userMods) UpdatedAtFunc(f func() null.Val[time.Time]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m userMods) UnsetUpdatedAt() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomUpdatedAt(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomUpdatedAtNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) UpdatedBy(val int64) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedBy = func() int64 { return val }
	})
}

// Set the Column from the function
func (m userMods) UpdatedByFunc(f func() int64) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedBy = f
	})
}

// Clear any values for the column
func (m userMods) UnsetUpdatedBy() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomUpdatedBy(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedBy = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) DeletedAt(val null.Val[time.Time]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.DeletedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m userMods) DeletedAtFunc(f func() null.Val[time.Time]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.DeletedAt = f
	})
}

// Clear any values for the column
func (m userMods) UnsetDeletedAt() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.DeletedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomDeletedAt(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.DeletedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomDeletedAtNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.DeletedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) DeletedBy(val null.Val[int64]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.DeletedBy = func() null.Val[int64] { return val }
	})
}

// Set the Column from the function
func (m userMods) DeletedByFunc(f func() null.Val[int64]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.DeletedBy = f
	})
}

// Clear any values for the column
func (m userMods) UnsetDeletedBy() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.DeletedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomDeletedBy(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.DeletedBy = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomDeletedByNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.DeletedBy = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) Name(val null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Name = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m userMods) NameFunc(f func() null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m userMods) UnsetName() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomName(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Name = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomNameNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Name = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) Email(val null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m userMods) EmailFunc(f func() null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = f
	})
}

// Clear any values for the column
func (m userMods) UnsetEmail() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomEmail(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomEmailNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) Phone(val null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Phone = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m userMods) PhoneFunc(f func() null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Phone = f
	})
}

// Clear any values for the column
func (m userMods) UnsetPhone() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Phone = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomPhone(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Phone = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "20")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomPhoneNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Phone = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "20")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) Password(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) PasswordFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = f
	})
}

// Clear any values for the column
func (m userMods) UnsetPassword() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomPassword(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m userMods) LoginType(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LoginType = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) LoginTypeFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LoginType = f
	})
}

// Clear any values for the column
func (m userMods) UnsetLoginType() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LoginType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomLoginType(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LoginType = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m userMods) IsVerified(val null.Val[bool]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.IsVerified = func() null.Val[bool] { return val }
	})
}

// Set the Column from the function
func (m userMods) IsVerifiedFunc(f func() null.Val[bool]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.IsVerified = f
	})
}

// Clear any values for the column
func (m userMods) UnsetIsVerified() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.IsVerified = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomIsVerified(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.IsVerified = func() null.Val[bool] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_bool(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomIsVerifiedNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.IsVerified = func() null.Val[bool] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_bool(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) VerifiedAt(val null.Val[time.Time]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.VerifiedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m userMods) VerifiedAtFunc(f func() null.Val[time.Time]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.VerifiedAt = f
	})
}

// Clear any values for the column
func (m userMods) UnsetVerifiedAt() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.VerifiedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomVerifiedAt(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.VerifiedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomVerifiedAtNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.VerifiedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m userMods) WithParentsCascading() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		if isDone, _ := userWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = userWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithCreatedBy(related).Apply(ctx, o)
		}
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithDeletedBy(related).Apply(ctx, o)
		}
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUpdatedBy(related).Apply(ctx, o)
		}
	})
}

func (m userMods) WithCreatedBy(rel *UserTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.CreatedBy = &userRCreatedByR{
			o: rel,
		}
	})
}

func (m userMods) WithNewCreatedBy(mods ...UserMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithCreatedBy(related).Apply(ctx, o)
	})
}

func (m userMods) WithExistingCreatedBy(em *models.User) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.CreatedBy = &userRCreatedByR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m userMods) WithoutCreatedBy() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.CreatedBy = nil
	})
}

func (m userMods) WithDeletedBy(rel *UserTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.DeletedBy = &userRDeletedByR{
			o: rel,
		}
	})
}

func (m userMods) WithNewDeletedBy(mods ...UserMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithDeletedBy(related).Apply(ctx, o)
	})
}

func (m userMods) WithExistingDeletedBy(em *models.User) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.DeletedBy = &userRDeletedByR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m userMods) WithoutDeletedBy() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.DeletedBy = nil
	})
}

func (m userMods) WithUpdatedBy(rel *UserTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.UpdatedBy = &userRUpdatedByR{
			o: rel,
		}
	})
}

func (m userMods) WithNewUpdatedBy(mods ...UserMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUpdatedBy(related).Apply(ctx, o)
	})
}

func (m userMods) WithExistingUpdatedBy(em *models.User) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.UpdatedBy = &userRUpdatedByR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m userMods) WithoutUpdatedBy() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.UpdatedBy = nil
	})
}

func (m userMods) WithOtps(number int, related *OtpTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Otps = []*userROtpsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewOtps(number int, mods ...OtpMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewOtpWithContext(ctx, mods...)
		m.WithOtps(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddOtps(number int, related *OtpTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Otps = append(o.r.Otps, &userROtpsR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewOtps(number int, mods ...OtpMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewOtpWithContext(ctx, mods...)
		m.AddOtps(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingOtps(existingModels ...*models.Otp) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.Otps = append(o.r.Otps, &userROtpsR{
				o: o.f.FromExistingOtp(em),
			})
		}
	})
}

func (m userMods) WithoutOtps() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Otps = nil
	})
}

func (m userMods) WithRefreshTokens(number int, related *RefreshTokenTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.RefreshTokens = []*userRRefreshTokensR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewRefreshTokens(number int, mods ...RefreshTokenMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewRefreshTokenWithContext(ctx, mods...)
		m.WithRefreshTokens(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddRefreshTokens(number int, related *RefreshTokenTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.RefreshTokens = append(o.r.RefreshTokens, &userRRefreshTokensR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewRefreshTokens(number int, mods ...RefreshTokenMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewRefreshTokenWithContext(ctx, mods...)
		m.AddRefreshTokens(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingRefreshTokens(existingModels ...*models.RefreshToken) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.RefreshTokens = append(o.r.RefreshTokens, &userRRefreshTokensR{
				o: o.f.FromExistingRefreshToken(em),
			})
		}
	})
}

func (m userMods) WithoutRefreshTokens() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.RefreshTokens = nil
	})
}

func (m userMods) WithReverseCreatedBies(number int, related *UserTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ReverseCreatedBies = []*userRReverseCreatedBiesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewReverseCreatedBies(number int, mods ...UserMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)
		m.WithReverseCreatedBies(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddReverseCreatedBies(number int, related *UserTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ReverseCreatedBies = append(o.r.ReverseCreatedBies, &userRReverseCreatedBiesR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewReverseCreatedBies(number int, mods ...UserMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)
		m.AddReverseCreatedBies(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingReverseCreatedBies(existingModels ...*models.User) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.ReverseCreatedBies = append(o.r.ReverseCreatedBies, &userRReverseCreatedBiesR{
				o: o.f.FromExistingUser(em),
			})
		}
	})
}

func (m userMods) WithoutReverseCreatedBies() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ReverseCreatedBies = nil
	})
}

func (m userMods) WithReverseDeletedBies(number int, related *UserTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ReverseDeletedBies = []*userRReverseDeletedBiesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewReverseDeletedBies(number int, mods ...UserMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)
		m.WithReverseDeletedBies(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddReverseDeletedBies(number int, related *UserTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ReverseDeletedBies = append(o.r.ReverseDeletedBies, &userRReverseDeletedBiesR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewReverseDeletedBies(number int, mods ...UserMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)
		m.AddReverseDeletedBies(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingReverseDeletedBies(existingModels ...*models.User) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.ReverseDeletedBies = append(o.r.ReverseDeletedBies, &userRReverseDeletedBiesR{
				o: o.f.FromExistingUser(em),
			})
		}
	})
}

func (m userMods) WithoutReverseDeletedBies() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ReverseDeletedBies = nil
	})
}

func (m userMods) WithReverseUpdatedBies(number int, related *UserTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ReverseUpdatedBies = []*userRReverseUpdatedBiesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewReverseUpdatedBies(number int, mods ...UserMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)
		m.WithReverseUpdatedBies(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddReverseUpdatedBies(number int, related *UserTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ReverseUpdatedBies = append(o.r.ReverseUpdatedBies, &userRReverseUpdatedBiesR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewReverseUpdatedBies(number int, mods ...UserMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)
		m.AddReverseUpdatedBies(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingReverseUpdatedBies(existingModels ...*models.User) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.ReverseUpdatedBies = append(o.r.ReverseUpdatedBies, &userRReverseUpdatedBiesR{
				o: o.f.FromExistingUser(em),
			})
		}
	})
}

func (m userMods) WithoutReverseUpdatedBies() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ReverseUpdatedBies = nil
	})
}
