// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	bob "github.com/stephenafamo/bob"

	db "github.com/letenk/golang-authentication/internal/applications/otp/repository/db"
	mock "github.com/stretchr/testify/mock"

	models "github.com/letenk/golang-authentication/bob/models"
)

// MockOTPRepository is an autogenerated mock type for the OTPRepository type
type MockOTPRepository struct {
	mock.Mock
}

type MockOTPRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOTPRepository) EXPECT() *MockOTPRepository_Expecter {
	return &MockOTPRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, params
func (_m *MockOTPRepository) Create(ctx context.Context, params db.CreateOTPParams) (*models.Otp, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Otp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateOTPParams) (*models.Otp, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateOTPParams) *models.Otp); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Otp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateOTPParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOTPRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOTPRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - params db.CreateOTPParams
func (_e *MockOTPRepository_Expecter) Create(ctx interface{}, params interface{}) *MockOTPRepository_Create_Call {
	return &MockOTPRepository_Create_Call{Call: _e.mock.On("Create", ctx, params)}
}

func (_c *MockOTPRepository_Create_Call) Run(run func(ctx context.Context, params db.CreateOTPParams)) *MockOTPRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateOTPParams))
	})
	return _c
}

func (_c *MockOTPRepository_Create_Call) Return(_a0 *models.Otp, _a1 error) *MockOTPRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOTPRepository_Create_Call) RunAndReturn(run func(context.Context, db.CreateOTPParams) (*models.Otp, error)) *MockOTPRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithExec provides a mock function with given fields: ctx, exec, params
func (_m *MockOTPRepository) CreateWithExec(ctx context.Context, exec bob.Executor, params db.CreateOTPParams) (*models.Otp, error) {
	ret := _m.Called(ctx, exec, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithExec")
	}

	var r0 *models.Otp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bob.Executor, db.CreateOTPParams) (*models.Otp, error)); ok {
		return rf(ctx, exec, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bob.Executor, db.CreateOTPParams) *models.Otp); ok {
		r0 = rf(ctx, exec, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Otp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bob.Executor, db.CreateOTPParams) error); ok {
		r1 = rf(ctx, exec, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOTPRepository_CreateWithExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithExec'
type MockOTPRepository_CreateWithExec_Call struct {
	*mock.Call
}

// CreateWithExec is a helper method to define mock.On call
//   - ctx context.Context
//   - exec bob.Executor
//   - params db.CreateOTPParams
func (_e *MockOTPRepository_Expecter) CreateWithExec(ctx interface{}, exec interface{}, params interface{}) *MockOTPRepository_CreateWithExec_Call {
	return &MockOTPRepository_CreateWithExec_Call{Call: _e.mock.On("CreateWithExec", ctx, exec, params)}
}

func (_c *MockOTPRepository_CreateWithExec_Call) Run(run func(ctx context.Context, exec bob.Executor, params db.CreateOTPParams)) *MockOTPRepository_CreateWithExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bob.Executor), args[2].(db.CreateOTPParams))
	})
	return _c
}

func (_c *MockOTPRepository_CreateWithExec_Call) Return(_a0 *models.Otp, _a1 error) *MockOTPRepository_CreateWithExec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOTPRepository_CreateWithExec_Call) RunAndReturn(run func(context.Context, bob.Executor, db.CreateOTPParams) (*models.Otp, error)) *MockOTPRepository_CreateWithExec_Call {
	_c.Call.Return(run)
	return _c
}

// FindValidByUserAndCode provides a mock function with given fields: ctx, userID, purpose, code
func (_m *MockOTPRepository) FindValidByUserAndCode(ctx context.Context, userID int64, purpose db.OTPPurpose, code string) (*models.Otp, error) {
	ret := _m.Called(ctx, userID, purpose, code)

	if len(ret) == 0 {
		panic("no return value specified for FindValidByUserAndCode")
	}

	var r0 *models.Otp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, db.OTPPurpose, string) (*models.Otp, error)); ok {
		return rf(ctx, userID, purpose, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, db.OTPPurpose, string) *models.Otp); ok {
		r0 = rf(ctx, userID, purpose, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Otp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, db.OTPPurpose, string) error); ok {
		r1 = rf(ctx, userID, purpose, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOTPRepository_FindValidByUserAndCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindValidByUserAndCode'
type MockOTPRepository_FindValidByUserAndCode_Call struct {
	*mock.Call
}

// FindValidByUserAndCode is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - purpose db.OTPPurpose
//   - code string
func (_e *MockOTPRepository_Expecter) FindValidByUserAndCode(ctx interface{}, userID interface{}, purpose interface{}, code interface{}) *MockOTPRepository_FindValidByUserAndCode_Call {
	return &MockOTPRepository_FindValidByUserAndCode_Call{Call: _e.mock.On("FindValidByUserAndCode", ctx, userID, purpose, code)}
}

func (_c *MockOTPRepository_FindValidByUserAndCode_Call) Run(run func(ctx context.Context, userID int64, purpose db.OTPPurpose, code string)) *MockOTPRepository_FindValidByUserAndCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(db.OTPPurpose), args[3].(string))
	})
	return _c
}

func (_c *MockOTPRepository_FindValidByUserAndCode_Call) Return(_a0 *models.Otp, _a1 error) *MockOTPRepository_FindValidByUserAndCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOTPRepository_FindValidByUserAndCode_Call) RunAndReturn(run func(context.Context, int64, db.OTPPurpose, string) (*models.Otp, error)) *MockOTPRepository_FindValidByUserAndCode_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidatePreviousByUserIDAndPurpose provides a mock function with given fields: ctx, userID, purpose
func (_m *MockOTPRepository) InvalidatePreviousByUserIDAndPurpose(ctx context.Context, userID int64, purpose db.OTPPurpose) error {
	ret := _m.Called(ctx, userID, purpose)

	if len(ret) == 0 {
		panic("no return value specified for InvalidatePreviousByUserIDAndPurpose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, db.OTPPurpose) error); ok {
		r0 = rf(ctx, userID, purpose)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOTPRepository_InvalidatePreviousByUserIDAndPurpose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidatePreviousByUserIDAndPurpose'
type MockOTPRepository_InvalidatePreviousByUserIDAndPurpose_Call struct {
	*mock.Call
}

// InvalidatePreviousByUserIDAndPurpose is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - purpose db.OTPPurpose
func (_e *MockOTPRepository_Expecter) InvalidatePreviousByUserIDAndPurpose(ctx interface{}, userID interface{}, purpose interface{}) *MockOTPRepository_InvalidatePreviousByUserIDAndPurpose_Call {
	return &MockOTPRepository_InvalidatePreviousByUserIDAndPurpose_Call{Call: _e.mock.On("InvalidatePreviousByUserIDAndPurpose", ctx, userID, purpose)}
}

func (_c *MockOTPRepository_InvalidatePreviousByUserIDAndPurpose_Call) Run(run func(ctx context.Context, userID int64, purpose db.OTPPurpose)) *MockOTPRepository_InvalidatePreviousByUserIDAndPurpose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(db.OTPPurpose))
	})
	return _c
}

func (_c *MockOTPRepository_InvalidatePreviousByUserIDAndPurpose_Call) Return(_a0 error) *MockOTPRepository_InvalidatePreviousByUserIDAndPurpose_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPRepository_InvalidatePreviousByUserIDAndPurpose_Call) RunAndReturn(run func(context.Context, int64, db.OTPPurpose) error) *MockOTPRepository_InvalidatePreviousByUserIDAndPurpose_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidatePreviousByUserIDAndPurposeWithExec provides a mock function with given fields: ctx, exec, userID, purpose
func (_m *MockOTPRepository) InvalidatePreviousByUserIDAndPurposeWithExec(ctx context.Context, exec bob.Executor, userID int64, purpose db.OTPPurpose) error {
	ret := _m.Called(ctx, exec, userID, purpose)

	if len(ret) == 0 {
		panic("no return value specified for InvalidatePreviousByUserIDAndPurposeWithExec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bob.Executor, int64, db.OTPPurpose) error); ok {
		r0 = rf(ctx, exec, userID, purpose)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOTPRepository_InvalidatePreviousByUserIDAndPurposeWithExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidatePreviousByUserIDAndPurposeWithExec'
type MockOTPRepository_InvalidatePreviousByUserIDAndPurposeWithExec_Call struct {
	*mock.Call
}

// InvalidatePreviousByUserIDAndPurposeWithExec is a helper method to define mock.On call
//   - ctx context.Context
//   - exec bob.Executor
//   - userID int64
//   - purpose db.OTPPurpose
func (_e *MockOTPRepository_Expecter) InvalidatePreviousByUserIDAndPurposeWithExec(ctx interface{}, exec interface{}, userID interface{}, purpose interface{}) *MockOTPRepository_InvalidatePreviousByUserIDAndPurposeWithExec_Call {
	return &MockOTPRepository_InvalidatePreviousByUserIDAndPurposeWithExec_Call{Call: _e.mock.On("InvalidatePreviousByUserIDAndPurposeWithExec", ctx, exec, userID, purpose)}
}

func (_c *MockOTPRepository_InvalidatePreviousByUserIDAndPurposeWithExec_Call) Run(run func(ctx context.Context, exec bob.Executor, userID int64, purpose db.OTPPurpose)) *MockOTPRepository_InvalidatePreviousByUserIDAndPurposeWithExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bob.Executor), args[2].(int64), args[3].(db.OTPPurpose))
	})
	return _c
}

func (_c *MockOTPRepository_InvalidatePreviousByUserIDAndPurposeWithExec_Call) Return(_a0 error) *MockOTPRepository_InvalidatePreviousByUserIDAndPurposeWithExec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPRepository_InvalidatePreviousByUserIDAndPurposeWithExec_Call) RunAndReturn(run func(context.Context, bob.Executor, int64, db.OTPPurpose) error) *MockOTPRepository_InvalidatePreviousByUserIDAndPurposeWithExec_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function with given fields: ctx, id
func (_m *MockOTPRepository) MarkUsed(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOTPRepository_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type MockOTPRepository_MarkUsed_Call struct {
	*mock.Call
}

// MarkUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockOTPRepository_Expecter) MarkUsed(ctx interface{}, id interface{}) *MockOTPRepository_MarkUsed_Call {
	return &MockOTPRepository_MarkUsed_Call{Call: _e.mock.On("MarkUsed", ctx, id)}
}

func (_c *MockOTPRepository_MarkUsed_Call) Run(run func(ctx context.Context, id int64)) *MockOTPRepository_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockOTPRepository_MarkUsed_Call) Return(_a0 error) *MockOTPRepository_MarkUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPRepository_MarkUsed_Call) RunAndReturn(run func(context.Context, int64) error) *MockOTPRepository_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsedWithExec provides a mock function with given fields: ctx, exec, id
func (_m *MockOTPRepository) MarkUsedWithExec(ctx context.Context, exec bob.Executor, id int64) error {
	ret := _m.Called(ctx, exec, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsedWithExec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bob.Executor, int64) error); ok {
		r0 = rf(ctx, exec, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOTPRepository_MarkUsedWithExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsedWithExec'
type MockOTPRepository_MarkUsedWithExec_Call struct {
	*mock.Call
}

// MarkUsedWithExec is a helper method to define mock.On call
//   - ctx context.Context
//   - exec bob.Executor
//   - id int64
func (_e *MockOTPRepository_Expecter) MarkUsedWithExec(ctx interface{}, exec interface{}, id interface{}) *MockOTPRepository_MarkUsedWithExec_Call {
	return &MockOTPRepository_MarkUsedWithExec_Call{Call: _e.mock.On("MarkUsedWithExec", ctx, exec, id)}
}

func (_c *MockOTPRepository_MarkUsedWithExec_Call) Run(run func(ctx context.Context, exec bob.Executor, id int64)) *MockOTPRepository_MarkUsedWithExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bob.Executor), args[2].(int64))
	})
	return _c
}

func (_c *MockOTPRepository_MarkUsedWithExec_Call) Return(_a0 error) *MockOTPRepository_MarkUsedWithExec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPRepository_MarkUsedWithExec_Call) RunAndReturn(run func(context.Context, bob.Executor, int64) error) *MockOTPRepository_MarkUsedWithExec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOTPRepository creates a new instance of MockOTPRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOTPRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOTPRepository {
	mock := &MockOTPRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
