// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var EmailVerificationOtps = Table[
	emailVerificationOtpColumns,
	emailVerificationOtpIndexes,
	emailVerificationOtpForeignKeys,
	emailVerificationOtpUniques,
	emailVerificationOtpChecks,
]{
	Schema: "",
	Name:   "email_verification_otps",
	Columns: emailVerificationOtpColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "nextval('email_verification_otps_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Code: column{
			Name:      "code",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ExpiresAt: column{
			Name:      "expires_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UsedAt: column{
			Name:      "used_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: emailVerificationOtpIndexes{
		EmailVerificationOtpsPkey: index{
			Type: "btree",
			Name: "email_verification_otps_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxEmailVerificationOtpsExpiresAt: index{
			Type: "btree",
			Name: "idx_email_verification_otps_expires_at",
			Columns: []indexColumn{
				{
					Name:         "expires_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxEmailVerificationOtpsUserID: index{
			Type: "btree",
			Name: "idx_email_verification_otps_user_id",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "email_verification_otps_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: emailVerificationOtpForeignKeys{
		EmailVerificationOtpsEmailVerificationOtpsUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "email_verification_otps.email_verification_otps_user_id_fkey",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type emailVerificationOtpColumns struct {
	ID        column
	UserID    column
	Code      column
	ExpiresAt column
	UsedAt    column
	CreatedAt column
}

func (c emailVerificationOtpColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.Code, c.ExpiresAt, c.UsedAt, c.CreatedAt,
	}
}

type emailVerificationOtpIndexes struct {
	EmailVerificationOtpsPkey         index
	IdxEmailVerificationOtpsExpiresAt index
	IdxEmailVerificationOtpsUserID    index
}

func (i emailVerificationOtpIndexes) AsSlice() []index {
	return []index{
		i.EmailVerificationOtpsPkey, i.IdxEmailVerificationOtpsExpiresAt, i.IdxEmailVerificationOtpsUserID,
	}
}

type emailVerificationOtpForeignKeys struct {
	EmailVerificationOtpsEmailVerificationOtpsUserIDFkey foreignKey
}

func (f emailVerificationOtpForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.EmailVerificationOtpsEmailVerificationOtpsUserIDFkey,
	}
}

type emailVerificationOtpUniques struct{}

func (u emailVerificationOtpUniques) AsSlice() []constraint {
	return []constraint{}
}

type emailVerificationOtpChecks struct{}

func (c emailVerificationOtpChecks) AsSlice() []check {
	return []check{}
}
