// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Otps = Table[
	otpColumns,
	otpIndexes,
	otpForeignKeys,
	otpUniques,
	otpChecks,
]{
	Schema: "",
	Name:   "otps",
	Columns: otpColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "nextval('otps_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Code: column{
			Name:      "code",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Purpose: column{
			Name:      "purpose",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ExpiresAt: column{
			Name:      "expires_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UsedAt: column{
			Name:      "used_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: otpIndexes{
		OtpsPkey: index{
			Type: "btree",
			Name: "otps_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxOtpsExpiresAt: index{
			Type: "btree",
			Name: "idx_otps_expires_at",
			Columns: []indexColumn{
				{
					Name:         "expires_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxOtpsUserPurpose: index{
			Type: "btree",
			Name: "idx_otps_user_purpose",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "purpose",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "otps_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: otpForeignKeys{
		OtpsOtpsUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "otps.otps_user_id_fkey",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type otpColumns struct {
	ID        column
	UserID    column
	Code      column
	Purpose   column
	ExpiresAt column
	UsedAt    column
	CreatedAt column
}

func (c otpColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.Code, c.Purpose, c.ExpiresAt, c.UsedAt, c.CreatedAt,
	}
}

type otpIndexes struct {
	OtpsPkey           index
	IdxOtpsExpiresAt   index
	IdxOtpsUserPurpose index
}

func (i otpIndexes) AsSlice() []index {
	return []index{
		i.OtpsPkey, i.IdxOtpsExpiresAt, i.IdxOtpsUserPurpose,
	}
}

type otpForeignKeys struct {
	OtpsOtpsUserIDFkey foreignKey
}

func (f otpForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.OtpsOtpsUserIDFkey,
	}
}

type otpUniques struct{}

func (u otpUniques) AsSlice() []constraint {
	return []constraint{}
}

type otpChecks struct{}

func (c otpChecks) AsSlice() []check {
	return []check{}
}
