// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var PasswordResetOtps = Table[
	passwordResetOtpColumns,
	passwordResetOtpIndexes,
	passwordResetOtpForeignKeys,
	passwordResetOtpUniques,
	passwordResetOtpChecks,
]{
	Schema: "",
	Name:   "password_reset_otps",
	Columns: passwordResetOtpColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "nextval('password_reset_otps_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Code: column{
			Name:      "code",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ExpiresAt: column{
			Name:      "expires_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UsedAt: column{
			Name:      "used_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: passwordResetOtpIndexes{
		PasswordResetOtpsPkey: index{
			Type: "btree",
			Name: "password_reset_otps_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxPasswordResetOtpsExpiresAt: index{
			Type: "btree",
			Name: "idx_password_reset_otps_expires_at",
			Columns: []indexColumn{
				{
					Name:         "expires_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxPasswordResetOtpsUserID: index{
			Type: "btree",
			Name: "idx_password_reset_otps_user_id",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "password_reset_otps_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: passwordResetOtpForeignKeys{
		PasswordResetOtpsPasswordResetOtpsUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "password_reset_otps.password_reset_otps_user_id_fkey",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type passwordResetOtpColumns struct {
	ID        column
	UserID    column
	Code      column
	ExpiresAt column
	UsedAt    column
	CreatedAt column
}

func (c passwordResetOtpColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.Code, c.ExpiresAt, c.UsedAt, c.CreatedAt,
	}
}

type passwordResetOtpIndexes struct {
	PasswordResetOtpsPkey         index
	IdxPasswordResetOtpsExpiresAt index
	IdxPasswordResetOtpsUserID    index
}

func (i passwordResetOtpIndexes) AsSlice() []index {
	return []index{
		i.PasswordResetOtpsPkey, i.IdxPasswordResetOtpsExpiresAt, i.IdxPasswordResetOtpsUserID,
	}
}

type passwordResetOtpForeignKeys struct {
	PasswordResetOtpsPasswordResetOtpsUserIDFkey foreignKey
}

func (f passwordResetOtpForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.PasswordResetOtpsPasswordResetOtpsUserIDFkey,
	}
}

type passwordResetOtpUniques struct{}

func (u passwordResetOtpUniques) AsSlice() []constraint {
	return []constraint{}
}

type passwordResetOtpChecks struct{}

func (c passwordResetOtpChecks) AsSlice() []check {
	return []check{}
}
