// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var RefreshTokens = Table[
	refreshTokenColumns,
	refreshTokenIndexes,
	refreshTokenForeignKeys,
	refreshTokenUniques,
	refreshTokenChecks,
]{
	Schema: "",
	Name:   "refresh_tokens",
	Columns: refreshTokenColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "nextval('refresh_tokens_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Token: column{
			Name:      "token",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DeviceName: column{
			Name:      "device_name",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		DeviceID: column{
			Name:      "device_id",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		IPAddress: column{
			Name:      "ip_address",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UserAgent: column{
			Name:      "user_agent",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ExpiresAt: column{
			Name:      "expires_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		RevokedAt: column{
			Name:      "revoked_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ReplacedByToken: column{
			Name:      "replaced_by_token",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: refreshTokenIndexes{
		RefreshTokensPkey: index{
			Type: "btree",
			Name: "refresh_tokens_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxRefreshTokensExpiresAt: index{
			Type: "btree",
			Name: "idx_refresh_tokens_expires_at",
			Columns: []indexColumn{
				{
					Name:         "expires_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxRefreshTokensToken: index{
			Type: "btree",
			Name: "idx_refresh_tokens_token",
			Columns: []indexColumn{
				{
					Name:         "token",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxRefreshTokensUserID: index{
			Type: "btree",
			Name: "idx_refresh_tokens_user_id",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		RefreshTokensTokenKey: index{
			Type: "btree",
			Name: "refresh_tokens_token_key",
			Columns: []indexColumn{
				{
					Name:         "token",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "refresh_tokens_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: refreshTokenForeignKeys{
		RefreshTokensRefreshTokensUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "refresh_tokens.refresh_tokens_user_id_fkey",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: refreshTokenUniques{
		RefreshTokensTokenKey: constraint{
			Name:    "refresh_tokens_token_key",
			Columns: []string{"token"},
			Comment: "",
		},
	},

	Comment: "",
}

type refreshTokenColumns struct {
	ID              column
	UserID          column
	Token           column
	DeviceName      column
	DeviceID        column
	IPAddress       column
	UserAgent       column
	ExpiresAt       column
	CreatedAt       column
	RevokedAt       column
	ReplacedByToken column
}

func (c refreshTokenColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.Token, c.DeviceName, c.DeviceID, c.IPAddress, c.UserAgent, c.ExpiresAt, c.CreatedAt, c.RevokedAt, c.ReplacedByToken,
	}
}

type refreshTokenIndexes struct {
	RefreshTokensPkey         index
	IdxRefreshTokensExpiresAt index
	IdxRefreshTokensToken     index
	IdxRefreshTokensUserID    index
	RefreshTokensTokenKey     index
}

func (i refreshTokenIndexes) AsSlice() []index {
	return []index{
		i.RefreshTokensPkey, i.IdxRefreshTokensExpiresAt, i.IdxRefreshTokensToken, i.IdxRefreshTokensUserID, i.RefreshTokensTokenKey,
	}
}

type refreshTokenForeignKeys struct {
	RefreshTokensRefreshTokensUserIDFkey foreignKey
}

func (f refreshTokenForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.RefreshTokensRefreshTokensUserIDFkey,
	}
}

type refreshTokenUniques struct {
	RefreshTokensTokenKey constraint
}

func (u refreshTokenUniques) AsSlice() []constraint {
	return []constraint{
		u.RefreshTokensTokenKey,
	}
}

type refreshTokenChecks struct{}

func (c refreshTokenChecks) AsSlice() []check {
	return []check{}
}
