// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Users = Table[
	userColumns,
	userIndexes,
	userForeignKeys,
	userUniques,
	userChecks,
]{
	Schema: "",
	Name:   "users",
	Columns: userColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "nextval('users_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Version: column{
			Name:      "version",
			DBType:    "bigint",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedBy: column{
			Name:      "created_by",
			DBType:    "bigint",
			Default:   "nextval('users_created_by_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedBy: column{
			Name:      "updated_by",
			DBType:    "bigint",
			Default:   "nextval('users_updated_by_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DeletedAt: column{
			Name:      "deleted_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		DeletedBy: column{
			Name:      "deleted_by",
			DBType:    "bigint",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Email: column{
			Name:      "email",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Phone: column{
			Name:      "phone",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Password: column{
			Name:      "password",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		LoginType: column{
			Name:      "login_type",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsVerified: column{
			Name:      "is_verified",
			DBType:    "boolean",
			Default:   "false",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		VerifiedAt: column{
			Name:      "verified_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: userIndexes{
		UsersPkey: index{
			Type: "btree",
			Name: "users_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UsersEmailIndex: index{
			Type: "btree",
			Name: "users_email_index",
			Columns: []indexColumn{
				{
					Name:         "email",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UsersEmailKey: index{
			Type: "btree",
			Name: "users_email_key",
			Columns: []indexColumn{
				{
					Name:         "email",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UsersPhoneIndex: index{
			Type: "btree",
			Name: "users_phone_index",
			Columns: []indexColumn{
				{
					Name:         "phone",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UsersPhoneKey: index{
			Type: "btree",
			Name: "users_phone_key",
			Columns: []indexColumn{
				{
					Name:         "phone",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "users_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: userForeignKeys{
		UsersFKUsersCreatedBy: foreignKey{
			constraint: constraint{
				Name:    "users.fk_users_created_by",
				Columns: []string{"created_by"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
		UsersFKUsersDeletedBy: foreignKey{
			constraint: constraint{
				Name:    "users.fk_users_deleted_by",
				Columns: []string{"deleted_by"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
		UsersFKUsersUpdatedBy: foreignKey{
			constraint: constraint{
				Name:    "users.fk_users_updated_by",
				Columns: []string{"updated_by"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: userUniques{
		UsersEmailKey: constraint{
			Name:    "users_email_key",
			Columns: []string{"email"},
			Comment: "",
		},
		UsersPhoneKey: constraint{
			Name:    "users_phone_key",
			Columns: []string{"phone"},
			Comment: "",
		},
	},

	Comment: "",
}

type userColumns struct {
	ID         column
	Version    column
	CreatedAt  column
	CreatedBy  column
	UpdatedAt  column
	UpdatedBy  column
	DeletedAt  column
	DeletedBy  column
	Name       column
	Email      column
	Phone      column
	Password   column
	LoginType  column
	IsVerified column
	VerifiedAt column
}

func (c userColumns) AsSlice() []column {
	return []column{
		c.ID, c.Version, c.CreatedAt, c.CreatedBy, c.UpdatedAt, c.UpdatedBy, c.DeletedAt, c.DeletedBy, c.Name, c.Email, c.Phone, c.Password, c.LoginType, c.IsVerified, c.VerifiedAt,
	}
}

type userIndexes struct {
	UsersPkey       index
	UsersEmailIndex index
	UsersEmailKey   index
	UsersPhoneIndex index
	UsersPhoneKey   index
}

func (i userIndexes) AsSlice() []index {
	return []index{
		i.UsersPkey, i.UsersEmailIndex, i.UsersEmailKey, i.UsersPhoneIndex, i.UsersPhoneKey,
	}
}

type userForeignKeys struct {
	UsersFKUsersCreatedBy foreignKey
	UsersFKUsersDeletedBy foreignKey
	UsersFKUsersUpdatedBy foreignKey
}

func (f userForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.UsersFKUsersCreatedBy, f.UsersFKUsersDeletedBy, f.UsersFKUsersUpdatedBy,
	}
}

type userUniques struct {
	UsersEmailKey constraint
	UsersPhoneKey constraint
}

func (u userUniques) AsSlice() []constraint {
	return []constraint{
		u.UsersEmailKey, u.UsersPhoneKey,
	}
}

type userChecks struct{}

func (c userChecks) AsSlice() []check {
	return []check{}
}
