// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"testing"
)

// Test that User has a C field with count pointers for to-many relationships
func TestUserCountStruct(t *testing.T) {
	var m User
	_ = m.C // Verify C field exists

	// Verify Otps count field exists and is *int64
	var _ *int64 = m.C.Otps

	// Verify RefreshTokens count field exists and is *int64
	var _ *int64 = m.C.RefreshTokens

	// Verify ReverseCreatedBies count field exists and is *int64
	var _ *int64 = m.C.ReverseCreatedBies

	// Verify ReverseDeletedBies count field exists and is *int64
	var _ *int64 = m.C.ReverseDeletedBies

	// Verify ReverseUpdatedBies count field exists and is *int64
	var _ *int64 = m.C.ReverseUpdatedBies
}

// Test that User has LoadCount methods for to-many relationships
func TestUserLoadCountMethods(t *testing.T) {
	var m *User
	var ms UserSlice
	ctx := context.Background()

	// Verify LoadCountOtps method exists on single model
	_ = m.LoadCountOtps(ctx, nil)

	// Verify LoadCountOtps method exists on slice
	_ = ms.LoadCountOtps(ctx, nil)

	// Verify LoadCountRefreshTokens method exists on single model
	_ = m.LoadCountRefreshTokens(ctx, nil)

	// Verify LoadCountRefreshTokens method exists on slice
	_ = ms.LoadCountRefreshTokens(ctx, nil)

	// Verify LoadCountReverseCreatedBies method exists on single model
	_ = m.LoadCountReverseCreatedBies(ctx, nil)

	// Verify LoadCountReverseCreatedBies method exists on slice
	_ = ms.LoadCountReverseCreatedBies(ctx, nil)

	// Verify LoadCountReverseDeletedBies method exists on single model
	_ = m.LoadCountReverseDeletedBies(ctx, nil)

	// Verify LoadCountReverseDeletedBies method exists on slice
	_ = ms.LoadCountReverseDeletedBies(ctx, nil)

	// Verify LoadCountReverseUpdatedBies method exists on single model
	_ = m.LoadCountReverseUpdatedBies(ctx, nil)

	// Verify LoadCountReverseUpdatedBies method exists on slice
	_ = ms.LoadCountReverseUpdatedBies(ctx, nil)
}

// Test that ThenLoadCount has User with methods for to-many relationships
func TestThenLoadCountUser(t *testing.T) {
	_ = ThenLoadCount.User

	// Verify Otps loader exists
	_ = ThenLoadCount.User.Otps

	// Verify RefreshTokens loader exists
	_ = ThenLoadCount.User.RefreshTokens

	// Verify ReverseCreatedBies loader exists
	_ = ThenLoadCount.User.ReverseCreatedBies

	// Verify ReverseDeletedBies loader exists
	_ = ThenLoadCount.User.ReverseDeletedBies

	// Verify ReverseUpdatedBies loader exists
	_ = ThenLoadCount.User.ReverseUpdatedBies
}

// Test that PreloadCount has User with methods for to-many relationships
func TestPreloadCountUser(t *testing.T) {
	_ = PreloadCount.User

	// Verify Otps preloader exists and returns a Preloader
	_ = PreloadCount.User.Otps()

	// Verify RefreshTokens preloader exists and returns a Preloader
	_ = PreloadCount.User.RefreshTokens()

	// Verify ReverseCreatedBies preloader exists and returns a Preloader
	_ = PreloadCount.User.ReverseCreatedBies()

	// Verify ReverseDeletedBies preloader exists and returns a Preloader
	_ = PreloadCount.User.ReverseDeletedBies()

	// Verify ReverseUpdatedBies preloader exists and returns a Preloader
	_ = PreloadCount.User.ReverseUpdatedBies()
}

// Test that User has PreloadCount method
func TestUserPreloadCountMethod(t *testing.T) {
	var m *User

	_ = m.PreloadCount("Otps", 0)

	_ = m.PreloadCount("RefreshTokens", 0)

	_ = m.PreloadCount("ReverseCreatedBies", 0)

	_ = m.PreloadCount("ReverseDeletedBies", 0)

	_ = m.PreloadCount("ReverseUpdatedBies", 0)
}
