// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// EmailVerificationOtp is an object representing the database table.
type EmailVerificationOtp struct {
	ID        int64               `db:"id,pk" `
	UserID    int64               `db:"user_id" `
	Code      string              `db:"code" `
	ExpiresAt time.Time           `db:"expires_at" `
	UsedAt    null.Val[time.Time] `db:"used_at" `
	CreatedAt null.Val[time.Time] `db:"created_at" `

	R emailVerificationOtpR `db:"-" `
}

// EmailVerificationOtpSlice is an alias for a slice of pointers to EmailVerificationOtp.
// This should almost always be used instead of []*EmailVerificationOtp.
type EmailVerificationOtpSlice []*EmailVerificationOtp

// EmailVerificationOtps contains methods to work with the email_verification_otps table
var EmailVerificationOtps = psql.NewTablex[*EmailVerificationOtp, EmailVerificationOtpSlice, *EmailVerificationOtpSetter]("", "email_verification_otps", buildEmailVerificationOtpColumns("email_verification_otps"))

// EmailVerificationOtpsQuery is a query on the email_verification_otps table
type EmailVerificationOtpsQuery = *psql.ViewQuery[*EmailVerificationOtp, EmailVerificationOtpSlice]

// emailVerificationOtpR is where relationships are stored.
type emailVerificationOtpR struct {
	User *User // email_verification_otps.email_verification_otps_user_id_fkey
}

func buildEmailVerificationOtpColumns(alias string) emailVerificationOtpColumns {
	return emailVerificationOtpColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "code", "expires_at", "used_at", "created_at",
		).WithParent("email_verification_otps"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		UserID:     psql.Quote(alias, "user_id"),
		Code:       psql.Quote(alias, "code"),
		ExpiresAt:  psql.Quote(alias, "expires_at"),
		UsedAt:     psql.Quote(alias, "used_at"),
		CreatedAt:  psql.Quote(alias, "created_at"),
	}
}

type emailVerificationOtpColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	UserID     psql.Expression
	Code       psql.Expression
	ExpiresAt  psql.Expression
	UsedAt     psql.Expression
	CreatedAt  psql.Expression
}

func (c emailVerificationOtpColumns) Alias() string {
	return c.tableAlias
}

func (emailVerificationOtpColumns) AliasedAs(alias string) emailVerificationOtpColumns {
	return buildEmailVerificationOtpColumns(alias)
}

// EmailVerificationOtpSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type EmailVerificationOtpSetter struct {
	ID        omit.Val[int64]         `db:"id,pk" `
	UserID    omit.Val[int64]         `db:"user_id" `
	Code      omit.Val[string]        `db:"code" `
	ExpiresAt omit.Val[time.Time]     `db:"expires_at" `
	UsedAt    omitnull.Val[time.Time] `db:"used_at" `
	CreatedAt omitnull.Val[time.Time] `db:"created_at" `
}

func (s EmailVerificationOtpSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Code.IsValue() {
		vals = append(vals, "code")
	}
	if s.ExpiresAt.IsValue() {
		vals = append(vals, "expires_at")
	}
	if !s.UsedAt.IsUnset() {
		vals = append(vals, "used_at")
	}
	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s EmailVerificationOtpSetter) Overwrite(t *EmailVerificationOtp) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Code.IsValue() {
		t.Code = s.Code.MustGet()
	}
	if s.ExpiresAt.IsValue() {
		t.ExpiresAt = s.ExpiresAt.MustGet()
	}
	if !s.UsedAt.IsUnset() {
		t.UsedAt = s.UsedAt.MustGetNull()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt = s.CreatedAt.MustGetNull()
	}
}

func (s *EmailVerificationOtpSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return EmailVerificationOtps.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Code.IsValue() {
			vals[2] = psql.Arg(s.Code.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.ExpiresAt.IsValue() {
			vals[3] = psql.Arg(s.ExpiresAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.UsedAt.IsUnset() {
			vals[4] = psql.Arg(s.UsedAt.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.CreatedAt.IsUnset() {
			vals[5] = psql.Arg(s.CreatedAt.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s EmailVerificationOtpSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s EmailVerificationOtpSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Code.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "code")...),
			psql.Arg(s.Code),
		}})
	}

	if s.ExpiresAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "expires_at")...),
			psql.Arg(s.ExpiresAt),
		}})
	}

	if !s.UsedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "used_at")...),
			psql.Arg(s.UsedAt),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindEmailVerificationOtp retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindEmailVerificationOtp(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*EmailVerificationOtp, error) {
	if len(cols) == 0 {
		return EmailVerificationOtps.Query(
			sm.Where(EmailVerificationOtps.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return EmailVerificationOtps.Query(
		sm.Where(EmailVerificationOtps.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(EmailVerificationOtps.Columns.Only(cols...)),
	).One(ctx, exec)
}

// EmailVerificationOtpExists checks the presence of a single record by primary key
func EmailVerificationOtpExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return EmailVerificationOtps.Query(
		sm.Where(EmailVerificationOtps.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after EmailVerificationOtp is retrieved from the database
func (o *EmailVerificationOtp) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = EmailVerificationOtps.AfterSelectHooks.RunHooks(ctx, exec, EmailVerificationOtpSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = EmailVerificationOtps.AfterInsertHooks.RunHooks(ctx, exec, EmailVerificationOtpSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = EmailVerificationOtps.AfterUpdateHooks.RunHooks(ctx, exec, EmailVerificationOtpSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = EmailVerificationOtps.AfterDeleteHooks.RunHooks(ctx, exec, EmailVerificationOtpSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the EmailVerificationOtp
func (o *EmailVerificationOtp) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *EmailVerificationOtp) pkEQ() dialect.Expression {
	return psql.Quote("email_verification_otps", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the EmailVerificationOtp
func (o *EmailVerificationOtp) Update(ctx context.Context, exec bob.Executor, s *EmailVerificationOtpSetter) error {
	v, err := EmailVerificationOtps.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single EmailVerificationOtp record with an executor
func (o *EmailVerificationOtp) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := EmailVerificationOtps.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the EmailVerificationOtp using the executor
func (o *EmailVerificationOtp) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := EmailVerificationOtps.Query(
		sm.Where(EmailVerificationOtps.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after EmailVerificationOtpSlice is retrieved from the database
func (o EmailVerificationOtpSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = EmailVerificationOtps.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = EmailVerificationOtps.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = EmailVerificationOtps.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = EmailVerificationOtps.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o EmailVerificationOtpSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("email_verification_otps", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o EmailVerificationOtpSlice) copyMatchingRows(from ...*EmailVerificationOtp) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o EmailVerificationOtpSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return EmailVerificationOtps.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *EmailVerificationOtp:
				o.copyMatchingRows(retrieved)
			case []*EmailVerificationOtp:
				o.copyMatchingRows(retrieved...)
			case EmailVerificationOtpSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a EmailVerificationOtp or a slice of EmailVerificationOtp
				// then run the AfterUpdateHooks on the slice
				_, err = EmailVerificationOtps.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o EmailVerificationOtpSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return EmailVerificationOtps.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *EmailVerificationOtp:
				o.copyMatchingRows(retrieved)
			case []*EmailVerificationOtp:
				o.copyMatchingRows(retrieved...)
			case EmailVerificationOtpSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a EmailVerificationOtp or a slice of EmailVerificationOtp
				// then run the AfterDeleteHooks on the slice
				_, err = EmailVerificationOtps.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o EmailVerificationOtpSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals EmailVerificationOtpSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := EmailVerificationOtps.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o EmailVerificationOtpSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := EmailVerificationOtps.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o EmailVerificationOtpSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := EmailVerificationOtps.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *EmailVerificationOtp) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os EmailVerificationOtpSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachEmailVerificationOtpUser0(ctx context.Context, exec bob.Executor, count int, emailVerificationOtp0 *EmailVerificationOtp, user1 *User) (*EmailVerificationOtp, error) {
	setter := &EmailVerificationOtpSetter{
		UserID: omit.From(user1.ID),
	}

	err := emailVerificationOtp0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachEmailVerificationOtpUser0: %w", err)
	}

	return emailVerificationOtp0, nil
}

func (emailVerificationOtp0 *EmailVerificationOtp) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachEmailVerificationOtpUser0(ctx, exec, 1, emailVerificationOtp0, user1)
	if err != nil {
		return err
	}

	emailVerificationOtp0.R.User = user1

	user1.R.EmailVerificationOtps = append(user1.R.EmailVerificationOtps, emailVerificationOtp0)

	return nil
}

func (emailVerificationOtp0 *EmailVerificationOtp) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachEmailVerificationOtpUser0(ctx, exec, 1, emailVerificationOtp0, user1)
	if err != nil {
		return err
	}

	emailVerificationOtp0.R.User = user1

	user1.R.EmailVerificationOtps = append(user1.R.EmailVerificationOtps, emailVerificationOtp0)

	return nil
}

type emailVerificationOtpWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, int64]
	UserID    psql.WhereMod[Q, int64]
	Code      psql.WhereMod[Q, string]
	ExpiresAt psql.WhereMod[Q, time.Time]
	UsedAt    psql.WhereNullMod[Q, time.Time]
	CreatedAt psql.WhereNullMod[Q, time.Time]
}

func (emailVerificationOtpWhere[Q]) AliasedAs(alias string) emailVerificationOtpWhere[Q] {
	return buildEmailVerificationOtpWhere[Q](buildEmailVerificationOtpColumns(alias))
}

func buildEmailVerificationOtpWhere[Q psql.Filterable](cols emailVerificationOtpColumns) emailVerificationOtpWhere[Q] {
	return emailVerificationOtpWhere[Q]{
		ID:        psql.Where[Q, int64](cols.ID),
		UserID:    psql.Where[Q, int64](cols.UserID),
		Code:      psql.Where[Q, string](cols.Code),
		ExpiresAt: psql.Where[Q, time.Time](cols.ExpiresAt),
		UsedAt:    psql.WhereNull[Q, time.Time](cols.UsedAt),
		CreatedAt: psql.WhereNull[Q, time.Time](cols.CreatedAt),
	}
}

func (o *EmailVerificationOtp) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("emailVerificationOtp cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.EmailVerificationOtps = EmailVerificationOtpSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("emailVerificationOtp has no relationship %q", name)
	}
}

type emailVerificationOtpPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildEmailVerificationOtpPreloader() emailVerificationOtpPreloader {
	return emailVerificationOtpPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        EmailVerificationOtps,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type emailVerificationOtpThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildEmailVerificationOtpThenLoader[Q orm.Loadable]() emailVerificationOtpThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return emailVerificationOtpThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the emailVerificationOtp's User into the .R struct
func (o *EmailVerificationOtp) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.EmailVerificationOtps = EmailVerificationOtpSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the emailVerificationOtp's User into the .R struct
func (os EmailVerificationOtpSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.EmailVerificationOtps = append(rel.R.EmailVerificationOtps, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type emailVerificationOtpJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j emailVerificationOtpJoins[Q]) aliasedAs(alias string) emailVerificationOtpJoins[Q] {
	return buildEmailVerificationOtpJoins[Q](buildEmailVerificationOtpColumns(alias), j.typ)
}

func buildEmailVerificationOtpJoins[Q dialect.Joinable](cols emailVerificationOtpColumns, typ string) emailVerificationOtpJoins[Q] {
	return emailVerificationOtpJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
