// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Otp is an object representing the database table.
type Otp struct {
	ID        int64               `db:"id,pk" `
	UserID    int64               `db:"user_id" `
	Code      string              `db:"code" `
	Purpose   string              `db:"purpose" `
	ExpiresAt time.Time           `db:"expires_at" `
	UsedAt    null.Val[time.Time] `db:"used_at" `
	CreatedAt null.Val[time.Time] `db:"created_at" `

	R otpR `db:"-" `
}

// OtpSlice is an alias for a slice of pointers to Otp.
// This should almost always be used instead of []*Otp.
type OtpSlice []*Otp

// Otps contains methods to work with the otps table
var Otps = psql.NewTablex[*Otp, OtpSlice, *OtpSetter]("", "otps", buildOtpColumns("otps"))

// OtpsQuery is a query on the otps table
type OtpsQuery = *psql.ViewQuery[*Otp, OtpSlice]

// otpR is where relationships are stored.
type otpR struct {
	User *User // otps.otps_user_id_fkey
}

func buildOtpColumns(tableName string) otpColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "user_id", "code", "purpose", "expires_at", "used_at", "created_at",
	)
	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}
	return otpColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          psql.Quote(tableName, "id"),
		UserID:      psql.Quote(tableName, "user_id"),
		Code:        psql.Quote(tableName, "code"),
		Purpose:     psql.Quote(tableName, "purpose"),
		ExpiresAt:   psql.Quote(tableName, "expires_at"),
		UsedAt:      psql.Quote(tableName, "used_at"),
		CreatedAt:   psql.Quote(tableName, "created_at"),
	}
}

type otpColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	UserID     psql.Expression
	Code       psql.Expression
	Purpose    psql.Expression
	ExpiresAt  psql.Expression
	UsedAt     psql.Expression
	CreatedAt  psql.Expression
}

func (c otpColumns) Alias() string {
	return c.tableAlias
}

func (otpColumns) AliasedAs(tableName string) otpColumns {
	return buildOtpColumns(tableName)
}

func (c otpColumns) Unqualified() otpColumns {
	return buildOtpColumns("")
}

// OtpSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type OtpSetter struct {
	ID        omit.Val[int64]         `db:"id,pk" `
	UserID    omit.Val[int64]         `db:"user_id" `
	Code      omit.Val[string]        `db:"code" `
	Purpose   omit.Val[string]        `db:"purpose" `
	ExpiresAt omit.Val[time.Time]     `db:"expires_at" `
	UsedAt    omitnull.Val[time.Time] `db:"used_at" `
	CreatedAt omitnull.Val[time.Time] `db:"created_at" `
}

func (s OtpSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Code.IsValue() {
		vals = append(vals, "code")
	}
	if s.Purpose.IsValue() {
		vals = append(vals, "purpose")
	}
	if s.ExpiresAt.IsValue() {
		vals = append(vals, "expires_at")
	}
	if !s.UsedAt.IsUnset() {
		vals = append(vals, "used_at")
	}
	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s OtpSetter) Overwrite(t *Otp) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Code.IsValue() {
		t.Code = s.Code.MustGet()
	}
	if s.Purpose.IsValue() {
		t.Purpose = s.Purpose.MustGet()
	}
	if s.ExpiresAt.IsValue() {
		t.ExpiresAt = s.ExpiresAt.MustGet()
	}
	if !s.UsedAt.IsUnset() {
		t.UsedAt = s.UsedAt.MustGetNull()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt = s.CreatedAt.MustGetNull()
	}
}

func (s *OtpSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Otps.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 7)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Code.IsValue() {
			vals[2] = psql.Arg(s.Code.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Purpose.IsValue() {
			vals[3] = psql.Arg(s.Purpose.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.ExpiresAt.IsValue() {
			vals[4] = psql.Arg(s.ExpiresAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.UsedAt.IsUnset() {
			vals[5] = psql.Arg(s.UsedAt.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.CreatedAt.IsUnset() {
			vals[6] = psql.Arg(s.CreatedAt.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s OtpSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s OtpSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Code.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "code")...),
			psql.Arg(s.Code),
		}})
	}

	if s.Purpose.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "purpose")...),
			psql.Arg(s.Purpose),
		}})
	}

	if s.ExpiresAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "expires_at")...),
			psql.Arg(s.ExpiresAt),
		}})
	}

	if !s.UsedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "used_at")...),
			psql.Arg(s.UsedAt),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindOtp retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindOtp(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Otp, error) {
	if len(cols) == 0 {
		return Otps.Query(
			sm.Where(Otps.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Otps.Query(
		sm.Where(Otps.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Otps.Columns.Only(cols...)),
	).One(ctx, exec)
}

// OtpExists checks the presence of a single record by primary key
func OtpExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Otps.Query(
		sm.Where(Otps.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Otp is retrieved from the database
func (o *Otp) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Otps.AfterSelectHooks.RunHooks(ctx, exec, OtpSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Otps.AfterInsertHooks.RunHooks(ctx, exec, OtpSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Otps.AfterUpdateHooks.RunHooks(ctx, exec, OtpSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Otps.AfterDeleteHooks.RunHooks(ctx, exec, OtpSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Otps.AfterMergeHooks.RunHooks(ctx, exec, OtpSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Otp
func (o *Otp) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Otp) pkEQ() dialect.Expression {
	return psql.Quote("otps", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Otp
func (o *Otp) Update(ctx context.Context, exec bob.Executor, s *OtpSetter) error {
	v, err := Otps.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Otp record with an executor
func (o *Otp) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Otps.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Otp using the executor
func (o *Otp) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Otps.Query(
		sm.Where(Otps.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after OtpSlice is retrieved from the database
func (o OtpSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Otps.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Otps.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Otps.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Otps.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Otps.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o OtpSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("otps", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o OtpSlice) copyMatchingRows(from ...*Otp) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o OtpSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Otps.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Otp:
				o.copyMatchingRows(retrieved)
			case []*Otp:
				o.copyMatchingRows(retrieved...)
			case OtpSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Otp or a slice of Otp
				// then run the AfterUpdateHooks on the slice
				_, err = Otps.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o OtpSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Otps.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Otp:
				o.copyMatchingRows(retrieved)
			case []*Otp:
				o.copyMatchingRows(retrieved...)
			case OtpSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Otp or a slice of Otp
				// then run the AfterDeleteHooks on the slice
				_, err = Otps.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o OtpSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Otps.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Otp:
				o.copyMatchingRows(retrieved)
			case []*Otp:
				o.copyMatchingRows(retrieved...)
			case OtpSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Otp or a slice of Otp
				// then run the AfterMergeHooks on the slice
				_, err = Otps.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o OtpSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals OtpSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Otps.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o OtpSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Otps.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o OtpSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Otps.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *Otp) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os OtpSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachOtpUser0(ctx context.Context, exec bob.Executor, count int, otp0 *Otp, user1 *User) (*Otp, error) {
	setter := &OtpSetter{
		UserID: omit.From(user1.ID),
	}

	err := otp0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachOtpUser0: %w", err)
	}

	return otp0, nil
}

func (otp0 *Otp) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachOtpUser0(ctx, exec, 1, otp0, user1)
	if err != nil {
		return err
	}

	otp0.R.User = user1

	user1.R.Otps = append(user1.R.Otps, otp0)

	return nil
}

func (otp0 *Otp) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachOtpUser0(ctx, exec, 1, otp0, user1)
	if err != nil {
		return err
	}

	otp0.R.User = user1

	user1.R.Otps = append(user1.R.Otps, otp0)

	return nil
}

type otpWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, int64]
	UserID    psql.WhereMod[Q, int64]
	Code      psql.WhereMod[Q, string]
	Purpose   psql.WhereMod[Q, string]
	ExpiresAt psql.WhereMod[Q, time.Time]
	UsedAt    psql.WhereNullMod[Q, time.Time]
	CreatedAt psql.WhereNullMod[Q, time.Time]
}

func (otpWhere[Q]) AliasedAs(alias string) otpWhere[Q] {
	return buildOtpWhere[Q](buildOtpColumns(alias))
}

func buildOtpWhere[Q psql.Filterable](cols otpColumns) otpWhere[Q] {
	return otpWhere[Q]{
		ID:        psql.Where[Q, int64](cols.ID),
		UserID:    psql.Where[Q, int64](cols.UserID),
		Code:      psql.Where[Q, string](cols.Code),
		Purpose:   psql.Where[Q, string](cols.Purpose),
		ExpiresAt: psql.Where[Q, time.Time](cols.ExpiresAt),
		UsedAt:    psql.WhereNull[Q, time.Time](cols.UsedAt),
		CreatedAt: psql.WhereNull[Q, time.Time](cols.CreatedAt),
	}
}

func (o *Otp) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("otp cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Otps = OtpSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("otp has no relationship %q", name)
	}
}

type otpPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildOtpPreloader() otpPreloader {
	return otpPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Otps,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type otpThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildOtpThenLoader[Q orm.Loadable]() otpThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return otpThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the otp's User into the .R struct
func (o *Otp) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Otps = OtpSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the otp's User into the .R struct
func (os OtpSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Otps = append(rel.R.Otps, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type otpJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j otpJoins[Q]) aliasedAs(alias string) otpJoins[Q] {
	return buildOtpJoins[Q](buildOtpColumns(alias), j.typ)
}

func buildOtpJoins[Q dialect.Joinable](cols otpColumns, typ string) otpJoins[Q] {
	return otpJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
