// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// PasswordResetOtp is an object representing the database table.
type PasswordResetOtp struct {
	ID        int64               `db:"id,pk" `
	UserID    int64               `db:"user_id" `
	Code      string              `db:"code" `
	ExpiresAt time.Time           `db:"expires_at" `
	UsedAt    null.Val[time.Time] `db:"used_at" `
	CreatedAt null.Val[time.Time] `db:"created_at" `

	R passwordResetOtpR `db:"-" `
}

// PasswordResetOtpSlice is an alias for a slice of pointers to PasswordResetOtp.
// This should almost always be used instead of []*PasswordResetOtp.
type PasswordResetOtpSlice []*PasswordResetOtp

// PasswordResetOtps contains methods to work with the password_reset_otps table
var PasswordResetOtps = psql.NewTablex[*PasswordResetOtp, PasswordResetOtpSlice, *PasswordResetOtpSetter]("", "password_reset_otps", buildPasswordResetOtpColumns("password_reset_otps"))

// PasswordResetOtpsQuery is a query on the password_reset_otps table
type PasswordResetOtpsQuery = *psql.ViewQuery[*PasswordResetOtp, PasswordResetOtpSlice]

// passwordResetOtpR is where relationships are stored.
type passwordResetOtpR struct {
	User *User // password_reset_otps.password_reset_otps_user_id_fkey
}

func buildPasswordResetOtpColumns(alias string) passwordResetOtpColumns {
	return passwordResetOtpColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "code", "expires_at", "used_at", "created_at",
		).WithParent("password_reset_otps"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		UserID:     psql.Quote(alias, "user_id"),
		Code:       psql.Quote(alias, "code"),
		ExpiresAt:  psql.Quote(alias, "expires_at"),
		UsedAt:     psql.Quote(alias, "used_at"),
		CreatedAt:  psql.Quote(alias, "created_at"),
	}
}

type passwordResetOtpColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	UserID     psql.Expression
	Code       psql.Expression
	ExpiresAt  psql.Expression
	UsedAt     psql.Expression
	CreatedAt  psql.Expression
}

func (c passwordResetOtpColumns) Alias() string {
	return c.tableAlias
}

func (passwordResetOtpColumns) AliasedAs(alias string) passwordResetOtpColumns {
	return buildPasswordResetOtpColumns(alias)
}

// PasswordResetOtpSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PasswordResetOtpSetter struct {
	ID        omit.Val[int64]         `db:"id,pk" `
	UserID    omit.Val[int64]         `db:"user_id" `
	Code      omit.Val[string]        `db:"code" `
	ExpiresAt omit.Val[time.Time]     `db:"expires_at" `
	UsedAt    omitnull.Val[time.Time] `db:"used_at" `
	CreatedAt omitnull.Val[time.Time] `db:"created_at" `
}

func (s PasswordResetOtpSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Code.IsValue() {
		vals = append(vals, "code")
	}
	if s.ExpiresAt.IsValue() {
		vals = append(vals, "expires_at")
	}
	if !s.UsedAt.IsUnset() {
		vals = append(vals, "used_at")
	}
	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s PasswordResetOtpSetter) Overwrite(t *PasswordResetOtp) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Code.IsValue() {
		t.Code = s.Code.MustGet()
	}
	if s.ExpiresAt.IsValue() {
		t.ExpiresAt = s.ExpiresAt.MustGet()
	}
	if !s.UsedAt.IsUnset() {
		t.UsedAt = s.UsedAt.MustGetNull()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt = s.CreatedAt.MustGetNull()
	}
}

func (s *PasswordResetOtpSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return PasswordResetOtps.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Code.IsValue() {
			vals[2] = psql.Arg(s.Code.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.ExpiresAt.IsValue() {
			vals[3] = psql.Arg(s.ExpiresAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.UsedAt.IsUnset() {
			vals[4] = psql.Arg(s.UsedAt.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.CreatedAt.IsUnset() {
			vals[5] = psql.Arg(s.CreatedAt.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s PasswordResetOtpSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s PasswordResetOtpSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Code.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "code")...),
			psql.Arg(s.Code),
		}})
	}

	if s.ExpiresAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "expires_at")...),
			psql.Arg(s.ExpiresAt),
		}})
	}

	if !s.UsedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "used_at")...),
			psql.Arg(s.UsedAt),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindPasswordResetOtp retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPasswordResetOtp(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*PasswordResetOtp, error) {
	if len(cols) == 0 {
		return PasswordResetOtps.Query(
			sm.Where(PasswordResetOtps.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return PasswordResetOtps.Query(
		sm.Where(PasswordResetOtps.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(PasswordResetOtps.Columns.Only(cols...)),
	).One(ctx, exec)
}

// PasswordResetOtpExists checks the presence of a single record by primary key
func PasswordResetOtpExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return PasswordResetOtps.Query(
		sm.Where(PasswordResetOtps.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after PasswordResetOtp is retrieved from the database
func (o *PasswordResetOtp) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PasswordResetOtps.AfterSelectHooks.RunHooks(ctx, exec, PasswordResetOtpSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = PasswordResetOtps.AfterInsertHooks.RunHooks(ctx, exec, PasswordResetOtpSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = PasswordResetOtps.AfterUpdateHooks.RunHooks(ctx, exec, PasswordResetOtpSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = PasswordResetOtps.AfterDeleteHooks.RunHooks(ctx, exec, PasswordResetOtpSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the PasswordResetOtp
func (o *PasswordResetOtp) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *PasswordResetOtp) pkEQ() dialect.Expression {
	return psql.Quote("password_reset_otps", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the PasswordResetOtp
func (o *PasswordResetOtp) Update(ctx context.Context, exec bob.Executor, s *PasswordResetOtpSetter) error {
	v, err := PasswordResetOtps.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single PasswordResetOtp record with an executor
func (o *PasswordResetOtp) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := PasswordResetOtps.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the PasswordResetOtp using the executor
func (o *PasswordResetOtp) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := PasswordResetOtps.Query(
		sm.Where(PasswordResetOtps.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after PasswordResetOtpSlice is retrieved from the database
func (o PasswordResetOtpSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PasswordResetOtps.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = PasswordResetOtps.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = PasswordResetOtps.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = PasswordResetOtps.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PasswordResetOtpSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("password_reset_otps", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PasswordResetOtpSlice) copyMatchingRows(from ...*PasswordResetOtp) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PasswordResetOtpSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PasswordResetOtps.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PasswordResetOtp:
				o.copyMatchingRows(retrieved)
			case []*PasswordResetOtp:
				o.copyMatchingRows(retrieved...)
			case PasswordResetOtpSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PasswordResetOtp or a slice of PasswordResetOtp
				// then run the AfterUpdateHooks on the slice
				_, err = PasswordResetOtps.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PasswordResetOtpSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PasswordResetOtps.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PasswordResetOtp:
				o.copyMatchingRows(retrieved)
			case []*PasswordResetOtp:
				o.copyMatchingRows(retrieved...)
			case PasswordResetOtpSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PasswordResetOtp or a slice of PasswordResetOtp
				// then run the AfterDeleteHooks on the slice
				_, err = PasswordResetOtps.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o PasswordResetOtpSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PasswordResetOtpSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PasswordResetOtps.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o PasswordResetOtpSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PasswordResetOtps.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PasswordResetOtpSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := PasswordResetOtps.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *PasswordResetOtp) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os PasswordResetOtpSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachPasswordResetOtpUser0(ctx context.Context, exec bob.Executor, count int, passwordResetOtp0 *PasswordResetOtp, user1 *User) (*PasswordResetOtp, error) {
	setter := &PasswordResetOtpSetter{
		UserID: omit.From(user1.ID),
	}

	err := passwordResetOtp0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachPasswordResetOtpUser0: %w", err)
	}

	return passwordResetOtp0, nil
}

func (passwordResetOtp0 *PasswordResetOtp) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachPasswordResetOtpUser0(ctx, exec, 1, passwordResetOtp0, user1)
	if err != nil {
		return err
	}

	passwordResetOtp0.R.User = user1

	user1.R.PasswordResetOtps = append(user1.R.PasswordResetOtps, passwordResetOtp0)

	return nil
}

func (passwordResetOtp0 *PasswordResetOtp) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachPasswordResetOtpUser0(ctx, exec, 1, passwordResetOtp0, user1)
	if err != nil {
		return err
	}

	passwordResetOtp0.R.User = user1

	user1.R.PasswordResetOtps = append(user1.R.PasswordResetOtps, passwordResetOtp0)

	return nil
}

type passwordResetOtpWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, int64]
	UserID    psql.WhereMod[Q, int64]
	Code      psql.WhereMod[Q, string]
	ExpiresAt psql.WhereMod[Q, time.Time]
	UsedAt    psql.WhereNullMod[Q, time.Time]
	CreatedAt psql.WhereNullMod[Q, time.Time]
}

func (passwordResetOtpWhere[Q]) AliasedAs(alias string) passwordResetOtpWhere[Q] {
	return buildPasswordResetOtpWhere[Q](buildPasswordResetOtpColumns(alias))
}

func buildPasswordResetOtpWhere[Q psql.Filterable](cols passwordResetOtpColumns) passwordResetOtpWhere[Q] {
	return passwordResetOtpWhere[Q]{
		ID:        psql.Where[Q, int64](cols.ID),
		UserID:    psql.Where[Q, int64](cols.UserID),
		Code:      psql.Where[Q, string](cols.Code),
		ExpiresAt: psql.Where[Q, time.Time](cols.ExpiresAt),
		UsedAt:    psql.WhereNull[Q, time.Time](cols.UsedAt),
		CreatedAt: psql.WhereNull[Q, time.Time](cols.CreatedAt),
	}
}

func (o *PasswordResetOtp) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("passwordResetOtp cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.PasswordResetOtps = PasswordResetOtpSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("passwordResetOtp has no relationship %q", name)
	}
}

type passwordResetOtpPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildPasswordResetOtpPreloader() passwordResetOtpPreloader {
	return passwordResetOtpPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        PasswordResetOtps,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type passwordResetOtpThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildPasswordResetOtpThenLoader[Q orm.Loadable]() passwordResetOtpThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return passwordResetOtpThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the passwordResetOtp's User into the .R struct
func (o *PasswordResetOtp) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.PasswordResetOtps = PasswordResetOtpSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the passwordResetOtp's User into the .R struct
func (os PasswordResetOtpSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.PasswordResetOtps = append(rel.R.PasswordResetOtps, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type passwordResetOtpJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j passwordResetOtpJoins[Q]) aliasedAs(alias string) passwordResetOtpJoins[Q] {
	return buildPasswordResetOtpJoins[Q](buildPasswordResetOtpColumns(alias), j.typ)
}

func buildPasswordResetOtpJoins[Q dialect.Joinable](cols passwordResetOtpColumns, typ string) passwordResetOtpJoins[Q] {
	return passwordResetOtpJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
