// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// RefreshToken is an object representing the database table.
type RefreshToken struct {
	ID              int64               `db:"id,pk" `
	UserID          int64               `db:"user_id" `
	Token           string              `db:"token" `
	DeviceName      null.Val[string]    `db:"device_name" `
	DeviceID        null.Val[string]    `db:"device_id" `
	IPAddress       null.Val[string]    `db:"ip_address" `
	UserAgent       null.Val[string]    `db:"user_agent" `
	ExpiresAt       time.Time           `db:"expires_at" `
	CreatedAt       null.Val[time.Time] `db:"created_at" `
	RevokedAt       null.Val[time.Time] `db:"revoked_at" `
	ReplacedByToken null.Val[string]    `db:"replaced_by_token" `

	R refreshTokenR `db:"-" `
}

// RefreshTokenSlice is an alias for a slice of pointers to RefreshToken.
// This should almost always be used instead of []*RefreshToken.
type RefreshTokenSlice []*RefreshToken

// RefreshTokens contains methods to work with the refresh_tokens table
var RefreshTokens = psql.NewTablex[*RefreshToken, RefreshTokenSlice, *RefreshTokenSetter]("", "refresh_tokens", buildRefreshTokenColumns("refresh_tokens"))

// RefreshTokensQuery is a query on the refresh_tokens table
type RefreshTokensQuery = *psql.ViewQuery[*RefreshToken, RefreshTokenSlice]

// refreshTokenR is where relationships are stored.
type refreshTokenR struct {
	User *User // refresh_tokens.refresh_tokens_user_id_fkey
}

func buildRefreshTokenColumns(alias string) refreshTokenColumns {
	return refreshTokenColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "token", "device_name", "device_id", "ip_address", "user_agent", "expires_at", "created_at", "revoked_at", "replaced_by_token",
		).WithParent("refresh_tokens"),
		tableAlias:      alias,
		ID:              psql.Quote(alias, "id"),
		UserID:          psql.Quote(alias, "user_id"),
		Token:           psql.Quote(alias, "token"),
		DeviceName:      psql.Quote(alias, "device_name"),
		DeviceID:        psql.Quote(alias, "device_id"),
		IPAddress:       psql.Quote(alias, "ip_address"),
		UserAgent:       psql.Quote(alias, "user_agent"),
		ExpiresAt:       psql.Quote(alias, "expires_at"),
		CreatedAt:       psql.Quote(alias, "created_at"),
		RevokedAt:       psql.Quote(alias, "revoked_at"),
		ReplacedByToken: psql.Quote(alias, "replaced_by_token"),
	}
}

type refreshTokenColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ID              psql.Expression
	UserID          psql.Expression
	Token           psql.Expression
	DeviceName      psql.Expression
	DeviceID        psql.Expression
	IPAddress       psql.Expression
	UserAgent       psql.Expression
	ExpiresAt       psql.Expression
	CreatedAt       psql.Expression
	RevokedAt       psql.Expression
	ReplacedByToken psql.Expression
}

func (c refreshTokenColumns) Alias() string {
	return c.tableAlias
}

func (refreshTokenColumns) AliasedAs(alias string) refreshTokenColumns {
	return buildRefreshTokenColumns(alias)
}

// RefreshTokenSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type RefreshTokenSetter struct {
	ID              omit.Val[int64]         `db:"id,pk" `
	UserID          omit.Val[int64]         `db:"user_id" `
	Token           omit.Val[string]        `db:"token" `
	DeviceName      omitnull.Val[string]    `db:"device_name" `
	DeviceID        omitnull.Val[string]    `db:"device_id" `
	IPAddress       omitnull.Val[string]    `db:"ip_address" `
	UserAgent       omitnull.Val[string]    `db:"user_agent" `
	ExpiresAt       omit.Val[time.Time]     `db:"expires_at" `
	CreatedAt       omitnull.Val[time.Time] `db:"created_at" `
	RevokedAt       omitnull.Val[time.Time] `db:"revoked_at" `
	ReplacedByToken omitnull.Val[string]    `db:"replaced_by_token" `
}

func (s RefreshTokenSetter) SetColumns() []string {
	vals := make([]string, 0, 11)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Token.IsValue() {
		vals = append(vals, "token")
	}
	if !s.DeviceName.IsUnset() {
		vals = append(vals, "device_name")
	}
	if !s.DeviceID.IsUnset() {
		vals = append(vals, "device_id")
	}
	if !s.IPAddress.IsUnset() {
		vals = append(vals, "ip_address")
	}
	if !s.UserAgent.IsUnset() {
		vals = append(vals, "user_agent")
	}
	if s.ExpiresAt.IsValue() {
		vals = append(vals, "expires_at")
	}
	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}
	if !s.RevokedAt.IsUnset() {
		vals = append(vals, "revoked_at")
	}
	if !s.ReplacedByToken.IsUnset() {
		vals = append(vals, "replaced_by_token")
	}
	return vals
}

func (s RefreshTokenSetter) Overwrite(t *RefreshToken) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Token.IsValue() {
		t.Token = s.Token.MustGet()
	}
	if !s.DeviceName.IsUnset() {
		t.DeviceName = s.DeviceName.MustGetNull()
	}
	if !s.DeviceID.IsUnset() {
		t.DeviceID = s.DeviceID.MustGetNull()
	}
	if !s.IPAddress.IsUnset() {
		t.IPAddress = s.IPAddress.MustGetNull()
	}
	if !s.UserAgent.IsUnset() {
		t.UserAgent = s.UserAgent.MustGetNull()
	}
	if s.ExpiresAt.IsValue() {
		t.ExpiresAt = s.ExpiresAt.MustGet()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt = s.CreatedAt.MustGetNull()
	}
	if !s.RevokedAt.IsUnset() {
		t.RevokedAt = s.RevokedAt.MustGetNull()
	}
	if !s.ReplacedByToken.IsUnset() {
		t.ReplacedByToken = s.ReplacedByToken.MustGetNull()
	}
}

func (s *RefreshTokenSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return RefreshTokens.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 11)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Token.IsValue() {
			vals[2] = psql.Arg(s.Token.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.DeviceName.IsUnset() {
			vals[3] = psql.Arg(s.DeviceName.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.DeviceID.IsUnset() {
			vals[4] = psql.Arg(s.DeviceID.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.IPAddress.IsUnset() {
			vals[5] = psql.Arg(s.IPAddress.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.UserAgent.IsUnset() {
			vals[6] = psql.Arg(s.UserAgent.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.ExpiresAt.IsValue() {
			vals[7] = psql.Arg(s.ExpiresAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.CreatedAt.IsUnset() {
			vals[8] = psql.Arg(s.CreatedAt.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if !s.RevokedAt.IsUnset() {
			vals[9] = psql.Arg(s.RevokedAt.MustGetNull())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if !s.ReplacedByToken.IsUnset() {
			vals[10] = psql.Arg(s.ReplacedByToken.MustGetNull())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s RefreshTokenSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s RefreshTokenSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 11)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Token.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "token")...),
			psql.Arg(s.Token),
		}})
	}

	if !s.DeviceName.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "device_name")...),
			psql.Arg(s.DeviceName),
		}})
	}

	if !s.DeviceID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "device_id")...),
			psql.Arg(s.DeviceID),
		}})
	}

	if !s.IPAddress.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "ip_address")...),
			psql.Arg(s.IPAddress),
		}})
	}

	if !s.UserAgent.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_agent")...),
			psql.Arg(s.UserAgent),
		}})
	}

	if s.ExpiresAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "expires_at")...),
			psql.Arg(s.ExpiresAt),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.RevokedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "revoked_at")...),
			psql.Arg(s.RevokedAt),
		}})
	}

	if !s.ReplacedByToken.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "replaced_by_token")...),
			psql.Arg(s.ReplacedByToken),
		}})
	}

	return exprs
}

// FindRefreshToken retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindRefreshToken(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*RefreshToken, error) {
	if len(cols) == 0 {
		return RefreshTokens.Query(
			sm.Where(RefreshTokens.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return RefreshTokens.Query(
		sm.Where(RefreshTokens.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(RefreshTokens.Columns.Only(cols...)),
	).One(ctx, exec)
}

// RefreshTokenExists checks the presence of a single record by primary key
func RefreshTokenExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return RefreshTokens.Query(
		sm.Where(RefreshTokens.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after RefreshToken is retrieved from the database
func (o *RefreshToken) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RefreshTokens.AfterSelectHooks.RunHooks(ctx, exec, RefreshTokenSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = RefreshTokens.AfterInsertHooks.RunHooks(ctx, exec, RefreshTokenSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = RefreshTokens.AfterUpdateHooks.RunHooks(ctx, exec, RefreshTokenSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = RefreshTokens.AfterDeleteHooks.RunHooks(ctx, exec, RefreshTokenSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the RefreshToken
func (o *RefreshToken) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *RefreshToken) pkEQ() dialect.Expression {
	return psql.Quote("refresh_tokens", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the RefreshToken
func (o *RefreshToken) Update(ctx context.Context, exec bob.Executor, s *RefreshTokenSetter) error {
	v, err := RefreshTokens.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single RefreshToken record with an executor
func (o *RefreshToken) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := RefreshTokens.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the RefreshToken using the executor
func (o *RefreshToken) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := RefreshTokens.Query(
		sm.Where(RefreshTokens.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after RefreshTokenSlice is retrieved from the database
func (o RefreshTokenSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RefreshTokens.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = RefreshTokens.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = RefreshTokens.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = RefreshTokens.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o RefreshTokenSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("refresh_tokens", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o RefreshTokenSlice) copyMatchingRows(from ...*RefreshToken) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o RefreshTokenSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RefreshTokens.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RefreshToken:
				o.copyMatchingRows(retrieved)
			case []*RefreshToken:
				o.copyMatchingRows(retrieved...)
			case RefreshTokenSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RefreshToken or a slice of RefreshToken
				// then run the AfterUpdateHooks on the slice
				_, err = RefreshTokens.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o RefreshTokenSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RefreshTokens.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RefreshToken:
				o.copyMatchingRows(retrieved)
			case []*RefreshToken:
				o.copyMatchingRows(retrieved...)
			case RefreshTokenSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RefreshToken or a slice of RefreshToken
				// then run the AfterDeleteHooks on the slice
				_, err = RefreshTokens.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o RefreshTokenSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals RefreshTokenSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RefreshTokens.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o RefreshTokenSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RefreshTokens.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o RefreshTokenSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := RefreshTokens.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *RefreshToken) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os RefreshTokenSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachRefreshTokenUser0(ctx context.Context, exec bob.Executor, count int, refreshToken0 *RefreshToken, user1 *User) (*RefreshToken, error) {
	setter := &RefreshTokenSetter{
		UserID: omit.From(user1.ID),
	}

	err := refreshToken0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachRefreshTokenUser0: %w", err)
	}

	return refreshToken0, nil
}

func (refreshToken0 *RefreshToken) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachRefreshTokenUser0(ctx, exec, 1, refreshToken0, user1)
	if err != nil {
		return err
	}

	refreshToken0.R.User = user1

	user1.R.RefreshTokens = append(user1.R.RefreshTokens, refreshToken0)

	return nil
}

func (refreshToken0 *RefreshToken) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachRefreshTokenUser0(ctx, exec, 1, refreshToken0, user1)
	if err != nil {
		return err
	}

	refreshToken0.R.User = user1

	user1.R.RefreshTokens = append(user1.R.RefreshTokens, refreshToken0)

	return nil
}

type refreshTokenWhere[Q psql.Filterable] struct {
	ID              psql.WhereMod[Q, int64]
	UserID          psql.WhereMod[Q, int64]
	Token           psql.WhereMod[Q, string]
	DeviceName      psql.WhereNullMod[Q, string]
	DeviceID        psql.WhereNullMod[Q, string]
	IPAddress       psql.WhereNullMod[Q, string]
	UserAgent       psql.WhereNullMod[Q, string]
	ExpiresAt       psql.WhereMod[Q, time.Time]
	CreatedAt       psql.WhereNullMod[Q, time.Time]
	RevokedAt       psql.WhereNullMod[Q, time.Time]
	ReplacedByToken psql.WhereNullMod[Q, string]
}

func (refreshTokenWhere[Q]) AliasedAs(alias string) refreshTokenWhere[Q] {
	return buildRefreshTokenWhere[Q](buildRefreshTokenColumns(alias))
}

func buildRefreshTokenWhere[Q psql.Filterable](cols refreshTokenColumns) refreshTokenWhere[Q] {
	return refreshTokenWhere[Q]{
		ID:              psql.Where[Q, int64](cols.ID),
		UserID:          psql.Where[Q, int64](cols.UserID),
		Token:           psql.Where[Q, string](cols.Token),
		DeviceName:      psql.WhereNull[Q, string](cols.DeviceName),
		DeviceID:        psql.WhereNull[Q, string](cols.DeviceID),
		IPAddress:       psql.WhereNull[Q, string](cols.IPAddress),
		UserAgent:       psql.WhereNull[Q, string](cols.UserAgent),
		ExpiresAt:       psql.Where[Q, time.Time](cols.ExpiresAt),
		CreatedAt:       psql.WhereNull[Q, time.Time](cols.CreatedAt),
		RevokedAt:       psql.WhereNull[Q, time.Time](cols.RevokedAt),
		ReplacedByToken: psql.WhereNull[Q, string](cols.ReplacedByToken),
	}
}

func (o *RefreshToken) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("refreshToken cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.RefreshTokens = RefreshTokenSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("refreshToken has no relationship %q", name)
	}
}

type refreshTokenPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildRefreshTokenPreloader() refreshTokenPreloader {
	return refreshTokenPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        RefreshTokens,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type refreshTokenThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildRefreshTokenThenLoader[Q orm.Loadable]() refreshTokenThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return refreshTokenThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the refreshToken's User into the .R struct
func (o *RefreshToken) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.RefreshTokens = RefreshTokenSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the refreshToken's User into the .R struct
func (os RefreshTokenSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.RefreshTokens = append(rel.R.RefreshTokens, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type refreshTokenJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j refreshTokenJoins[Q]) aliasedAs(alias string) refreshTokenJoins[Q] {
	return buildRefreshTokenJoins[Q](buildRefreshTokenColumns(alias), j.typ)
}

func buildRefreshTokenJoins[Q dialect.Joinable](cols refreshTokenColumns, typ string) refreshTokenJoins[Q] {
	return refreshTokenJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
