// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// User is an object representing the database table.
type User struct {
	ID         int64               `db:"id,pk" `
	Version    int64               `db:"version" `
	CreatedAt  null.Val[time.Time] `db:"created_at" `
	CreatedBy  int64               `db:"created_by" `
	UpdatedAt  null.Val[time.Time] `db:"updated_at" `
	UpdatedBy  int64               `db:"updated_by" `
	DeletedAt  null.Val[time.Time] `db:"deleted_at" `
	DeletedBy  null.Val[int64]     `db:"deleted_by" `
	Name       null.Val[string]    `db:"name" `
	Email      null.Val[string]    `db:"email" `
	Phone      null.Val[string]    `db:"phone" `
	Password   string              `db:"password" `
	LoginType  string              `db:"login_type" `
	IsVerified null.Val[bool]      `db:"is_verified" `
	VerifiedAt null.Val[time.Time] `db:"verified_at" `

	R userR `db:"-" `
}

// UserSlice is an alias for a slice of pointers to User.
// This should almost always be used instead of []*User.
type UserSlice []*User

// Users contains methods to work with the users table
var Users = psql.NewTablex[*User, UserSlice, *UserSetter]("", "users", buildUserColumns("users"))

// UsersQuery is a query on the users table
type UsersQuery = *psql.ViewQuery[*User, UserSlice]

// userR is where relationships are stored.
type userR struct {
	EmailVerificationOtps EmailVerificationOtpSlice // email_verification_otps.email_verification_otps_user_id_fkey
	PasswordResetOtps     PasswordResetOtpSlice     // password_reset_otps.password_reset_otps_user_id_fkey
	RefreshTokens         RefreshTokenSlice         // refresh_tokens.refresh_tokens_user_id_fkey
	CreatedBy             *User                     // users.fk_users_created_by
	ReverseCreatedBies    UserSlice                 // users.fk_users_created_by__self_join_reverse
	DeletedBy             *User                     // users.fk_users_deleted_by
	ReverseDeletedBies    UserSlice                 // users.fk_users_deleted_by__self_join_reverse
	UpdatedBy             *User                     // users.fk_users_updated_by
	ReverseUpdatedBies    UserSlice                 // users.fk_users_updated_by__self_join_reverse
}

func buildUserColumns(alias string) userColumns {
	return userColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "version", "created_at", "created_by", "updated_at", "updated_by", "deleted_at", "deleted_by", "name", "email", "phone", "password", "login_type", "is_verified", "verified_at",
		).WithParent("users"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		Version:    psql.Quote(alias, "version"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		CreatedBy:  psql.Quote(alias, "created_by"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
		UpdatedBy:  psql.Quote(alias, "updated_by"),
		DeletedAt:  psql.Quote(alias, "deleted_at"),
		DeletedBy:  psql.Quote(alias, "deleted_by"),
		Name:       psql.Quote(alias, "name"),
		Email:      psql.Quote(alias, "email"),
		Phone:      psql.Quote(alias, "phone"),
		Password:   psql.Quote(alias, "password"),
		LoginType:  psql.Quote(alias, "login_type"),
		IsVerified: psql.Quote(alias, "is_verified"),
		VerifiedAt: psql.Quote(alias, "verified_at"),
	}
}

type userColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	Version    psql.Expression
	CreatedAt  psql.Expression
	CreatedBy  psql.Expression
	UpdatedAt  psql.Expression
	UpdatedBy  psql.Expression
	DeletedAt  psql.Expression
	DeletedBy  psql.Expression
	Name       psql.Expression
	Email      psql.Expression
	Phone      psql.Expression
	Password   psql.Expression
	LoginType  psql.Expression
	IsVerified psql.Expression
	VerifiedAt psql.Expression
}

func (c userColumns) Alias() string {
	return c.tableAlias
}

func (userColumns) AliasedAs(alias string) userColumns {
	return buildUserColumns(alias)
}

// UserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSetter struct {
	ID         omit.Val[int64]         `db:"id,pk" `
	Version    omit.Val[int64]         `db:"version" `
	CreatedAt  omitnull.Val[time.Time] `db:"created_at" `
	CreatedBy  omit.Val[int64]         `db:"created_by" `
	UpdatedAt  omitnull.Val[time.Time] `db:"updated_at" `
	UpdatedBy  omit.Val[int64]         `db:"updated_by" `
	DeletedAt  omitnull.Val[time.Time] `db:"deleted_at" `
	DeletedBy  omitnull.Val[int64]     `db:"deleted_by" `
	Name       omitnull.Val[string]    `db:"name" `
	Email      omitnull.Val[string]    `db:"email" `
	Phone      omitnull.Val[string]    `db:"phone" `
	Password   omit.Val[string]        `db:"password" `
	LoginType  omit.Val[string]        `db:"login_type" `
	IsVerified omitnull.Val[bool]      `db:"is_verified" `
	VerifiedAt omitnull.Val[time.Time] `db:"verified_at" `
}

func (s UserSetter) SetColumns() []string {
	vals := make([]string, 0, 15)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Version.IsValue() {
		vals = append(vals, "version")
	}
	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}
	if s.CreatedBy.IsValue() {
		vals = append(vals, "created_by")
	}
	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}
	if s.UpdatedBy.IsValue() {
		vals = append(vals, "updated_by")
	}
	if !s.DeletedAt.IsUnset() {
		vals = append(vals, "deleted_at")
	}
	if !s.DeletedBy.IsUnset() {
		vals = append(vals, "deleted_by")
	}
	if !s.Name.IsUnset() {
		vals = append(vals, "name")
	}
	if !s.Email.IsUnset() {
		vals = append(vals, "email")
	}
	if !s.Phone.IsUnset() {
		vals = append(vals, "phone")
	}
	if s.Password.IsValue() {
		vals = append(vals, "password")
	}
	if s.LoginType.IsValue() {
		vals = append(vals, "login_type")
	}
	if !s.IsVerified.IsUnset() {
		vals = append(vals, "is_verified")
	}
	if !s.VerifiedAt.IsUnset() {
		vals = append(vals, "verified_at")
	}
	return vals
}

func (s UserSetter) Overwrite(t *User) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Version.IsValue() {
		t.Version = s.Version.MustGet()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt = s.CreatedAt.MustGetNull()
	}
	if s.CreatedBy.IsValue() {
		t.CreatedBy = s.CreatedBy.MustGet()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt = s.UpdatedAt.MustGetNull()
	}
	if s.UpdatedBy.IsValue() {
		t.UpdatedBy = s.UpdatedBy.MustGet()
	}
	if !s.DeletedAt.IsUnset() {
		t.DeletedAt = s.DeletedAt.MustGetNull()
	}
	if !s.DeletedBy.IsUnset() {
		t.DeletedBy = s.DeletedBy.MustGetNull()
	}
	if !s.Name.IsUnset() {
		t.Name = s.Name.MustGetNull()
	}
	if !s.Email.IsUnset() {
		t.Email = s.Email.MustGetNull()
	}
	if !s.Phone.IsUnset() {
		t.Phone = s.Phone.MustGetNull()
	}
	if s.Password.IsValue() {
		t.Password = s.Password.MustGet()
	}
	if s.LoginType.IsValue() {
		t.LoginType = s.LoginType.MustGet()
	}
	if !s.IsVerified.IsUnset() {
		t.IsVerified = s.IsVerified.MustGetNull()
	}
	if !s.VerifiedAt.IsUnset() {
		t.VerifiedAt = s.VerifiedAt.MustGetNull()
	}
}

func (s *UserSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Users.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 15)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Version.IsValue() {
			vals[1] = psql.Arg(s.Version.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if !s.CreatedAt.IsUnset() {
			vals[2] = psql.Arg(s.CreatedAt.MustGetNull())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.CreatedBy.IsValue() {
			vals[3] = psql.Arg(s.CreatedBy.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.UpdatedAt.IsUnset() {
			vals[4] = psql.Arg(s.UpdatedAt.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.UpdatedBy.IsValue() {
			vals[5] = psql.Arg(s.UpdatedBy.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.DeletedAt.IsUnset() {
			vals[6] = psql.Arg(s.DeletedAt.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.DeletedBy.IsUnset() {
			vals[7] = psql.Arg(s.DeletedBy.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.Name.IsUnset() {
			vals[8] = psql.Arg(s.Name.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if !s.Email.IsUnset() {
			vals[9] = psql.Arg(s.Email.MustGetNull())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if !s.Phone.IsUnset() {
			vals[10] = psql.Arg(s.Phone.MustGetNull())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if s.Password.IsValue() {
			vals[11] = psql.Arg(s.Password.MustGet())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		if s.LoginType.IsValue() {
			vals[12] = psql.Arg(s.LoginType.MustGet())
		} else {
			vals[12] = psql.Raw("DEFAULT")
		}

		if !s.IsVerified.IsUnset() {
			vals[13] = psql.Arg(s.IsVerified.MustGetNull())
		} else {
			vals[13] = psql.Raw("DEFAULT")
		}

		if !s.VerifiedAt.IsUnset() {
			vals[14] = psql.Arg(s.VerifiedAt.MustGetNull())
		} else {
			vals[14] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 15)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Version.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "version")...),
			psql.Arg(s.Version),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.CreatedBy.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_by")...),
			psql.Arg(s.CreatedBy),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.UpdatedBy.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_by")...),
			psql.Arg(s.UpdatedBy),
		}})
	}

	if !s.DeletedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "deleted_at")...),
			psql.Arg(s.DeletedAt),
		}})
	}

	if !s.DeletedBy.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "deleted_by")...),
			psql.Arg(s.DeletedBy),
		}})
	}

	if !s.Name.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if !s.Email.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if !s.Phone.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "phone")...),
			psql.Arg(s.Phone),
		}})
	}

	if s.Password.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "password")...),
			psql.Arg(s.Password),
		}})
	}

	if s.LoginType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "login_type")...),
			psql.Arg(s.LoginType),
		}})
	}

	if !s.IsVerified.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_verified")...),
			psql.Arg(s.IsVerified),
		}})
	}

	if !s.VerifiedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "verified_at")...),
			psql.Arg(s.VerifiedAt),
		}})
	}

	return exprs
}

// FindUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUser(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*User, error) {
	if len(cols) == 0 {
		return Users.Query(
			sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Users.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UserExists checks the presence of a single record by primary key
func UserExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after User is retrieved from the database
func (o *User) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, UserSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the User
func (o *User) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *User) pkEQ() dialect.Expression {
	return psql.Quote("users", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the User
func (o *User) Update(ctx context.Context, exec bob.Executor, s *UserSetter) error {
	v, err := Users.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single User record with an executor
func (o *User) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Users.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the User using the executor
func (o *User) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserSlice is retrieved from the database
func (o UserSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("users", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserSlice) copyMatchingRows(from ...*User) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterUpdateHooks on the slice
				_, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterDeleteHooks on the slice
				_, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Users.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// EmailVerificationOtps starts a query for related objects on email_verification_otps
func (o *User) EmailVerificationOtps(mods ...bob.Mod[*dialect.SelectQuery]) EmailVerificationOtpsQuery {
	return EmailVerificationOtps.Query(append(mods,
		sm.Where(EmailVerificationOtps.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) EmailVerificationOtps(mods ...bob.Mod[*dialect.SelectQuery]) EmailVerificationOtpsQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return EmailVerificationOtps.Query(append(mods,
		sm.Where(psql.Group(EmailVerificationOtps.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// PasswordResetOtps starts a query for related objects on password_reset_otps
func (o *User) PasswordResetOtps(mods ...bob.Mod[*dialect.SelectQuery]) PasswordResetOtpsQuery {
	return PasswordResetOtps.Query(append(mods,
		sm.Where(PasswordResetOtps.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) PasswordResetOtps(mods ...bob.Mod[*dialect.SelectQuery]) PasswordResetOtpsQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return PasswordResetOtps.Query(append(mods,
		sm.Where(psql.Group(PasswordResetOtps.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// RefreshTokens starts a query for related objects on refresh_tokens
func (o *User) RefreshTokens(mods ...bob.Mod[*dialect.SelectQuery]) RefreshTokensQuery {
	return RefreshTokens.Query(append(mods,
		sm.Where(RefreshTokens.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) RefreshTokens(mods ...bob.Mod[*dialect.SelectQuery]) RefreshTokensQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return RefreshTokens.Query(append(mods,
		sm.Where(psql.Group(RefreshTokens.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// CreatedBy starts a query for related objects on users
func (o *User) RelatedCreatedBy(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.CreatedBy))),
	)...)
}

func (os UserSlice) RelatedCreatedBy(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkCreatedBy := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkCreatedBy = append(pkCreatedBy, o.CreatedBy)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkCreatedBy), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// ReverseCreatedBies starts a query for related objects on users
func (o *User) ReverseCreatedBies(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.CreatedBy.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) ReverseCreatedBies(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.CreatedBy).OP("IN", PKArgExpr)),
	)...)
}

// DeletedBy starts a query for related objects on users
func (o *User) RelatedDeletedBy(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.DeletedBy))),
	)...)
}

func (os UserSlice) RelatedDeletedBy(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkDeletedBy := make(pgtypes.Array[null.Val[int64]], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkDeletedBy = append(pkDeletedBy, o.DeletedBy)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkDeletedBy), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// ReverseDeletedBies starts a query for related objects on users
func (o *User) ReverseDeletedBies(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.DeletedBy.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) ReverseDeletedBies(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.DeletedBy).OP("IN", PKArgExpr)),
	)...)
}

// UpdatedBy starts a query for related objects on users
func (o *User) RelatedUpdatedBy(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UpdatedBy))),
	)...)
}

func (os UserSlice) RelatedUpdatedBy(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUpdatedBy := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUpdatedBy = append(pkUpdatedBy, o.UpdatedBy)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUpdatedBy), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// ReverseUpdatedBies starts a query for related objects on users
func (o *User) ReverseUpdatedBies(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.UpdatedBy.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) ReverseUpdatedBies(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.UpdatedBy).OP("IN", PKArgExpr)),
	)...)
}

func insertUserEmailVerificationOtps0(ctx context.Context, exec bob.Executor, emailVerificationOtps1 []*EmailVerificationOtpSetter, user0 *User) (EmailVerificationOtpSlice, error) {
	for i := range emailVerificationOtps1 {
		emailVerificationOtps1[i].UserID = omit.From(user0.ID)
	}

	ret, err := EmailVerificationOtps.Insert(bob.ToMods(emailVerificationOtps1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserEmailVerificationOtps0: %w", err)
	}

	return ret, nil
}

func attachUserEmailVerificationOtps0(ctx context.Context, exec bob.Executor, count int, emailVerificationOtps1 EmailVerificationOtpSlice, user0 *User) (EmailVerificationOtpSlice, error) {
	setter := &EmailVerificationOtpSetter{
		UserID: omit.From(user0.ID),
	}

	err := emailVerificationOtps1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserEmailVerificationOtps0: %w", err)
	}

	return emailVerificationOtps1, nil
}

func (user0 *User) InsertEmailVerificationOtps(ctx context.Context, exec bob.Executor, related ...*EmailVerificationOtpSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	emailVerificationOtps1, err := insertUserEmailVerificationOtps0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.EmailVerificationOtps = append(user0.R.EmailVerificationOtps, emailVerificationOtps1...)

	for _, rel := range emailVerificationOtps1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachEmailVerificationOtps(ctx context.Context, exec bob.Executor, related ...*EmailVerificationOtp) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	emailVerificationOtps1 := EmailVerificationOtpSlice(related)

	_, err = attachUserEmailVerificationOtps0(ctx, exec, len(related), emailVerificationOtps1, user0)
	if err != nil {
		return err
	}

	user0.R.EmailVerificationOtps = append(user0.R.EmailVerificationOtps, emailVerificationOtps1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserPasswordResetOtps0(ctx context.Context, exec bob.Executor, passwordResetOtps1 []*PasswordResetOtpSetter, user0 *User) (PasswordResetOtpSlice, error) {
	for i := range passwordResetOtps1 {
		passwordResetOtps1[i].UserID = omit.From(user0.ID)
	}

	ret, err := PasswordResetOtps.Insert(bob.ToMods(passwordResetOtps1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserPasswordResetOtps0: %w", err)
	}

	return ret, nil
}

func attachUserPasswordResetOtps0(ctx context.Context, exec bob.Executor, count int, passwordResetOtps1 PasswordResetOtpSlice, user0 *User) (PasswordResetOtpSlice, error) {
	setter := &PasswordResetOtpSetter{
		UserID: omit.From(user0.ID),
	}

	err := passwordResetOtps1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserPasswordResetOtps0: %w", err)
	}

	return passwordResetOtps1, nil
}

func (user0 *User) InsertPasswordResetOtps(ctx context.Context, exec bob.Executor, related ...*PasswordResetOtpSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	passwordResetOtps1, err := insertUserPasswordResetOtps0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.PasswordResetOtps = append(user0.R.PasswordResetOtps, passwordResetOtps1...)

	for _, rel := range passwordResetOtps1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachPasswordResetOtps(ctx context.Context, exec bob.Executor, related ...*PasswordResetOtp) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	passwordResetOtps1 := PasswordResetOtpSlice(related)

	_, err = attachUserPasswordResetOtps0(ctx, exec, len(related), passwordResetOtps1, user0)
	if err != nil {
		return err
	}

	user0.R.PasswordResetOtps = append(user0.R.PasswordResetOtps, passwordResetOtps1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserRefreshTokens0(ctx context.Context, exec bob.Executor, refreshTokens1 []*RefreshTokenSetter, user0 *User) (RefreshTokenSlice, error) {
	for i := range refreshTokens1 {
		refreshTokens1[i].UserID = omit.From(user0.ID)
	}

	ret, err := RefreshTokens.Insert(bob.ToMods(refreshTokens1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserRefreshTokens0: %w", err)
	}

	return ret, nil
}

func attachUserRefreshTokens0(ctx context.Context, exec bob.Executor, count int, refreshTokens1 RefreshTokenSlice, user0 *User) (RefreshTokenSlice, error) {
	setter := &RefreshTokenSetter{
		UserID: omit.From(user0.ID),
	}

	err := refreshTokens1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserRefreshTokens0: %w", err)
	}

	return refreshTokens1, nil
}

func (user0 *User) InsertRefreshTokens(ctx context.Context, exec bob.Executor, related ...*RefreshTokenSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	refreshTokens1, err := insertUserRefreshTokens0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.RefreshTokens = append(user0.R.RefreshTokens, refreshTokens1...)

	for _, rel := range refreshTokens1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachRefreshTokens(ctx context.Context, exec bob.Executor, related ...*RefreshToken) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	refreshTokens1 := RefreshTokenSlice(related)

	_, err = attachUserRefreshTokens0(ctx, exec, len(related), refreshTokens1, user0)
	if err != nil {
		return err
	}

	user0.R.RefreshTokens = append(user0.R.RefreshTokens, refreshTokens1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func attachUserCreatedBy0(ctx context.Context, exec bob.Executor, count int, user0 *User, user1 *User) (*User, error) {
	setter := &UserSetter{
		CreatedBy: omit.From(user1.ID),
	}

	err := user0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserCreatedBy0: %w", err)
	}

	return user0, nil
}

func (user0 *User) InsertCreatedBy(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserCreatedBy0(ctx, exec, 1, user0, user1)
	if err != nil {
		return err
	}

	user0.R.CreatedBy = user1

	user1.R.CreatedBy = user0

	return nil
}

func (user0 *User) AttachCreatedBy(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachUserCreatedBy0(ctx, exec, 1, user0, user1)
	if err != nil {
		return err
	}

	user0.R.CreatedBy = user1

	user1.R.CreatedBy = user0

	return nil
}

func insertUserReverseCreatedBies0(ctx context.Context, exec bob.Executor, users1 []*UserSetter, user0 *User) (UserSlice, error) {
	for i := range users1 {
		users1[i].CreatedBy = omit.From(user0.ID)
	}

	ret, err := Users.Insert(bob.ToMods(users1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserReverseCreatedBies0: %w", err)
	}

	return ret, nil
}

func attachUserReverseCreatedBies0(ctx context.Context, exec bob.Executor, count int, users1 UserSlice, user0 *User) (UserSlice, error) {
	setter := &UserSetter{
		CreatedBy: omit.From(user0.ID),
	}

	err := users1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserReverseCreatedBies0: %w", err)
	}

	return users1, nil
}

func (user0 *User) InsertReverseCreatedBies(ctx context.Context, exec bob.Executor, related ...*UserSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	users1, err := insertUserReverseCreatedBies0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.ReverseCreatedBies = append(user0.R.ReverseCreatedBies, users1...)

	for _, rel := range users1 {
		rel.R.ReverseCreatedBies = append(rel.R.ReverseCreatedBies, user0)
	}
	return nil
}

func (user0 *User) AttachReverseCreatedBies(ctx context.Context, exec bob.Executor, related ...*User) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	users1 := UserSlice(related)

	_, err = attachUserReverseCreatedBies0(ctx, exec, len(related), users1, user0)
	if err != nil {
		return err
	}

	user0.R.ReverseCreatedBies = append(user0.R.ReverseCreatedBies, users1...)

	for _, rel := range related {
		rel.R.ReverseCreatedBies = append(rel.R.ReverseCreatedBies, user0)
	}

	return nil
}

func attachUserDeletedBy0(ctx context.Context, exec bob.Executor, count int, user0 *User, user1 *User) (*User, error) {
	setter := &UserSetter{
		DeletedBy: omitnull.From(user1.ID),
	}

	err := user0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserDeletedBy0: %w", err)
	}

	return user0, nil
}

func (user0 *User) InsertDeletedBy(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserDeletedBy0(ctx, exec, 1, user0, user1)
	if err != nil {
		return err
	}

	user0.R.DeletedBy = user1

	user1.R.DeletedBy = user0

	return nil
}

func (user0 *User) AttachDeletedBy(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachUserDeletedBy0(ctx, exec, 1, user0, user1)
	if err != nil {
		return err
	}

	user0.R.DeletedBy = user1

	user1.R.DeletedBy = user0

	return nil
}

func insertUserReverseDeletedBies0(ctx context.Context, exec bob.Executor, users1 []*UserSetter, user0 *User) (UserSlice, error) {
	for i := range users1 {
		users1[i].DeletedBy = omitnull.From(user0.ID)
	}

	ret, err := Users.Insert(bob.ToMods(users1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserReverseDeletedBies0: %w", err)
	}

	return ret, nil
}

func attachUserReverseDeletedBies0(ctx context.Context, exec bob.Executor, count int, users1 UserSlice, user0 *User) (UserSlice, error) {
	setter := &UserSetter{
		DeletedBy: omitnull.From(user0.ID),
	}

	err := users1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserReverseDeletedBies0: %w", err)
	}

	return users1, nil
}

func (user0 *User) InsertReverseDeletedBies(ctx context.Context, exec bob.Executor, related ...*UserSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	users1, err := insertUserReverseDeletedBies0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.ReverseDeletedBies = append(user0.R.ReverseDeletedBies, users1...)

	for _, rel := range users1 {
		rel.R.ReverseDeletedBies = append(rel.R.ReverseDeletedBies, user0)
	}
	return nil
}

func (user0 *User) AttachReverseDeletedBies(ctx context.Context, exec bob.Executor, related ...*User) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	users1 := UserSlice(related)

	_, err = attachUserReverseDeletedBies0(ctx, exec, len(related), users1, user0)
	if err != nil {
		return err
	}

	user0.R.ReverseDeletedBies = append(user0.R.ReverseDeletedBies, users1...)

	for _, rel := range related {
		rel.R.ReverseDeletedBies = append(rel.R.ReverseDeletedBies, user0)
	}

	return nil
}

func attachUserUpdatedBy0(ctx context.Context, exec bob.Executor, count int, user0 *User, user1 *User) (*User, error) {
	setter := &UserSetter{
		UpdatedBy: omit.From(user1.ID),
	}

	err := user0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserUpdatedBy0: %w", err)
	}

	return user0, nil
}

func (user0 *User) InsertUpdatedBy(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserUpdatedBy0(ctx, exec, 1, user0, user1)
	if err != nil {
		return err
	}

	user0.R.UpdatedBy = user1

	user1.R.UpdatedBy = user0

	return nil
}

func (user0 *User) AttachUpdatedBy(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachUserUpdatedBy0(ctx, exec, 1, user0, user1)
	if err != nil {
		return err
	}

	user0.R.UpdatedBy = user1

	user1.R.UpdatedBy = user0

	return nil
}

func insertUserReverseUpdatedBies0(ctx context.Context, exec bob.Executor, users1 []*UserSetter, user0 *User) (UserSlice, error) {
	for i := range users1 {
		users1[i].UpdatedBy = omit.From(user0.ID)
	}

	ret, err := Users.Insert(bob.ToMods(users1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserReverseUpdatedBies0: %w", err)
	}

	return ret, nil
}

func attachUserReverseUpdatedBies0(ctx context.Context, exec bob.Executor, count int, users1 UserSlice, user0 *User) (UserSlice, error) {
	setter := &UserSetter{
		UpdatedBy: omit.From(user0.ID),
	}

	err := users1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserReverseUpdatedBies0: %w", err)
	}

	return users1, nil
}

func (user0 *User) InsertReverseUpdatedBies(ctx context.Context, exec bob.Executor, related ...*UserSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	users1, err := insertUserReverseUpdatedBies0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.ReverseUpdatedBies = append(user0.R.ReverseUpdatedBies, users1...)

	for _, rel := range users1 {
		rel.R.ReverseUpdatedBies = append(rel.R.ReverseUpdatedBies, user0)
	}
	return nil
}

func (user0 *User) AttachReverseUpdatedBies(ctx context.Context, exec bob.Executor, related ...*User) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	users1 := UserSlice(related)

	_, err = attachUserReverseUpdatedBies0(ctx, exec, len(related), users1, user0)
	if err != nil {
		return err
	}

	user0.R.ReverseUpdatedBies = append(user0.R.ReverseUpdatedBies, users1...)

	for _, rel := range related {
		rel.R.ReverseUpdatedBies = append(rel.R.ReverseUpdatedBies, user0)
	}

	return nil
}

type userWhere[Q psql.Filterable] struct {
	ID         psql.WhereMod[Q, int64]
	Version    psql.WhereMod[Q, int64]
	CreatedAt  psql.WhereNullMod[Q, time.Time]
	CreatedBy  psql.WhereMod[Q, int64]
	UpdatedAt  psql.WhereNullMod[Q, time.Time]
	UpdatedBy  psql.WhereMod[Q, int64]
	DeletedAt  psql.WhereNullMod[Q, time.Time]
	DeletedBy  psql.WhereNullMod[Q, int64]
	Name       psql.WhereNullMod[Q, string]
	Email      psql.WhereNullMod[Q, string]
	Phone      psql.WhereNullMod[Q, string]
	Password   psql.WhereMod[Q, string]
	LoginType  psql.WhereMod[Q, string]
	IsVerified psql.WhereNullMod[Q, bool]
	VerifiedAt psql.WhereNullMod[Q, time.Time]
}

func (userWhere[Q]) AliasedAs(alias string) userWhere[Q] {
	return buildUserWhere[Q](buildUserColumns(alias))
}

func buildUserWhere[Q psql.Filterable](cols userColumns) userWhere[Q] {
	return userWhere[Q]{
		ID:         psql.Where[Q, int64](cols.ID),
		Version:    psql.Where[Q, int64](cols.Version),
		CreatedAt:  psql.WhereNull[Q, time.Time](cols.CreatedAt),
		CreatedBy:  psql.Where[Q, int64](cols.CreatedBy),
		UpdatedAt:  psql.WhereNull[Q, time.Time](cols.UpdatedAt),
		UpdatedBy:  psql.Where[Q, int64](cols.UpdatedBy),
		DeletedAt:  psql.WhereNull[Q, time.Time](cols.DeletedAt),
		DeletedBy:  psql.WhereNull[Q, int64](cols.DeletedBy),
		Name:       psql.WhereNull[Q, string](cols.Name),
		Email:      psql.WhereNull[Q, string](cols.Email),
		Phone:      psql.WhereNull[Q, string](cols.Phone),
		Password:   psql.Where[Q, string](cols.Password),
		LoginType:  psql.Where[Q, string](cols.LoginType),
		IsVerified: psql.WhereNull[Q, bool](cols.IsVerified),
		VerifiedAt: psql.WhereNull[Q, time.Time](cols.VerifiedAt),
	}
}

func (o *User) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "EmailVerificationOtps":
		rels, ok := retrieved.(EmailVerificationOtpSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.EmailVerificationOtps = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "PasswordResetOtps":
		rels, ok := retrieved.(PasswordResetOtpSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.PasswordResetOtps = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "RefreshTokens":
		rels, ok := retrieved.(RefreshTokenSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.RefreshTokens = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "CreatedBy":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.CreatedBy = rel

		if rel != nil {
			rel.R.CreatedBy = o
		}
		return nil
	case "ReverseCreatedBies":
		rels, ok := retrieved.(UserSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.ReverseCreatedBies = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.ReverseCreatedBies = UserSlice{o}
			}
		}
		return nil
	case "DeletedBy":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.DeletedBy = rel

		if rel != nil {
			rel.R.DeletedBy = o
		}
		return nil
	case "ReverseDeletedBies":
		rels, ok := retrieved.(UserSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.ReverseDeletedBies = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.ReverseDeletedBies = UserSlice{o}
			}
		}
		return nil
	case "UpdatedBy":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.UpdatedBy = rel

		if rel != nil {
			rel.R.UpdatedBy = o
		}
		return nil
	case "ReverseUpdatedBies":
		rels, ok := retrieved.(UserSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.ReverseUpdatedBies = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.ReverseUpdatedBies = UserSlice{o}
			}
		}
		return nil
	default:
		return fmt.Errorf("user has no relationship %q", name)
	}
}

type userPreloader struct {
	CreatedBy func(...psql.PreloadOption) psql.Preloader
	DeletedBy func(...psql.PreloadOption) psql.Preloader
	UpdatedBy func(...psql.PreloadOption) psql.Preloader
}

func buildUserPreloader() userPreloader {
	return userPreloader{
		CreatedBy: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "CreatedBy",
				Sides: []psql.PreloadSide{
					{
						From:        Users,
						To:          Users,
						FromColumns: []string{"created_by"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
		DeletedBy: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "DeletedBy",
				Sides: []psql.PreloadSide{
					{
						From:        Users,
						To:          Users,
						FromColumns: []string{"deleted_by"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
		UpdatedBy: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "UpdatedBy",
				Sides: []psql.PreloadSide{
					{
						From:        Users,
						To:          Users,
						FromColumns: []string{"updated_by"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type userThenLoader[Q orm.Loadable] struct {
	EmailVerificationOtps func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	PasswordResetOtps     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	RefreshTokens         func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	CreatedBy             func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ReverseCreatedBies    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	DeletedBy             func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ReverseDeletedBies    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UpdatedBy             func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ReverseUpdatedBies    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserThenLoader[Q orm.Loadable]() userThenLoader[Q] {
	type EmailVerificationOtpsLoadInterface interface {
		LoadEmailVerificationOtps(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type PasswordResetOtpsLoadInterface interface {
		LoadPasswordResetOtps(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type RefreshTokensLoadInterface interface {
		LoadRefreshTokens(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CreatedByLoadInterface interface {
		LoadCreatedBy(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ReverseCreatedBiesLoadInterface interface {
		LoadReverseCreatedBies(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type DeletedByLoadInterface interface {
		LoadDeletedBy(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ReverseDeletedBiesLoadInterface interface {
		LoadReverseDeletedBies(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UpdatedByLoadInterface interface {
		LoadUpdatedBy(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ReverseUpdatedBiesLoadInterface interface {
		LoadReverseUpdatedBies(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userThenLoader[Q]{
		EmailVerificationOtps: thenLoadBuilder[Q](
			"EmailVerificationOtps",
			func(ctx context.Context, exec bob.Executor, retrieved EmailVerificationOtpsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadEmailVerificationOtps(ctx, exec, mods...)
			},
		),
		PasswordResetOtps: thenLoadBuilder[Q](
			"PasswordResetOtps",
			func(ctx context.Context, exec bob.Executor, retrieved PasswordResetOtpsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadPasswordResetOtps(ctx, exec, mods...)
			},
		),
		RefreshTokens: thenLoadBuilder[Q](
			"RefreshTokens",
			func(ctx context.Context, exec bob.Executor, retrieved RefreshTokensLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadRefreshTokens(ctx, exec, mods...)
			},
		),
		CreatedBy: thenLoadBuilder[Q](
			"CreatedBy",
			func(ctx context.Context, exec bob.Executor, retrieved CreatedByLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCreatedBy(ctx, exec, mods...)
			},
		),
		ReverseCreatedBies: thenLoadBuilder[Q](
			"ReverseCreatedBies",
			func(ctx context.Context, exec bob.Executor, retrieved ReverseCreatedBiesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadReverseCreatedBies(ctx, exec, mods...)
			},
		),
		DeletedBy: thenLoadBuilder[Q](
			"DeletedBy",
			func(ctx context.Context, exec bob.Executor, retrieved DeletedByLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadDeletedBy(ctx, exec, mods...)
			},
		),
		ReverseDeletedBies: thenLoadBuilder[Q](
			"ReverseDeletedBies",
			func(ctx context.Context, exec bob.Executor, retrieved ReverseDeletedBiesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadReverseDeletedBies(ctx, exec, mods...)
			},
		),
		UpdatedBy: thenLoadBuilder[Q](
			"UpdatedBy",
			func(ctx context.Context, exec bob.Executor, retrieved UpdatedByLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUpdatedBy(ctx, exec, mods...)
			},
		),
		ReverseUpdatedBies: thenLoadBuilder[Q](
			"ReverseUpdatedBies",
			func(ctx context.Context, exec bob.Executor, retrieved ReverseUpdatedBiesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadReverseUpdatedBies(ctx, exec, mods...)
			},
		),
	}
}

// LoadEmailVerificationOtps loads the user's EmailVerificationOtps into the .R struct
func (o *User) LoadEmailVerificationOtps(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.EmailVerificationOtps = nil

	related, err := o.EmailVerificationOtps(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.EmailVerificationOtps = related
	return nil
}

// LoadEmailVerificationOtps loads the user's EmailVerificationOtps into the .R struct
func (os UserSlice) LoadEmailVerificationOtps(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	emailVerificationOtps, err := os.EmailVerificationOtps(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.EmailVerificationOtps = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range emailVerificationOtps {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.EmailVerificationOtps = append(o.R.EmailVerificationOtps, rel)
		}
	}

	return nil
}

// LoadPasswordResetOtps loads the user's PasswordResetOtps into the .R struct
func (o *User) LoadPasswordResetOtps(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PasswordResetOtps = nil

	related, err := o.PasswordResetOtps(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.PasswordResetOtps = related
	return nil
}

// LoadPasswordResetOtps loads the user's PasswordResetOtps into the .R struct
func (os UserSlice) LoadPasswordResetOtps(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	passwordResetOtps, err := os.PasswordResetOtps(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.PasswordResetOtps = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range passwordResetOtps {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.PasswordResetOtps = append(o.R.PasswordResetOtps, rel)
		}
	}

	return nil
}

// LoadRefreshTokens loads the user's RefreshTokens into the .R struct
func (o *User) LoadRefreshTokens(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.RefreshTokens = nil

	related, err := o.RefreshTokens(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.RefreshTokens = related
	return nil
}

// LoadRefreshTokens loads the user's RefreshTokens into the .R struct
func (os UserSlice) LoadRefreshTokens(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	refreshTokens, err := os.RefreshTokens(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.RefreshTokens = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range refreshTokens {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.RefreshTokens = append(o.R.RefreshTokens, rel)
		}
	}

	return nil
}

// LoadCreatedBy loads the user's CreatedBy into the .R struct
func (o *User) LoadCreatedBy(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CreatedBy = nil

	related, err := o.RelatedCreatedBy(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.CreatedBy = o

	o.R.CreatedBy = related
	return nil
}

// LoadCreatedBy loads the user's CreatedBy into the .R struct
func (os UserSlice) LoadCreatedBy(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.RelatedCreatedBy(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.CreatedBy == rel.ID) {
				continue
			}

			rel.R.CreatedBy = o

			o.R.CreatedBy = rel
			break
		}
	}

	return nil
}

// LoadReverseCreatedBies loads the user's ReverseCreatedBies into the .R struct
func (o *User) LoadReverseCreatedBies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ReverseCreatedBies = nil

	related, err := o.ReverseCreatedBies(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.ReverseCreatedBies = UserSlice{o}
	}

	o.R.ReverseCreatedBies = related
	return nil
}

// LoadReverseCreatedBies loads the user's ReverseCreatedBies into the .R struct
func (os UserSlice) LoadReverseCreatedBies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.ReverseCreatedBies(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.ReverseCreatedBies = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.ID == rel.CreatedBy) {
				continue
			}

			rel.R.ReverseCreatedBies = append(rel.R.ReverseCreatedBies, o)

			o.R.ReverseCreatedBies = append(o.R.ReverseCreatedBies, rel)
		}
	}

	return nil
}

// LoadDeletedBy loads the user's DeletedBy into the .R struct
func (o *User) LoadDeletedBy(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.DeletedBy = nil

	related, err := o.RelatedDeletedBy(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.DeletedBy = o

	o.R.DeletedBy = related
	return nil
}

// LoadDeletedBy loads the user's DeletedBy into the .R struct
func (os UserSlice) LoadDeletedBy(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.RelatedDeletedBy(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {
			if !o.DeletedBy.IsValue() {
				continue
			}

			if !(o.DeletedBy.IsValue() && o.DeletedBy.MustGet() == rel.ID) {
				continue
			}

			rel.R.DeletedBy = o

			o.R.DeletedBy = rel
			break
		}
	}

	return nil
}

// LoadReverseDeletedBies loads the user's ReverseDeletedBies into the .R struct
func (o *User) LoadReverseDeletedBies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ReverseDeletedBies = nil

	related, err := o.ReverseDeletedBies(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.ReverseDeletedBies = UserSlice{o}
	}

	o.R.ReverseDeletedBies = related
	return nil
}

// LoadReverseDeletedBies loads the user's ReverseDeletedBies into the .R struct
func (os UserSlice) LoadReverseDeletedBies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.ReverseDeletedBies(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.ReverseDeletedBies = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !rel.DeletedBy.IsValue() {
				continue
			}
			if !(rel.DeletedBy.IsValue() && o.ID == rel.DeletedBy.MustGet()) {
				continue
			}

			rel.R.ReverseDeletedBies = append(rel.R.ReverseDeletedBies, o)

			o.R.ReverseDeletedBies = append(o.R.ReverseDeletedBies, rel)
		}
	}

	return nil
}

// LoadUpdatedBy loads the user's UpdatedBy into the .R struct
func (o *User) LoadUpdatedBy(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UpdatedBy = nil

	related, err := o.RelatedUpdatedBy(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.UpdatedBy = o

	o.R.UpdatedBy = related
	return nil
}

// LoadUpdatedBy loads the user's UpdatedBy into the .R struct
func (os UserSlice) LoadUpdatedBy(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.RelatedUpdatedBy(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UpdatedBy == rel.ID) {
				continue
			}

			rel.R.UpdatedBy = o

			o.R.UpdatedBy = rel
			break
		}
	}

	return nil
}

// LoadReverseUpdatedBies loads the user's ReverseUpdatedBies into the .R struct
func (o *User) LoadReverseUpdatedBies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ReverseUpdatedBies = nil

	related, err := o.ReverseUpdatedBies(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.ReverseUpdatedBies = UserSlice{o}
	}

	o.R.ReverseUpdatedBies = related
	return nil
}

// LoadReverseUpdatedBies loads the user's ReverseUpdatedBies into the .R struct
func (os UserSlice) LoadReverseUpdatedBies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.ReverseUpdatedBies(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.ReverseUpdatedBies = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.ID == rel.UpdatedBy) {
				continue
			}

			rel.R.ReverseUpdatedBies = append(rel.R.ReverseUpdatedBies, o)

			o.R.ReverseUpdatedBies = append(o.R.ReverseUpdatedBies, rel)
		}
	}

	return nil
}

type userJoins[Q dialect.Joinable] struct {
	typ                   string
	EmailVerificationOtps modAs[Q, emailVerificationOtpColumns]
	PasswordResetOtps     modAs[Q, passwordResetOtpColumns]
	RefreshTokens         modAs[Q, refreshTokenColumns]
	CreatedBy             modAs[Q, userColumns]
	ReverseCreatedBies    modAs[Q, userColumns]
	DeletedBy             modAs[Q, userColumns]
	ReverseDeletedBies    modAs[Q, userColumns]
	UpdatedBy             modAs[Q, userColumns]
	ReverseUpdatedBies    modAs[Q, userColumns]
}

func (j userJoins[Q]) aliasedAs(alias string) userJoins[Q] {
	return buildUserJoins[Q](buildUserColumns(alias), j.typ)
}

func buildUserJoins[Q dialect.Joinable](cols userColumns, typ string) userJoins[Q] {
	return userJoins[Q]{
		typ: typ,
		EmailVerificationOtps: modAs[Q, emailVerificationOtpColumns]{
			c: EmailVerificationOtps.Columns,
			f: func(to emailVerificationOtpColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, EmailVerificationOtps.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		PasswordResetOtps: modAs[Q, passwordResetOtpColumns]{
			c: PasswordResetOtps.Columns,
			f: func(to passwordResetOtpColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PasswordResetOtps.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		RefreshTokens: modAs[Q, refreshTokenColumns]{
			c: RefreshTokens.Columns,
			f: func(to refreshTokenColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, RefreshTokens.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		CreatedBy: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.CreatedBy),
					))
				}

				return mods
			},
		},
		ReverseCreatedBies: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.CreatedBy.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		DeletedBy: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.DeletedBy),
					))
				}

				return mods
			},
		},
		ReverseDeletedBies: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.DeletedBy.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		UpdatedBy: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UpdatedBy),
					))
				}

				return mods
			},
		},
		ReverseUpdatedBies: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.UpdatedBy.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
