// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	"time"

	bob "github.com/stephenafamo/bob"
	mock "github.com/stretchr/testify/mock"

	models "github.com/letenk/golang-authentication/bob/models"
)

// MockPasswordResetOTPRepository is an autogenerated mock type for the PasswordResetOTPRepository type
type MockPasswordResetOTPRepository struct {
	mock.Mock
}

type MockPasswordResetOTPRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordResetOTPRepository) EXPECT() *MockPasswordResetOTPRepository_Expecter {
	return &MockPasswordResetOTPRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, code, expiresAt
func (_m *MockPasswordResetOTPRepository) Create(ctx context.Context, userID int64, code string, expiresAt time.Time) (*models.PasswordResetOtp, error) {
	ret := _m.Called(ctx, userID, code, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.PasswordResetOtp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, time.Time) (*models.PasswordResetOtp, error)); ok {
		return rf(ctx, userID, code, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, time.Time) *models.PasswordResetOtp); ok {
		r0 = rf(ctx, userID, code, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PasswordResetOtp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, time.Time) error); ok {
		r1 = rf(ctx, userID, code, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordResetOTPRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPasswordResetOTPRepository_Create_Call struct {
	*mock.Call
}

func (_e *MockPasswordResetOTPRepository_Expecter) Create(ctx, userID, code, expiresAt interface{}) *MockPasswordResetOTPRepository_Create_Call {
	return &MockPasswordResetOTPRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, code, expiresAt)}
}

func (_c *MockPasswordResetOTPRepository_Create_Call) Run(run func(ctx context.Context, userID int64, code string, expiresAt time.Time)) *MockPasswordResetOTPRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockPasswordResetOTPRepository_Create_Call) Return(_a0 *models.PasswordResetOtp, _a1 error) *MockPasswordResetOTPRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordResetOTPRepository_Create_Call) RunAndReturn(run func(context.Context, int64, string, time.Time) (*models.PasswordResetOtp, error)) *MockPasswordResetOTPRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindValidByUserAndCode provides a mock function with given fields: ctx, userID, code
func (_m *MockPasswordResetOTPRepository) FindValidByUserAndCode(ctx context.Context, userID int64, code string) (*models.PasswordResetOtp, error) {
	ret := _m.Called(ctx, userID, code)

	if len(ret) == 0 {
		panic("no return value specified for FindValidByUserAndCode")
	}

	var r0 *models.PasswordResetOtp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*models.PasswordResetOtp, error)); ok {
		return rf(ctx, userID, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *models.PasswordResetOtp); ok {
		r0 = rf(ctx, userID, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PasswordResetOtp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordResetOTPRepository_FindValidByUserAndCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindValidByUserAndCode'
type MockPasswordResetOTPRepository_FindValidByUserAndCode_Call struct {
	*mock.Call
}

func (_e *MockPasswordResetOTPRepository_Expecter) FindValidByUserAndCode(ctx, userID, code interface{}) *MockPasswordResetOTPRepository_FindValidByUserAndCode_Call {
	return &MockPasswordResetOTPRepository_FindValidByUserAndCode_Call{Call: _e.mock.On("FindValidByUserAndCode", ctx, userID, code)}
}

func (_c *MockPasswordResetOTPRepository_FindValidByUserAndCode_Call) Run(run func(ctx context.Context, userID int64, code string)) *MockPasswordResetOTPRepository_FindValidByUserAndCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockPasswordResetOTPRepository_FindValidByUserAndCode_Call) Return(_a0 *models.PasswordResetOtp, _a1 error) *MockPasswordResetOTPRepository_FindValidByUserAndCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordResetOTPRepository_FindValidByUserAndCode_Call) RunAndReturn(run func(context.Context, int64, string) (*models.PasswordResetOtp, error)) *MockPasswordResetOTPRepository_FindValidByUserAndCode_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function with given fields: ctx, id
func (_m *MockPasswordResetOTPRepository) MarkUsed(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetOTPRepository_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type MockPasswordResetOTPRepository_MarkUsed_Call struct {
	*mock.Call
}

func (_e *MockPasswordResetOTPRepository_Expecter) MarkUsed(ctx, id interface{}) *MockPasswordResetOTPRepository_MarkUsed_Call {
	return &MockPasswordResetOTPRepository_MarkUsed_Call{Call: _e.mock.On("MarkUsed", ctx, id)}
}

func (_c *MockPasswordResetOTPRepository_MarkUsed_Call) Run(run func(ctx context.Context, id int64)) *MockPasswordResetOTPRepository_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockPasswordResetOTPRepository_MarkUsed_Call) Return(_a0 error) *MockPasswordResetOTPRepository_MarkUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetOTPRepository_MarkUsed_Call) RunAndReturn(run func(context.Context, int64) error) *MockPasswordResetOTPRepository_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidatePreviousByUserID provides a mock function with given fields: ctx, userID
func (_m *MockPasswordResetOTPRepository) InvalidatePreviousByUserID(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidatePreviousByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetOTPRepository_InvalidatePreviousByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidatePreviousByUserID'
type MockPasswordResetOTPRepository_InvalidatePreviousByUserID_Call struct {
	*mock.Call
}

func (_e *MockPasswordResetOTPRepository_Expecter) InvalidatePreviousByUserID(ctx, userID interface{}) *MockPasswordResetOTPRepository_InvalidatePreviousByUserID_Call {
	return &MockPasswordResetOTPRepository_InvalidatePreviousByUserID_Call{Call: _e.mock.On("InvalidatePreviousByUserID", ctx, userID)}
}

func (_c *MockPasswordResetOTPRepository_InvalidatePreviousByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockPasswordResetOTPRepository_InvalidatePreviousByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockPasswordResetOTPRepository_InvalidatePreviousByUserID_Call) Return(_a0 error) *MockPasswordResetOTPRepository_InvalidatePreviousByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetOTPRepository_InvalidatePreviousByUserID_Call) RunAndReturn(run func(context.Context, int64) error) *MockPasswordResetOTPRepository_InvalidatePreviousByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithExec provides a mock function with given fields: ctx, exec, userID, code, expiresAt
func (_m *MockPasswordResetOTPRepository) CreateWithExec(ctx context.Context, exec bob.Executor, userID int64, code string, expiresAt time.Time) (*models.PasswordResetOtp, error) {
	ret := _m.Called(ctx, exec, userID, code, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithExec")
	}

	var r0 *models.PasswordResetOtp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bob.Executor, int64, string, time.Time) (*models.PasswordResetOtp, error)); ok {
		return rf(ctx, exec, userID, code, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bob.Executor, int64, string, time.Time) *models.PasswordResetOtp); ok {
		r0 = rf(ctx, exec, userID, code, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PasswordResetOtp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bob.Executor, int64, string, time.Time) error); ok {
		r1 = rf(ctx, exec, userID, code, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordResetOTPRepository_CreateWithExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithExec'
type MockPasswordResetOTPRepository_CreateWithExec_Call struct {
	*mock.Call
}

func (_e *MockPasswordResetOTPRepository_Expecter) CreateWithExec(ctx, exec, userID, code, expiresAt interface{}) *MockPasswordResetOTPRepository_CreateWithExec_Call {
	return &MockPasswordResetOTPRepository_CreateWithExec_Call{Call: _e.mock.On("CreateWithExec", ctx, exec, userID, code, expiresAt)}
}

func (_c *MockPasswordResetOTPRepository_CreateWithExec_Call) Run(run func(ctx context.Context, exec bob.Executor, userID int64, code string, expiresAt time.Time)) *MockPasswordResetOTPRepository_CreateWithExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bob.Executor), args[2].(int64), args[3].(string), args[4].(time.Time))
	})
	return _c
}

func (_c *MockPasswordResetOTPRepository_CreateWithExec_Call) Return(_a0 *models.PasswordResetOtp, _a1 error) *MockPasswordResetOTPRepository_CreateWithExec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordResetOTPRepository_CreateWithExec_Call) RunAndReturn(run func(context.Context, bob.Executor, int64, string, time.Time) (*models.PasswordResetOtp, error)) *MockPasswordResetOTPRepository_CreateWithExec_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsedWithExec provides a mock function with given fields: ctx, exec, id
func (_m *MockPasswordResetOTPRepository) MarkUsedWithExec(ctx context.Context, exec bob.Executor, id int64) error {
	ret := _m.Called(ctx, exec, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsedWithExec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bob.Executor, int64) error); ok {
		r0 = rf(ctx, exec, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetOTPRepository_MarkUsedWithExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsedWithExec'
type MockPasswordResetOTPRepository_MarkUsedWithExec_Call struct {
	*mock.Call
}

func (_e *MockPasswordResetOTPRepository_Expecter) MarkUsedWithExec(ctx, exec, id interface{}) *MockPasswordResetOTPRepository_MarkUsedWithExec_Call {
	return &MockPasswordResetOTPRepository_MarkUsedWithExec_Call{Call: _e.mock.On("MarkUsedWithExec", ctx, exec, id)}
}

func (_c *MockPasswordResetOTPRepository_MarkUsedWithExec_Call) Run(run func(ctx context.Context, exec bob.Executor, id int64)) *MockPasswordResetOTPRepository_MarkUsedWithExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bob.Executor), args[2].(int64))
	})
	return _c
}

func (_c *MockPasswordResetOTPRepository_MarkUsedWithExec_Call) Return(_a0 error) *MockPasswordResetOTPRepository_MarkUsedWithExec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetOTPRepository_MarkUsedWithExec_Call) RunAndReturn(run func(context.Context, bob.Executor, int64) error) *MockPasswordResetOTPRepository_MarkUsedWithExec_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidatePreviousByUserIDWithExec provides a mock function with given fields: ctx, exec, userID
func (_m *MockPasswordResetOTPRepository) InvalidatePreviousByUserIDWithExec(ctx context.Context, exec bob.Executor, userID int64) error {
	ret := _m.Called(ctx, exec, userID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidatePreviousByUserIDWithExec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bob.Executor, int64) error); ok {
		r0 = rf(ctx, exec, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetOTPRepository_InvalidatePreviousByUserIDWithExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidatePreviousByUserIDWithExec'
type MockPasswordResetOTPRepository_InvalidatePreviousByUserIDWithExec_Call struct {
	*mock.Call
}

func (_e *MockPasswordResetOTPRepository_Expecter) InvalidatePreviousByUserIDWithExec(ctx, exec, userID interface{}) *MockPasswordResetOTPRepository_InvalidatePreviousByUserIDWithExec_Call {
	return &MockPasswordResetOTPRepository_InvalidatePreviousByUserIDWithExec_Call{Call: _e.mock.On("InvalidatePreviousByUserIDWithExec", ctx, exec, userID)}
}

func (_c *MockPasswordResetOTPRepository_InvalidatePreviousByUserIDWithExec_Call) Run(run func(ctx context.Context, exec bob.Executor, userID int64)) *MockPasswordResetOTPRepository_InvalidatePreviousByUserIDWithExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bob.Executor), args[2].(int64))
	})
	return _c
}

func (_c *MockPasswordResetOTPRepository_InvalidatePreviousByUserIDWithExec_Call) Return(_a0 error) *MockPasswordResetOTPRepository_InvalidatePreviousByUserIDWithExec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetOTPRepository_InvalidatePreviousByUserIDWithExec_Call) RunAndReturn(run func(context.Context, bob.Executor, int64) error) *MockPasswordResetOTPRepository_InvalidatePreviousByUserIDWithExec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordResetOTPRepository creates a new instance of MockPasswordResetOTPRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordResetOTPRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordResetOTPRepository {
	mock := &MockPasswordResetOTPRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
