// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/letenk/golang-authentication/internal/applications/auth/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/letenk/golang-authentication/bob/models"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// DeleteAccount provides a mock function with given fields: ctx, userID
func (_m *MockAuthService) DeleteAccount(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockAuthService_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAuthService_Expecter) DeleteAccount(ctx interface{}, userID interface{}) *MockAuthService_DeleteAccount_Call {
	return &MockAuthService_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, userID)}
}

func (_c *MockAuthService_DeleteAccount_Call) Run(run func(ctx context.Context, userID int64)) *MockAuthService_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAuthService_DeleteAccount_Call) Return(_a0 error) *MockAuthService_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_DeleteAccount_Call) RunAndReturn(run func(context.Context, int64) error) *MockAuthService_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetMe provides a mock function with given fields: ctx, userID
func (_m *MockAuthService) GetMe(ctx context.Context, userID int64) (*dto.GetMeResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 *dto.GetMeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*dto.GetMeResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *dto.GetMeResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetMeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type MockAuthService_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAuthService_Expecter) GetMe(ctx interface{}, userID interface{}) *MockAuthService_GetMe_Call {
	return &MockAuthService_GetMe_Call{Call: _e.mock.On("GetMe", ctx, userID)}
}

func (_c *MockAuthService_GetMe_Call) Run(run func(ctx context.Context, userID int64)) *MockAuthService_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAuthService_GetMe_Call) Return(_a0 *dto.GetMeResponse, _a1 error) *MockAuthService_GetMe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_GetMe_Call) RunAndReturn(run func(context.Context, int64) (*dto.GetMeResponse, error)) *MockAuthService_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, req, ipAddress, userAgent
func (_m *MockAuthService) Login(ctx context.Context, req *dto.LoginRequest, ipAddress string, userAgent string) (*dto.LoginResponse, error) {
	ret := _m.Called(ctx, req, ipAddress, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.LoginRequest, string, string) (*dto.LoginResponse, error)); ok {
		return rf(ctx, req, ipAddress, userAgent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.LoginRequest, string, string) *dto.LoginResponse); ok {
		r0 = rf(ctx, req, ipAddress, userAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.LoginRequest, string, string) error); ok {
		r1 = rf(ctx, req, ipAddress, userAgent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.LoginRequest
//   - ipAddress string
//   - userAgent string
func (_e *MockAuthService_Expecter) Login(ctx interface{}, req interface{}, ipAddress interface{}, userAgent interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, req, ipAddress, userAgent)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, req *dto.LoginRequest, ipAddress string, userAgent string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.LoginRequest), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(_a0 *dto.LoginResponse, _a1 error) *MockAuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(context.Context, *dto.LoginRequest, string, string) (*dto.LoginResponse, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthService) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthService_Expecter) Logout(ctx interface{}, refreshToken interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(_a0 error) *MockAuthService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAll provides a mock function with given fields: ctx, userID
func (_m *MockAuthService) LogoutAll(ctx context.Context, userID int64) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_LogoutAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAll'
type MockAuthService_LogoutAll_Call struct {
	*mock.Call
}

// LogoutAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAuthService_Expecter) LogoutAll(ctx interface{}, userID interface{}) *MockAuthService_LogoutAll_Call {
	return &MockAuthService_LogoutAll_Call{Call: _e.mock.On("LogoutAll", ctx, userID)}
}

func (_c *MockAuthService_LogoutAll_Call) Run(run func(ctx context.Context, userID int64)) *MockAuthService_LogoutAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAuthService_LogoutAll_Call) Return(_a0 int, _a1 error) *MockAuthService_LogoutAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_LogoutAll_Call) RunAndReturn(run func(context.Context, int64) (int, error)) *MockAuthService_LogoutAll_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, req, ipAddress, userAgent
func (_m *MockAuthService) RefreshToken(ctx context.Context, req *dto.RefreshTokenRequest, ipAddress string, userAgent string) (*dto.RefreshTokenResponse, error) {
	ret := _m.Called(ctx, req, ipAddress, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *dto.RefreshTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RefreshTokenRequest, string, string) (*dto.RefreshTokenResponse, error)); ok {
		return rf(ctx, req, ipAddress, userAgent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RefreshTokenRequest, string, string) *dto.RefreshTokenResponse); ok {
		r0 = rf(ctx, req, ipAddress, userAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RefreshTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.RefreshTokenRequest, string, string) error); ok {
		r1 = rf(ctx, req, ipAddress, userAgent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.RefreshTokenRequest
//   - ipAddress string
//   - userAgent string
func (_e *MockAuthService_Expecter) RefreshToken(ctx interface{}, req interface{}, ipAddress interface{}, userAgent interface{}) *MockAuthService_RefreshToken_Call {
	return &MockAuthService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, req, ipAddress, userAgent)}
}

func (_c *MockAuthService_RefreshToken_Call) Run(run func(ctx context.Context, req *dto.RefreshTokenRequest, ipAddress string, userAgent string)) *MockAuthService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.RefreshTokenRequest), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) Return(_a0 *dto.RefreshTokenResponse, _a1 error) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) RunAndReturn(run func(context.Context, *dto.RefreshTokenRequest, string, string) (*dto.RefreshTokenResponse, error)) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, param
func (_m *MockAuthService) Register(ctx context.Context, param *dto.ParameterRegister) (*models.User, error) {
	ret := _m.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ParameterRegister) (*models.User, error)); ok {
		return rf(ctx, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ParameterRegister) *models.User); ok {
		r0 = rf(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.ParameterRegister) error); ok {
		r1 = rf(ctx, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - param *dto.ParameterRegister
func (_e *MockAuthService_Expecter) Register(ctx interface{}, param interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, param)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, param *dto.ParameterRegister)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.ParameterRegister))
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(_a0 *models.User, _a1 error) *MockAuthService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(context.Context, *dto.ParameterRegister) (*models.User, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessions provides a mock function with given fields: ctx, userID
func (_m *MockAuthService) GetSessions(ctx context.Context, userID int64) ([]*dto.ActiveSessionResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessions")
	}

	var r0 []*dto.ActiveSessionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*dto.ActiveSessionResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*dto.ActiveSessionResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ActiveSessionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_GetSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessions'
type MockAuthService_GetSessions_Call struct {
	*mock.Call
}

// GetSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAuthService_Expecter) GetSessions(ctx interface{}, userID interface{}) *MockAuthService_GetSessions_Call {
	return &MockAuthService_GetSessions_Call{Call: _e.mock.On("GetSessions", ctx, userID)}
}

func (_c *MockAuthService_GetSessions_Call) Run(run func(ctx context.Context, userID int64)) *MockAuthService_GetSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAuthService_GetSessions_Call) Return(_a0 []*dto.ActiveSessionResponse, _a1 error) *MockAuthService_GetSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_GetSessions_Call) RunAndReturn(run func(context.Context, int64) ([]*dto.ActiveSessionResponse, error)) *MockAuthService_GetSessions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, userID, req
func (_m *MockAuthService) UpdateProfile(ctx context.Context, userID int64, req *dto.UpdateProfileRequest) (*dto.UserResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *dto.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *dto.UpdateProfileRequest) (*dto.UserResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *dto.UpdateProfileRequest) *dto.UserResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *dto.UpdateProfileRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockAuthService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - req *dto.UpdateProfileRequest
func (_e *MockAuthService_Expecter) UpdateProfile(ctx interface{}, userID interface{}, req interface{}) *MockAuthService_UpdateProfile_Call {
	return &MockAuthService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, req)}
}

func (_c *MockAuthService_UpdateProfile_Call) Run(run func(ctx context.Context, userID int64, req *dto.UpdateProfileRequest)) *MockAuthService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*dto.UpdateProfileRequest))
	})
	return _c
}

func (_c *MockAuthService_UpdateProfile_Call) Return(_a0 *dto.UserResponse, _a1 error) *MockAuthService_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_UpdateProfile_Call) RunAndReturn(run func(context.Context, int64, *dto.UpdateProfileRequest) (*dto.UserResponse, error)) *MockAuthService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, userID, req
func (_m *MockAuthService) UpdatePassword(ctx context.Context, userID int64, req *dto.UpdatePasswordRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *dto.UpdatePasswordRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockAuthService_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - req *dto.UpdatePasswordRequest
func (_e *MockAuthService_Expecter) UpdatePassword(ctx interface{}, userID interface{}, req interface{}) *MockAuthService_UpdatePassword_Call {
	return &MockAuthService_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, req)}
}

func (_c *MockAuthService_UpdatePassword_Call) Run(run func(ctx context.Context, userID int64, req *dto.UpdatePasswordRequest)) *MockAuthService_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*dto.UpdatePasswordRequest))
	})
	return _c
}

func (_c *MockAuthService_UpdatePassword_Call) Return(_a0 error) *MockAuthService_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_UpdatePassword_Call) RunAndReturn(run func(context.Context, int64, *dto.UpdatePasswordRequest) error) *MockAuthService_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: ctx, userID, sessionID
func (_m *MockAuthService) RevokeSession(ctx context.Context, userID int64, sessionID int64) error {
	ret := _m.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockAuthService_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - sessionID int64
func (_e *MockAuthService_Expecter) RevokeSession(ctx interface{}, userID interface{}, sessionID interface{}) *MockAuthService_RevokeSession_Call {
	return &MockAuthService_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, userID, sessionID)}
}

func (_c *MockAuthService_RevokeSession_Call) Run(run func(ctx context.Context, userID int64, sessionID int64)) *MockAuthService_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockAuthService_RevokeSession_Call) Return(_a0 error) *MockAuthService_RevokeSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_RevokeSession_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockAuthService_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// ForgotPassword provides a mock function with given fields: ctx, email
func (_m *MockAuthService) ForgotPassword(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_ForgotPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgotPassword'
type MockAuthService_ForgotPassword_Call struct {
	*mock.Call
}

// ForgotPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthService_Expecter) ForgotPassword(ctx interface{}, email interface{}) *MockAuthService_ForgotPassword_Call {
	return &MockAuthService_ForgotPassword_Call{Call: _e.mock.On("ForgotPassword", ctx, email)}
}

func (_c *MockAuthService_ForgotPassword_Call) Run(run func(ctx context.Context, email string)) *MockAuthService_ForgotPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_ForgotPassword_Call) Return(_a0 error) *MockAuthService_ForgotPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_ForgotPassword_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthService_ForgotPassword_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function with given fields: ctx, req
func (_m *MockAuthService) ResetPassword(ctx context.Context, req *dto.ResetPasswordRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ResetPasswordRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockAuthService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.ResetPasswordRequest
func (_e *MockAuthService_Expecter) ResetPassword(ctx interface{}, req interface{}) *MockAuthService_ResetPassword_Call {
	return &MockAuthService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, req)}
}

func (_c *MockAuthService_ResetPassword_Call) Run(run func(ctx context.Context, req *dto.ResetPasswordRequest)) *MockAuthService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.ResetPasswordRequest))
	})
	return _c
}

func (_c *MockAuthService_ResetPassword_Call) Return(_a0 error) *MockAuthService_ResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_ResetPassword_Call) RunAndReturn(run func(context.Context, *dto.ResetPasswordRequest) error) *MockAuthService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
