// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockEmailService is an autogenerated mock type for the EmailService type
type MockEmailService struct {
	mock.Mock
}

type MockEmailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailService) EXPECT() *MockEmailService_Expecter {
	return &MockEmailService_Expecter{mock: &_m.Mock}
}

// SendOTP provides a mock function with given fields: toEmail, toName, otp
func (_m *MockEmailService) SendOTP(toEmail string, toName string, otp string) error {
	ret := _m.Called(toEmail, toName, otp)

	if len(ret) == 0 {
		panic("no return value specified for SendOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(toEmail, toName, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailService_SendOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOTP'
type MockEmailService_SendOTP_Call struct {
	*mock.Call
}

// SendOTP is a helper method to define mock.On call
//   - toEmail string
//   - toName string
//   - otp string
func (_e *MockEmailService_Expecter) SendOTP(toEmail interface{}, toName interface{}, otp interface{}) *MockEmailService_SendOTP_Call {
	return &MockEmailService_SendOTP_Call{Call: _e.mock.On("SendOTP", toEmail, toName, otp)}
}

func (_c *MockEmailService_SendOTP_Call) Run(run func(toEmail string, toName string, otp string)) *MockEmailService_SendOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockEmailService_SendOTP_Call) Return(_a0 error) *MockEmailService_SendOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailService_SendOTP_Call) RunAndReturn(run func(string, string, string) error) *MockEmailService_SendOTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailService creates a new instance of MockEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailService {
	mock := &MockEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
