// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var EmailVerificationOtpErrors = &emailVerificationOtpErrors{
	ErrUniqueEmailVerificationOtpsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "email_verification_otps",
		columns: []string{"id"},
		s:       "email_verification_otps_pkey",
	},
}

type emailVerificationOtpErrors struct {
	ErrUniqueEmailVerificationOtpsPkey *UniqueConstraintError
}
