// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var OtpErrors = &otpErrors{
	ErrUniqueOtpsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "otps",
		columns: []string{"id"},
		s:       "otps_pkey",
	},
}

type otpErrors struct {
	ErrUniqueOtpsPkey *UniqueConstraintError
}
