// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var PasswordResetOtpErrors = &passwordResetOtpErrors{
	ErrUniquePasswordResetOtpsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "password_reset_otps",
		columns: []string{"id"},
		s:       "password_reset_otps_pkey",
	},
}

type passwordResetOtpErrors struct {
	ErrUniquePasswordResetOtpsPkey *UniqueConstraintError
}
