// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var RefreshTokenErrors = &refreshTokenErrors{
	ErrUniqueRefreshTokensPkey: &UniqueConstraintError{
		schema:  "",
		table:   "refresh_tokens",
		columns: []string{"id"},
		s:       "refresh_tokens_pkey",
	},

	ErrUniqueRefreshTokensTokenKey: &UniqueConstraintError{
		schema:  "",
		table:   "refresh_tokens",
		columns: []string{"token"},
		s:       "refresh_tokens_token_key",
	},
}

type refreshTokenErrors struct {
	ErrUniqueRefreshTokensPkey *UniqueConstraintError

	ErrUniqueRefreshTokensTokenKey *UniqueConstraintError
}
