// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var UserErrors = &userErrors{
	ErrUniqueUsersPkey: &UniqueConstraintError{
		schema:  "",
		table:   "users",
		columns: []string{"id"},
		s:       "users_pkey",
	},

	ErrUniqueUsersEmailKey: &UniqueConstraintError{
		schema:  "",
		table:   "users",
		columns: []string{"email"},
		s:       "users_email_key",
	},

	ErrUniqueUsersPhoneKey: &UniqueConstraintError{
		schema:  "",
		table:   "users",
		columns: []string{"phone"},
		s:       "users_phone_key",
	},
}

type userErrors struct {
	ErrUniqueUsersPkey *UniqueConstraintError

	ErrUniqueUsersEmailKey *UniqueConstraintError

	ErrUniqueUsersPhoneKey *UniqueConstraintError
}
